/**
 * @file nmo_object_enum_guids.h
 * @brief GUIDs for CK/VX enums and flags used in reflection fields
 *
 * NOTE:
 * - Some GUIDs are explicitly overridden in enum_overrides.json.
 * - Others use the auto-generated GUIDs from nmo_type_generate_guid(name).
 */

#ifndef NMO_OBJECT_ENUM_GUIDS_H
#define NMO_OBJECT_ENUM_GUIDS_H

#include "core/nmo_guid.h"
#include "object/nmo_param_guids.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Auto-generated GUIDs (nmo_type_generate_guid) */
#define NMO_GUID_ENUM_CK_OBJECT_FLAGS NMO_GUID(0xbeffcf75, 0x7a6f7a77)
#define NMO_GUID_ENUM_CK_OBJECT_FLAGS_INIT NMO_GUID_INIT(0xbeffcf75, 0x7a6f7a77)
#define NMO_GUID_ENUM_CK_SCENE_FLAGS NMO_GUID(0x8833764d, 0x973e6508)
#define NMO_GUID_ENUM_CK_SCENE_FLAGS_INIT NMO_GUID_INIT(0x8833764d, 0x973e6508)
#define NMO_GUID_ENUM_CK_2DENTITY_FLAGS NMO_GUID(0xefee90ae, 0x8c2fe0b7)
#define NMO_GUID_ENUM_CK_2DENTITY_FLAGS_INIT NMO_GUID_INIT(0xefee90ae, 0x8c2fe0b7)
#define NMO_GUID_ENUM_CK_3DENTITY_FLAGS NMO_GUID(0xefee90ae, 0xa27dd9a9)
#define NMO_GUID_ENUM_CK_3DENTITY_FLAGS_INIT NMO_GUID_INIT(0xefee90ae, 0xa27dd9a9)
#define NMO_GUID_ENUM_VX_MOVEABLE_FLAGS NMO_GUID(0x901d7d23, 0x18e2a2c5)
#define NMO_GUID_ENUM_VX_MOVEABLE_FLAGS_INIT NMO_GUID_INIT(0x901d7d23, 0x18e2a2c5)
#define NMO_GUID_ENUM_VXMESH_FLAGS NMO_GUID(0xb4d819ba, 0x694d1499)
#define NMO_GUID_ENUM_VXMESH_FLAGS_INIT NMO_GUID_INIT(0xb4d819ba, 0x694d1499)
#define NMO_GUID_ENUM_CK_BEHAVIOR_FLAGS NMO_GUID(0xca57328f, 0x1edda205)
#define NMO_GUID_ENUM_CK_BEHAVIOR_FLAGS_INIT NMO_GUID_INIT(0xca57328f, 0x1edda205)
#define NMO_GUID_ENUM_CK_BEHAVIOR_TYPE NMO_GUID(0x90a8425a, 0x1f0a9405)
#define NMO_GUID_ENUM_CK_BEHAVIOR_TYPE_INIT NMO_GUID_INIT(0x90a8425a, 0x1f0a9405)
#define NMO_GUID_ENUM_CK_TEXTURE_SAVEOPTIONS NMO_GUID(0xb656be94, 0x1f32ceaf)
#define NMO_GUID_ENUM_CK_TEXTURE_SAVEOPTIONS_INIT NMO_GUID_INIT(0xb656be94, 0x1f32ceaf)
#define NMO_GUID_ENUM_CK_SOUND_SAVEOPTIONS NMO_GUID(0xf2ac90ae, 0xb47a9e0c)
#define NMO_GUID_ENUM_CK_SOUND_SAVEOPTIONS_INIT NMO_GUID_INIT(0xf2ac90ae, 0xb47a9e0c)
#define NMO_GUID_ENUM_CK_WAVESOUND_STATE NMO_GUID(0xc24205a8, 0xd005d9b2)
#define NMO_GUID_ENUM_CK_WAVESOUND_STATE_INIT NMO_GUID_INIT(0xc24205a8, 0xd005d9b2)
/* Explicit override GUIDs (enum_overrides.json) */
#define NMO_GUID_ENUM_CK_SCENEOBJECTACTIVITY_FLAGS CKPGUID_SCENEACTIVITYFLAGS
#define NMO_GUID_ENUM_CK_SCENEOBJECTACTIVITY_FLAGS_INIT CKPGUID_SCENEACTIVITYFLAGS_INIT
#define NMO_GUID_ENUM_VXSPRITE3D_TYPE              CKPGUID_3DSPRITEMODE
#define NMO_GUID_ENUM_VXSPRITE3D_TYPE_INIT         CKPGUID_3DSPRITEMODE_INIT
#define NMO_GUID_ENUM_VX_PIXELFORMAT               CKPGUID_PIXELFORMAT
#define NMO_GUID_ENUM_VX_PIXELFORMAT_INIT          CKPGUID_PIXELFORMAT_INIT
#define NMO_GUID_ENUM_VXFOG_MODE                   CKPGUID_FOGMODE
#define NMO_GUID_ENUM_VXFOG_MODE_INIT              CKPGUID_FOGMODE_INIT
#define NMO_GUID_ENUM_CK_ARRAYTYPE                CKPGUID_ARRAYTYPE
#define NMO_GUID_ENUM_CK_ARRAYTYPE_INIT           CKPGUID_ARRAYTYPE_INIT
#define NMO_GUID_ENUM_CK_PARAMETER_MODE           CKPGUID_PARAMETER_MODE
#define NMO_GUID_ENUM_CK_PARAMETER_MODE_INIT      CKPGUID_PARAMETER_MODE_INIT
#define NMO_GUID_ENUM_CK_PATCHMESH_FORMAT         CKPGUID_PATCHMESH_FORMAT
#define NMO_GUID_ENUM_CK_PATCHMESH_FORMAT_INIT    CKPGUID_PATCHMESH_FORMAT_INIT
#define NMO_GUID_ENUM_CK_OBJECTANIMATION_FORMAT   CKPGUID_OBJECTANIMATION_FORMAT
#define NMO_GUID_ENUM_CK_OBJECTANIMATION_FORMAT_INIT CKPGUID_OBJECTANIMATION_FORMAT_INIT

#ifdef __cplusplus
}
#endif

#endif /* NMO_OBJECT_ENUM_GUIDS_H */
