#!/usr/bin/env python3
"""
Generate Virtools data .inc files from exported JSON.

Reads:
  data/virtools_parameter_types.json
  data/virtools_operation_types.json
  data/virtools_building_blocks.json

Produces:
  src/type/virtools_param_types.inc
  src/type/virtools_operations.inc
  src/app/bb_registry_builtin.inc

Usage:
  python gen_virtools_data.py
"""

import json
import os
import sys


def c_escape(s):
    if not s:
        return ''
    return s.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n').replace('\r', '')


def guid_key(entry):
    g = entry['guid']
    return (g[0] & 0xFFFFFFFF, g[1] & 0xFFFFFFFF)


def dedup(entries):
    seen = set()
    result = []
    for e in sorted(entries, key=guid_key):
        key = (e['guid'][0], e['guid'][1])
        if key not in seen:
            seen.add(key)
            result.append(e)
    return result


HEADER = ('/* Auto-generated by tools/scripts/gen_virtools_data.py\n'
          ' * DO NOT EDIT — regenerate with: python tools/scripts/gen_virtools_data.py\n'
          ' */\n\n')

CATEGORY_MAP = {
    'primitive': 'NMO_TYPE_CATEGORY_SCALAR',
    'enum': 'NMO_TYPE_CATEGORY_ENUM',
    'flags': 'NMO_TYPE_CATEGORY_FLAGS',
    'struct': 'NMO_TYPE_CATEGORY_STRUCT',
}


def write_param_types_inc(path, entries):
    entries = dedup(entries)
    with open(path, 'w', encoding='utf-8') as f:
        f.write(HEADER)
        f.write('static nmo_status_t register_virtools_param_types(nmo_type_registry_t *registry) {\n')
        f.write('    nmo_type_descriptor_t desc;\n')
        f.write('    nmo_status_t st;\n\n')
        for pt in entries:
            d1, d2 = pt['guid']
            cat = CATEGORY_MAP.get(pt.get('category', 'primitive'), 'NMO_TYPE_CATEGORY_SCALAR')
            df = pt.get('derived_from')
            base = (f'NMO_GUID(0x{df[0]:08X}, 0x{df[1]:08X})'
                    if df and isinstance(df, list) and len(df) == 2 else 'NMO_GUID_NULL')
            f.write(f'    if (nmo_type_registry_guid_to_type_id(registry, NMO_GUID(0x{d1:08X}, 0x{d2:08X})) == NMO_TYPE_ID_INVALID) {{\n')
            f.write(f'        memset(&desc, 0, sizeof(desc));\n')
            f.write(f'        desc.guid = NMO_GUID(0x{d1:08X}, 0x{d2:08X});\n')
            f.write(f'        desc.name = "{c_escape(pt["name"])}"; desc.size = {pt.get("size", 0)};\n')
            f.write(f'        desc.category = {cat}; desc.class_id = {pt.get("class_id", 0)};\n')
            f.write(f'        desc.base_type = {base}; desc.valid = true;\n')
            f.write(f'        st = nmo_type_registry_register(registry, &desc); (void)st;\n')
            f.write(f'    }}\n')
        f.write('    return NMO_OK;\n}\n')
    return len(entries)


def write_operations_inc(path, entries):
    entries = dedup(entries)
    with open(path, 'w', encoding='utf-8') as f:
        f.write(HEADER)
        f.write('static nmo_status_t register_virtools_operation_types(nmo_type_registry_t *registry) {\n')
        f.write('    nmo_type_descriptor_t desc;\n')
        f.write('    nmo_status_t st;\n\n')
        for op in entries:
            d1, d2 = op['guid']
            f.write(f'    memset(&desc, 0, sizeof(desc));\n')
            f.write(f'    desc.guid = NMO_GUID(0x{d1:08X}, 0x{d2:08X});\n')
            f.write(f'    desc.name = "{c_escape(op["name"])}"; desc.category = NMO_TYPE_CATEGORY_OPERATION;\n')
            f.write(f'    desc.valid = true; st = nmo_type_registry_register(registry, &desc); (void)st;\n')
        f.write('    return NMO_OK;\n}\n')
    return len(entries)


def write_bb_registry_inc(path, entries):
    entries = dedup(entries)
    with open(path, 'w', encoding='utf-8') as f:
        f.write(HEADER)
        f.write('typedef struct bb_builtin_entry {\n')
        f.write('    nmo_guid_t guid;\n')
        f.write('    const char *name;\n')
        f.write('    const char *category;\n')
        f.write('    const char *dll;\n')
        f.write('} bb_builtin_entry_t;\n\n')
        f.write('static const bb_builtin_entry_t s_bb_builtin[] = {\n')
        for b in entries:
            d1, d2 = b['guid']
            f.write(f'    {{NMO_GUID_INIT(0x{d1:08X}, 0x{d2:08X}), '
                    f'"{c_escape(b["name"])}", '
                    f'"{c_escape(b.get("category", ""))}", '
                    f'"{c_escape(b.get("dll", ""))}"}},\n')
        f.write('};\n\n')
        f.write(f'#define BB_BUILTIN_COUNT {len(entries)}\n')
    return len(entries)


def main():
    root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    data_dir = os.path.join(root, 'data')

    pt_path = os.path.join(data_dir, 'virtools_parameter_types.json')
    op_path = os.path.join(data_dir, 'virtools_operation_types.json')
    bb_path = os.path.join(data_dir, 'virtools_building_blocks.json')

    for p in [pt_path, op_path, bb_path]:
        if not os.path.isfile(p):
            print(f'Error: {p} not found', file=sys.stderr)
            return 1

    pt = json.load(open(pt_path, encoding='utf-8'))
    ops = json.load(open(op_path, encoding='utf-8'))
    bbs = json.load(open(bb_path, encoding='utf-8'))
    print(f'Input: {len(pt)} param types, {len(ops)} operations, {len(bbs)} BBs')

    n1 = write_param_types_inc(os.path.join(root, 'src', 'type', 'virtools_param_types.inc'), pt)
    n2 = write_operations_inc(os.path.join(root, 'src', 'type', 'virtools_operations.inc'), ops)
    n3 = write_bb_registry_inc(os.path.join(root, 'src', 'app', 'bb_registry_builtin.inc'), bbs)

    print(f'Output:')
    print(f'  src/type/virtools_param_types.inc: {n1} entries')
    print(f'  src/type/virtools_operations.inc: {n2} entries')
    print(f'  src/app/bb_registry_builtin.inc: {n3} entries')
    return 0


if __name__ == '__main__':
    sys.exit(main())
