#!/usr/bin/env python3
"""
Generate all Virtools data files from VirtoolsDataExporter JSON.

Reads data/virtools_data.json and produces:
  - src/app/bb_registry_builtin.inc     (BB prototype sorted table)
  - src/type/type_registry_virtools_data.inc  (param type + operation type registrations)

Usage:
  python gen_virtools_data.py
  python gen_virtools_data.py --input data/virtools_data.json
"""

import argparse
import json
import os
import sys


def c_escape(s):
    if not s:
        return ''
    return s.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n').replace('\r', '')


def guid_key(entry):
    g = entry['guid']
    return (g[0] & 0xFFFFFFFF, g[1] & 0xFFFFFFFF)


def dedup(entries):
    seen = set()
    result = []
    for e in sorted(entries, key=guid_key):
        key = (e['guid'][0], e['guid'][1])
        if key not in seen:
            seen.add(key)
            result.append(e)
    return result


def category_to_c(cat):
    return {
        'primitive': 'NMO_TYPE_CATEGORY_SCALAR',
        'enum': 'NMO_TYPE_CATEGORY_ENUM',
        'flags': 'NMO_TYPE_CATEGORY_FLAGS',
        'struct': 'NMO_TYPE_CATEGORY_STRUCT',
    }.get(cat, 'NMO_TYPE_CATEGORY_SCALAR')


def write_bb_registry(path, bbs):
    bbs = dedup(bbs)
    with open(path, 'w', encoding='utf-8') as f:
        f.write('/* Auto-generated by tools/scripts/gen_virtools_data.py\n')
        f.write(' * Source: data/virtools_data.json\n')
        f.write(' * DO NOT EDIT — regenerate with: python tools/scripts/gen_virtools_data.py\n')
        f.write(' */\n\n')
        f.write('typedef struct bb_builtin_entry {\n')
        f.write('    nmo_guid_t guid;\n')
        f.write('    const char *name;\n')
        f.write('    const char *category;\n')
        f.write('    const char *dll;\n')
        f.write('} bb_builtin_entry_t;\n\n')
        f.write('static const bb_builtin_entry_t s_bb_builtin[] = {\n')
        for b in bbs:
            d1, d2 = b['guid']
            f.write(f'    {{NMO_GUID_INIT(0x{d1:08X}, 0x{d2:08X}), '
                    f'"{c_escape(b["name"])}", '
                    f'"{c_escape(b.get("category", ""))}", '
                    f'"{c_escape(b.get("dll", ""))}"}},\n')
        f.write('};\n\n')
        f.write(f'#define BB_BUILTIN_COUNT {len(bbs)}\n')
    return len(bbs)


def write_type_registry(path, param_types, operations):
    param_types = dedup(param_types)
    operations = dedup(operations)

    with open(path, 'w', encoding='utf-8') as f:
        f.write('/* Auto-generated by tools/scripts/gen_virtools_data.py\n')
        f.write(' * Source: data/virtools_data.json\n')
        f.write(' * DO NOT EDIT — regenerate with: python tools/scripts/gen_virtools_data.py\n')
        f.write(' */\n\n')

        # Parameter types
        f.write(f'static nmo_status_t register_virtools_param_types(nmo_type_registry_t *registry) {{\n')
        f.write('    nmo_type_descriptor_t desc;\n')
        f.write('    nmo_status_t st;\n\n')
        for pt in param_types:
            d1, d2 = pt['guid']
            name = c_escape(pt['name'])
            size = pt.get('size', 0)
            cat = category_to_c(pt.get('category', 'primitive'))
            class_id = pt.get('class_id', 0)
            df = pt.get('derived_from')
            base = (f'NMO_GUID(0x{df[0]:08X}, 0x{df[1]:08X})'
                    if df and isinstance(df, list) and len(df) == 2 else 'NMO_GUID_NULL')
            f.write(f'    if (nmo_type_registry_guid_to_type_id(registry, NMO_GUID(0x{d1:08X}, 0x{d2:08X})) == NMO_TYPE_ID_INVALID) {{\n')
            f.write(f'        memset(&desc, 0, sizeof(desc));\n')
            f.write(f'        desc.guid = NMO_GUID(0x{d1:08X}, 0x{d2:08X});\n')
            f.write(f'        desc.name = "{name}"; desc.size = {size};\n')
            f.write(f'        desc.category = {cat}; desc.class_id = {class_id};\n')
            f.write(f'        desc.base_type = {base}; desc.valid = true;\n')
            f.write(f'        st = nmo_type_registry_register(registry, &desc); (void)st;\n')
            f.write(f'    }}\n')
        f.write('    return NMO_OK;\n}\n\n')

        # Operation types
        f.write(f'static nmo_status_t register_virtools_operation_types(nmo_type_registry_t *registry) {{\n')
        f.write('    nmo_type_descriptor_t desc;\n')
        f.write('    nmo_status_t st;\n\n')
        for op in operations:
            d1, d2 = op['guid']
            name = c_escape(op['name'])
            f.write(f'    memset(&desc, 0, sizeof(desc));\n')
            f.write(f'    desc.guid = NMO_GUID(0x{d1:08X}, 0x{d2:08X});\n')
            f.write(f'    desc.name = "{name}"; desc.category = NMO_TYPE_CATEGORY_OPERATION;\n')
            f.write(f'    desc.valid = true; st = nmo_type_registry_register(registry, &desc); (void)st;\n')
        f.write('    return NMO_OK;\n}\n')

    return len(param_types), len(operations)


def main():
    parser = argparse.ArgumentParser(description='Generate Virtools data .inc files')
    parser.add_argument('--input', help='Input JSON path')
    args = parser.parse_args()

    root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    input_path = args.input or os.path.join(root, 'data', 'virtools_data.json')

    if not os.path.isfile(input_path):
        print(f'Error: {input_path} not found', file=sys.stderr)
        return 1

    data = json.load(open(input_path, encoding='utf-8'))
    pt = data.get('parameter_types', [])
    ops = data.get('operation_types', [])
    bbs = data.get('building_blocks', [])
    print(f'Input: {len(pt)} param types, {len(ops)} operations, {len(bbs)} BBs')

    bb_count = write_bb_registry(os.path.join(root, 'src', 'app', 'bb_registry_builtin.inc'), bbs)
    pt_count, op_count = write_type_registry(
        os.path.join(root, 'src', 'type', 'type_registry_virtools_data.inc'), pt, ops)

    print(f'Output:')
    print(f'  src/app/bb_registry_builtin.inc: {bb_count} BBs')
    print(f'  src/type/type_registry_virtools_data.inc: {pt_count} param types + {op_count} operations')
    return 0


if __name__ == '__main__':
    sys.exit(main())
