/* Auto-generated by tools/scripts/gen_lua_pushers.py; do not edit by hand. */

#include "lua_pushers_generated.h"

#include "lua_bindings_internal.h"

#include "behavior/nmo_behavior_query.h"
#include "behavior/nmo_behavior_view.h"
#include "document/nmo_document_stats.h"
#include "format/nmo_interface_view.h"

void nmo_lua_push_interface_body_view(lua_State *state, const nmo_interface_body_view_t *value)
{
    lua_createtable(state, 0, 17);
    nmo_lua_set_boolean_field(state, "has_body", value->has_body);
    nmo_lua_set_integer_field(state, "link_count", (lua_Integer)value->link_count);
    nmo_lua_set_integer_field(state, "operation_count", (lua_Integer)value->operation_count);
    nmo_lua_set_integer_field(state, "comment_count", (lua_Integer)value->comment_count);
    nmo_lua_set_integer_field(state, "local_param_count", (lua_Integer)value->local_param_count);
    nmo_lua_set_integer_field(state, "shared_param_count", (lua_Integer)value->shared_param_count);
    nmo_lua_set_boolean_field(state, "has_params", value->has_params);
    nmo_lua_set_boolean_field(state, "has_graph_io", value->has_graph_io);
    nmo_lua_set_boolean_field(state, "has_links_section", value->has_links_section);
    nmo_lua_set_boolean_field(state, "has_operations_section", value->has_operations_section);
    nmo_lua_set_boolean_field(state, "has_comments_section", value->has_comments_section);
    nmo_lua_set_boolean_field(state, "has_unknown_flag_section", value->has_unknown_flag_section);
    nmo_lua_set_integer_field(state, "unknown_flag", (lua_Integer)value->unknown_flag);
    nmo_lua_set_integer_field(state, "inward_input_count", (lua_Integer)value->inward_input_count);
    nmo_lua_set_integer_field(state, "outward_input_count", (lua_Integer)value->outward_input_count);
    nmo_lua_set_integer_field(state, "inward_output_count", (lua_Integer)value->inward_output_count);
    nmo_lua_set_integer_field(state, "outward_output_count", (lua_Integer)value->outward_output_count);
}

void nmo_lua_push_interface_view(lua_State *state, const nmo_interface_view_t *value)
{
    lua_createtable(state, 0, 12);
    nmo_lua_set_integer_field(state, "owner_behavior_id", (lua_Integer)value->owner_behavior_id);
    nmo_lua_set_integer_field(state, "behavior_id", (lua_Integer)value->behavior_id);
    nmo_lua_set_boolean_field(state, "is_root", value->is_root);
    nmo_lua_set_integer_field(state, "version", (lua_Integer)value->version);
    nmo_lua_set_integer_field(state, "format_flags", (lua_Integer)value->format_flags);
    nmo_lua_set_integer_field(state, "flags", (lua_Integer)value->flags);
    nmo_lua_set_integer_field(state, "depth", (lua_Integer)value->depth);
    nmo_lua_set_integer_field(state, "sub_behavior_count", (lua_Integer)value->sub_behavior_count);
    nmo_lua_set_boolean_field(state, "extra_present", value->extra_present);
    nmo_lua_set_integer_field(state, "extra_entry_count", (lua_Integer)value->extra_entry_count);
    nmo_lua_set_boolean_field(state, "has_snapshot", value->has_snapshot);
    nmo_lua_push_interface_body_view(state, &value->body);
    lua_setfield(state, -2, "body");
}

void nmo_lua_push_behavior_script_view(lua_State *state, const nmo_behavior_script_view_t *value)
{
    lua_createtable(state, 0, 5);
    nmo_lua_set_integer_field(state, "script_id", (lua_Integer)value->script_id);
    nmo_lua_set_integer_field(state, "owner_id", (lua_Integer)value->owner_id);
    nmo_lua_set_optional_string_field(state, "script_name", value->script_name);
    nmo_lua_set_optional_string_field(state, "owner_name", value->owner_name);
    nmo_lua_set_integer_field(state, "owner_class_id", (lua_Integer)value->owner_class_id);
}

void nmo_lua_push_behavior_view(lua_State *state, const nmo_behavior_view_t *value)
{
    lua_createtable(state, 0, 22);
    nmo_lua_set_integer_field(state, "behavior_id", (lua_Integer)value->behavior_id);
    nmo_lua_set_integer_field(state, "class_id", (lua_Integer)value->class_id);
    nmo_lua_set_optional_string_field(state, "name", value->name);
    nmo_lua_set_integer_field(state, "flags", (lua_Integer)value->flags);
    nmo_lua_set_boolean_field(state, "is_building_block", value->is_building_block);
    nmo_lua_set_boolean_field(state, "has_target_parameter", value->has_target_parameter);
    nmo_lua_set_integer_field(state, "target_parameter_id", (lua_Integer)value->target_parameter_id);
    nmo_lua_set_integer_field(state, "sub_behavior_count", (lua_Integer)value->sub_behavior_count);
    nmo_lua_set_integer_field(state, "link_count", (lua_Integer)value->link_count);
    nmo_lua_set_integer_field(state, "operation_count", (lua_Integer)value->operation_count);
    nmo_lua_set_integer_field(state, "input_count", (lua_Integer)value->input_count);
    nmo_lua_set_integer_field(state, "output_count", (lua_Integer)value->output_count);
    nmo_lua_set_integer_field(state, "in_parameter_count", (lua_Integer)value->in_parameter_count);
    nmo_lua_set_integer_field(state, "out_parameter_count", (lua_Integer)value->out_parameter_count);
    nmo_lua_set_integer_field(state, "local_parameter_count", (lua_Integer)value->local_parameter_count);
    nmo_lua_set_boolean_field(state, "owner_index_available", value->owner_index_available);
    nmo_lua_set_boolean_field(state, "edit_ready", value->edit_ready);
    nmo_lua_set_integer_field(state, "edit_graph_status", (lua_Integer)value->edit_graph_status);
    nmo_lua_set_boolean_field(state, "has_interface", value->has_interface);
    nmo_lua_set_boolean_field(state, "interface_available", value->interface_available);
    nmo_lua_set_integer_field(state, "interface_status", (lua_Integer)value->interface_status);
    if (value->interface_available) {
        nmo_lua_push_interface_view(state, &value->interface_view);
        lua_setfield(state, -2, "interface");
    }
}

void nmo_lua_push_behavior_boundary_view(lua_State *state, const nmo_behavior_boundary_view_t *value)
{
    lua_createtable(state, 0, 8);
    nmo_lua_set_integer_field(state, "behavior_id", (lua_Integer)value->behavior_id);
    nmo_lua_set_integer_field(state, "internal_node_count", (lua_Integer)value->internal_node_count);
    nmo_lua_set_integer_field(state, "control_in_count", (lua_Integer)value->control_in_count);
    nmo_lua_set_integer_field(state, "control_out_count", (lua_Integer)value->control_out_count);
    nmo_lua_set_integer_field(state, "parameter_in_count", (lua_Integer)value->parameter_in_count);
    nmo_lua_set_integer_field(state, "parameter_out_count", (lua_Integer)value->parameter_out_count);
    nmo_lua_set_integer_field(state, "broken_links", (lua_Integer)value->broken_links);
    nmo_lua_set_integer_field(state, "missing_nodes", (lua_Integer)value->missing_nodes);
}

void nmo_lua_push_file_stats(lua_State *state, const nmo_file_stats_t *value)
{
    lua_createtable(state, 0, 5);
    lua_createtable(state, 0, 3);
    nmo_lua_set_integer_field(state, "total_count", (lua_Integer)value->objects.total_count);
    nmo_lua_set_integer_field(state, "max_class_id", (lua_Integer)value->objects.max_class_id);
    nmo_lua_set_integer_field(state, "unique_classes", (lua_Integer)value->objects.unique_classes);
    lua_setfield(state, -2, "objects");
    lua_createtable(state, 0, 6);
    nmo_lua_set_integer_field(state, "total_size", (lua_Integer)value->memory.total_size);
    nmo_lua_set_integer_field(state, "header_size", (lua_Integer)value->memory.header_size);
    nmo_lua_set_integer_field(state, "data_size", (lua_Integer)value->memory.data_size);
    nmo_lua_set_integer_field(state, "chunk_data_size", (lua_Integer)value->memory.chunk_data_size);
    nmo_lua_set_integer_field(state, "chunk_overhead", (lua_Integer)value->memory.chunk_overhead);
    nmo_lua_set_integer_field(state, "compression_ratio", (lua_Integer)value->memory.compression_ratio);
    lua_setfield(state, -2, "memory");
    lua_createtable(state, 0, 3);
    nmo_lua_set_number_field(state, "load_time_ms", (lua_Number)value->performance.load_time_ms);
    nmo_lua_set_number_field(state, "parse_time_ms", (lua_Number)value->performance.parse_time_ms);
    nmo_lua_set_number_field(state, "remap_time_ms", (lua_Number)value->performance.remap_time_ms);
    lua_setfield(state, -2, "performance");
    lua_createtable(state, 0, 3);
    nmo_lua_set_integer_field(state, "total_references", (lua_Integer)value->references.total_references);
    nmo_lua_set_integer_field(state, "resolved", (lua_Integer)value->references.resolved);
    nmo_lua_set_integer_field(state, "unresolved", (lua_Integer)value->references.unresolved);
    lua_setfield(state, -2, "references");
    lua_createtable(state, 0, 4);
    nmo_lua_set_integer_field(state, "total_chunks", (lua_Integer)value->chunks.total_chunks);
    nmo_lua_set_integer_field(state, "compressed_chunks", (lua_Integer)value->chunks.compressed_chunks);
    nmo_lua_set_integer_field(state, "max_chunk_size", (lua_Integer)value->chunks.max_chunk_size);
    nmo_lua_set_integer_field(state, "avg_chunk_size", (lua_Integer)value->chunks.avg_chunk_size);
    lua_setfield(state, -2, "chunks");
}
