/* Auto-generated by tools/scripts/gen_lua_pushers.py; do not edit by hand. */
#ifndef NMO_LUA_PUSHERS_GENERATED_H
#define NMO_LUA_PUSHERS_GENERATED_H

#include "lua.h"

#include "behavior/nmo_behavior_query.h"
#include "behavior/nmo_behavior_view.h"
#include "document/nmo_document_stats.h"
#include "format/nmo_interface_view.h"

void nmo_lua_push_interface_body_view(lua_State *state, const nmo_interface_body_view_t *value);
void nmo_lua_push_interface_view(lua_State *state, const nmo_interface_view_t *value);
void nmo_lua_push_behavior_script_view(lua_State *state, const nmo_behavior_script_view_t *value);
void nmo_lua_push_behavior_view(lua_State *state, const nmo_behavior_view_t *value);
void nmo_lua_push_behavior_boundary_view(lua_State *state, const nmo_behavior_boundary_view_t *value);
void nmo_lua_push_file_stats(lua_State *state, const nmo_file_stats_t *value);

#endif /* NMO_LUA_PUSHERS_GENERATED_H */
