/**
 * @file builtin_type_values.c
 * @brief Builtin type value behavior and vtables
 */

#include "type/nmo_type_system.h"
#include "type_value_internal.h"
#include "core/nmo_array.h"
#include "core/nmo_error.h"
#include "core/nmo_hash.h"
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include <string.h>
#include <stdio.h>


/* ============================================================================
 * Builtin Type VTables
 * ============================================================================ */

/* Helpers implemented in type_string_converters.c */
nmo_status_t nmo_builtin_create_zero(void *instance, const nmo_type_descriptor_t *type, void *context);
void nmo_builtin_destroy_noop(void *instance, const nmo_type_descriptor_t *type, void *context);
nmo_status_t nmo_builtin_copy_memcpy(
    const void *src,
    void *dst,
    const nmo_type_descriptor_t *type,
    nmo_arena_t *arena);
nmo_status_t nmo_builtin_copy_string(
    const void *src,
    void *dst,
    const nmo_type_descriptor_t *type,
    nmo_arena_t *arena);

bool nmo_equals_float_bits(const void *a, const void *b);
uint32_t nmo_hash_float_bits(const void *instance);
bool nmo_equals_double_bits(const void *a, const void *b);
uint32_t nmo_hash_double_bits(const void *instance);

bool nmo_equals_string_value(const void *a, const void *b);
uint32_t nmo_hash_string_value(const void *instance);

bool nmo_vt_equals_int32(const void *a, const void *b);
uint32_t nmo_vt_hash_int32(const void *instance);
bool nmo_vt_equals_uint32(const void *a, const void *b);
uint32_t nmo_vt_hash_uint32(const void *instance);
bool nmo_vt_equals_int8(const void *a, const void *b);
uint32_t nmo_vt_hash_int8(const void *instance);
bool nmo_vt_equals_uint8(const void *a, const void *b);
uint32_t nmo_vt_hash_uint8(const void *instance);
bool nmo_vt_equals_int16(const void *a, const void *b);
uint32_t nmo_vt_hash_int16(const void *instance);
bool nmo_vt_equals_uint16(const void *a, const void *b);
uint32_t nmo_vt_hash_uint16(const void *instance);
bool nmo_vt_equals_int64(const void *a, const void *b);
uint32_t nmo_vt_hash_int64(const void *instance);
bool nmo_vt_equals_uint64(const void *a, const void *b);
uint32_t nmo_vt_hash_uint64(const void *instance);

bool nmo_equals_bool(const void *a, const void *b);
uint32_t nmo_hash_bool(const void *instance);
bool nmo_equals_bool32(const void *a, const void *b);
uint32_t nmo_hash_bool32(const void *instance);
bool nmo_equals_pointer(const void *a, const void *b);
uint32_t nmo_hash_pointer(const void *instance);
bool nmo_equals_guid(const void *a, const void *b);
uint32_t nmo_hash_guid(const void *instance);
bool nmo_equals_object_id(const void *a, const void *b);
uint32_t nmo_hash_object_id(const void *instance);

bool nmo_equals_bytes_vector2(const void *a, const void *b);
uint32_t nmo_hash_bytes_vector2(const void *instance);
bool nmo_equals_bytes_vector3(const void *a, const void *b);
uint32_t nmo_hash_bytes_vector3(const void *instance);
bool nmo_equals_bytes_vector4(const void *a, const void *b);
uint32_t nmo_hash_bytes_vector4(const void *instance);
bool nmo_equals_bytes_quaternion(const void *a, const void *b);
uint32_t nmo_hash_bytes_quaternion(const void *instance);
bool nmo_equals_bytes_matrix(const void *a, const void *b);
uint32_t nmo_hash_bytes_matrix(const void *instance);
bool nmo_equals_bytes_color(const void *a, const void *b);
uint32_t nmo_hash_bytes_color(const void *instance);
bool nmo_equals_bytes_rect(const void *a, const void *b);
uint32_t nmo_hash_bytes_rect(const void *instance);
bool nmo_equals_bytes_eulerangles(const void *a, const void *b);
uint32_t nmo_hash_bytes_eulerangles(const void *instance);
bool nmo_equals_bytes_box(const void *a, const void *b);
uint32_t nmo_hash_bytes_box(const void *instance);

/* Forward declarations for VT wrappers 鈥?generated by NMO_DEFINE_VT_TO_STRING/FROM_STRING macros */
#define NMO_DECL_VT_PAIR(name) \
    nmo_status_t nmo_vt_to_string_##name( \
        const void *value, const nmo_type_descriptor_t *type, \
        const nmo_type_registry_t *registry, \
        char *buffer, size_t buffer_size, int depth); \
    nmo_status_t nmo_vt_from_string_##name( \
        void *value, const nmo_type_descriptor_t *type, \
        const nmo_type_registry_t *registry, const char *string);

NMO_DECL_VT_PAIR(int32)
NMO_DECL_VT_PAIR(uint32)
NMO_DECL_VT_PAIR(int8)
NMO_DECL_VT_PAIR(uint8)
NMO_DECL_VT_PAIR(int16)
NMO_DECL_VT_PAIR(uint16)
NMO_DECL_VT_PAIR(int64)
NMO_DECL_VT_PAIR(uint64)
NMO_DECL_VT_PAIR(float)
NMO_DECL_VT_PAIR(double)
NMO_DECL_VT_PAIR(bool)
NMO_DECL_VT_PAIR(string)
NMO_DECL_VT_PAIR(pointer)
NMO_DECL_VT_PAIR(guid)
NMO_DECL_VT_PAIR(object_id)
NMO_DECL_VT_PAIR(vector2)
NMO_DECL_VT_PAIR(vector3)
NMO_DECL_VT_PAIR(vector4)
NMO_DECL_VT_PAIR(quaternion)
NMO_DECL_VT_PAIR(matrix)
NMO_DECL_VT_PAIR(color)
NMO_DECL_VT_PAIR(rect)
NMO_DECL_VT_PAIR(eulerangles)
NMO_DECL_VT_PAIR(box)

#undef NMO_DECL_VT_PAIR

/* Semantic vtable handlers (hand-written, not macro-generated) */
nmo_status_t nmo_vt_to_string_angle(
    const void *value, const nmo_type_descriptor_t *type,
    const nmo_type_registry_t *registry,
    char *buffer, size_t buffer_size, int depth);
nmo_status_t nmo_vt_to_string_percentage(
    const void *value, const nmo_type_descriptor_t *type,
    const nmo_type_registry_t *registry,
    char *buffer, size_t buffer_size, int depth);
nmo_status_t nmo_vt_from_string_percentage(
    void *value, const nmo_type_descriptor_t *type,
    const nmo_type_registry_t *registry,
    const char *string);
nmo_status_t nmo_vt_to_string_bool32(
    const void *value, const nmo_type_descriptor_t *type,
    const nmo_type_registry_t *registry,
    char *buffer, size_t buffer_size, int depth);
nmo_status_t nmo_vt_from_string_bool32(
    void *value, const nmo_type_descriptor_t *type,
    const nmo_type_registry_t *registry,
    const char *string);
nmo_status_t nmo_vt_to_string_time(
    const void *value, const nmo_type_descriptor_t *type,
    const nmo_type_registry_t *registry,
    char *buffer, size_t buffer_size, int depth);
nmo_status_t nmo_vt_to_string_classid(
    const void *value, const nmo_type_descriptor_t *type,
    const nmo_type_registry_t *registry,
    char *buffer, size_t buffer_size, int depth);
nmo_status_t nmo_vt_to_string_none(
    const void *value, const nmo_type_descriptor_t *type,
    const nmo_type_registry_t *registry,
    char *buffer, size_t buffer_size, int depth);
nmo_status_t nmo_vt_from_string_none(
    void *value, const nmo_type_descriptor_t *type,
    const nmo_type_registry_t *registry, const char *string);
nmo_status_t nmo_vt_to_string_voidbuf(
    const void *value, const nmo_type_descriptor_t *type,
    const nmo_type_registry_t *registry,
    char *buffer, size_t buffer_size, int depth);
nmo_status_t nmo_vt_from_string_voidbuf(
    void *value, const nmo_type_descriptor_t *type,
    const nmo_type_registry_t *registry, const char *string);

const nmo_type_vtable_t nmo_builtin_vtable_int = {
    .create = nmo_builtin_create_zero,
    .destroy = nmo_builtin_destroy_noop,
    .copy = nmo_builtin_copy_memcpy,
    .equals = nmo_vt_equals_int32,
    .hash = nmo_vt_hash_int32,
    .to_string = nmo_vt_to_string_int32,
    .from_string = nmo_vt_from_string_int32,
};

const nmo_type_vtable_t nmo_builtin_vtable_float = {
    .create = nmo_builtin_create_zero,
    .destroy = nmo_builtin_destroy_noop,
    .copy = nmo_builtin_copy_memcpy,
    .equals = nmo_equals_float_bits,
    .hash = nmo_hash_float_bits,
    .to_string = nmo_vt_to_string_float,
    .from_string = nmo_vt_from_string_float,
};

const nmo_type_vtable_t nmo_builtin_vtable_angle = {
    .create = nmo_builtin_create_zero,
    .destroy = nmo_builtin_destroy_noop,
    .copy = nmo_builtin_copy_memcpy,
    .equals = nmo_equals_float_bits,
    .hash = nmo_hash_float_bits,
    .to_string = nmo_vt_to_string_angle,
    .from_string = nmo_vt_from_string_float,
};

const nmo_type_vtable_t nmo_builtin_vtable_percentage = {
    .create = nmo_builtin_create_zero,
    .destroy = nmo_builtin_destroy_noop,
    .copy = nmo_builtin_copy_memcpy,
    .equals = nmo_equals_float_bits,
    .hash = nmo_hash_float_bits,
    .to_string = nmo_vt_to_string_percentage,
    .from_string = nmo_vt_from_string_percentage,
};

const nmo_type_vtable_t nmo_builtin_vtable_bool = {
    .create = nmo_builtin_create_zero,
    .destroy = nmo_builtin_destroy_noop,
    .copy = nmo_builtin_copy_memcpy,
    .equals = nmo_equals_bool32,
    .hash = nmo_hash_bool32,
    .to_string = nmo_vt_to_string_bool32,
    .from_string = nmo_vt_from_string_bool32,
};

const nmo_type_vtable_t nmo_builtin_vtable_double = {
    .create = nmo_builtin_create_zero,
    .destroy = nmo_builtin_destroy_noop,
    .copy = nmo_builtin_copy_memcpy,
    .equals = nmo_equals_double_bits,
    .hash = nmo_hash_double_bits,
    .to_string = nmo_vt_to_string_double,
    .from_string = nmo_vt_from_string_double,
};

const nmo_type_vtable_t nmo_builtin_vtable_int8 = {
    .create = nmo_builtin_create_zero,
    .destroy = nmo_builtin_destroy_noop,
    .copy = nmo_builtin_copy_memcpy,
    .equals = nmo_vt_equals_int8,
    .hash = nmo_vt_hash_int8,
    .to_string = nmo_vt_to_string_int8,
    .from_string = nmo_vt_from_string_int8,
};

const nmo_type_vtable_t nmo_builtin_vtable_uint8 = {
    .create = nmo_builtin_create_zero,
    .destroy = nmo_builtin_destroy_noop,
    .copy = nmo_builtin_copy_memcpy,
    .equals = nmo_vt_equals_uint8,
    .hash = nmo_vt_hash_uint8,
    .to_string = nmo_vt_to_string_uint8,
    .from_string = nmo_vt_from_string_uint8,
};

const nmo_type_vtable_t nmo_builtin_vtable_int16 = {
    .create = nmo_builtin_create_zero,
    .destroy = nmo_builtin_destroy_noop,
    .copy = nmo_builtin_copy_memcpy,
    .equals = nmo_vt_equals_int16,
    .hash = nmo_vt_hash_int16,
    .to_string = nmo_vt_to_string_int16,
    .from_string = nmo_vt_from_string_int16,
};

const nmo_type_vtable_t nmo_builtin_vtable_uint16 = {
    .create = nmo_builtin_create_zero,
    .destroy = nmo_builtin_destroy_noop,
    .copy = nmo_builtin_copy_memcpy,
    .equals = nmo_vt_equals_uint16,
    .hash = nmo_vt_hash_uint16,
    .to_string = nmo_vt_to_string_uint16,
    .from_string = nmo_vt_from_string_uint16,
};

const nmo_type_vtable_t nmo_builtin_vtable_uint32 = {
    .create = nmo_builtin_create_zero,
    .destroy = nmo_builtin_destroy_noop,
    .copy = nmo_builtin_copy_memcpy,
    .equals = nmo_vt_equals_uint32,
    .hash = nmo_vt_hash_uint32,
    .to_string = nmo_vt_to_string_uint32,
    .from_string = nmo_vt_from_string_uint32,
};

const nmo_type_vtable_t nmo_builtin_vtable_classid = {
    .create = nmo_builtin_create_zero,
    .destroy = nmo_builtin_destroy_noop,
    .copy = nmo_builtin_copy_memcpy,
    .equals = nmo_vt_equals_uint32,
    .hash = nmo_vt_hash_uint32,
    .to_string = nmo_vt_to_string_classid,
    .from_string = nmo_vt_from_string_uint32,
};

const nmo_type_vtable_t nmo_builtin_vtable_int64 = {
    .create = nmo_builtin_create_zero,
    .destroy = nmo_builtin_destroy_noop,
    .copy = nmo_builtin_copy_memcpy,
    .equals = nmo_vt_equals_int64,
    .hash = nmo_vt_hash_int64,
    .to_string = nmo_vt_to_string_int64,
    .from_string = nmo_vt_from_string_int64,
};

const nmo_type_vtable_t nmo_builtin_vtable_uint64 = {
    .create = nmo_builtin_create_zero,
    .destroy = nmo_builtin_destroy_noop,
    .copy = nmo_builtin_copy_memcpy,
    .equals = nmo_vt_equals_uint64,
    .hash = nmo_vt_hash_uint64,
    .to_string = nmo_vt_to_string_uint64,
    .from_string = nmo_vt_from_string_uint64,
};

const nmo_type_vtable_t nmo_builtin_vtable_string = {
    .create = nmo_builtin_create_zero,
    .destroy = nmo_builtin_destroy_noop,
    .copy = nmo_builtin_copy_string,
    .equals = nmo_equals_string_value,
    .hash = nmo_hash_string_value,
    .to_string = nmo_vt_to_string_string,
    .from_string = nmo_vt_from_string_string,
};

const nmo_type_vtable_t nmo_builtin_vtable_pointer = {
    .create = nmo_builtin_create_zero,
    .destroy = nmo_builtin_destroy_noop,
    .copy = nmo_builtin_copy_memcpy,
    .equals = nmo_equals_pointer,
    .hash = nmo_hash_pointer,
    .to_string = nmo_vt_to_string_pointer,
    .from_string = nmo_vt_from_string_pointer,
};

const nmo_type_vtable_t nmo_builtin_vtable_chunk = {
    .create = nmo_builtin_create_zero,
    .destroy = nmo_builtin_destroy_noop,
    .copy = nmo_builtin_copy_memcpy,
    .equals = nmo_equals_pointer,
    .hash = nmo_hash_pointer,
    .to_string = nmo_vt_to_string_pointer,
    .from_string = nmo_vt_from_string_pointer,
};

const nmo_type_vtable_t nmo_builtin_vtable_guid = {
    .create = nmo_builtin_create_zero,
    .destroy = nmo_builtin_destroy_noop,
    .copy = nmo_builtin_copy_memcpy,
    .equals = nmo_equals_guid,
    .hash = nmo_hash_guid,
    .to_string = nmo_vt_to_string_guid,
    .from_string = nmo_vt_from_string_guid,
};

const nmo_type_vtable_t nmo_builtin_vtable_object_id = {
    .create = nmo_builtin_create_zero,
    .destroy = nmo_builtin_destroy_noop,
    .copy = nmo_builtin_copy_memcpy,
    .equals = nmo_equals_object_id,
    .hash = nmo_hash_object_id,
    .to_string = nmo_vt_to_string_object_id,
    .from_string = nmo_vt_from_string_object_id,
};

const nmo_type_vtable_t nmo_builtin_vtable_vector2 = {
    .create = nmo_builtin_create_zero,
    .destroy = nmo_builtin_destroy_noop,
    .copy = nmo_builtin_copy_memcpy,
    .equals = nmo_equals_bytes_vector2,
    .hash = nmo_hash_bytes_vector2,
    .to_string = nmo_vt_to_string_vector2,
    .from_string = nmo_vt_from_string_vector2,
};

const nmo_type_vtable_t nmo_builtin_vtable_vector3 = {
    .create = nmo_builtin_create_zero,
    .destroy = nmo_builtin_destroy_noop,
    .copy = nmo_builtin_copy_memcpy,
    .equals = nmo_equals_bytes_vector3,
    .hash = nmo_hash_bytes_vector3,
    .to_string = nmo_vt_to_string_vector3,
    .from_string = nmo_vt_from_string_vector3,
};

const nmo_type_vtable_t nmo_builtin_vtable_vector4 = {
    .create = nmo_builtin_create_zero,
    .destroy = nmo_builtin_destroy_noop,
    .copy = nmo_builtin_copy_memcpy,
    .equals = nmo_equals_bytes_vector4,
    .hash = nmo_hash_bytes_vector4,
    .to_string = nmo_vt_to_string_vector4,
    .from_string = nmo_vt_from_string_vector4,
};

const nmo_type_vtable_t nmo_builtin_vtable_quaternion = {
    .create = nmo_builtin_create_zero,
    .destroy = nmo_builtin_destroy_noop,
    .copy = nmo_builtin_copy_memcpy,
    .equals = nmo_equals_bytes_quaternion,
    .hash = nmo_hash_bytes_quaternion,
    .to_string = nmo_vt_to_string_quaternion,
    .from_string = nmo_vt_from_string_quaternion,
};

const nmo_type_vtable_t nmo_builtin_vtable_matrix = {
    .create = nmo_builtin_create_zero,
    .destroy = nmo_builtin_destroy_noop,
    .copy = nmo_builtin_copy_memcpy,
    .equals = nmo_equals_bytes_matrix,
    .hash = nmo_hash_bytes_matrix,
    .to_string = nmo_vt_to_string_matrix,
    .from_string = nmo_vt_from_string_matrix,
};

const nmo_type_vtable_t nmo_builtin_vtable_color = {
    .create = nmo_builtin_create_zero,
    .destroy = nmo_builtin_destroy_noop,
    .copy = nmo_builtin_copy_memcpy,
    .equals = nmo_equals_bytes_color,
    .hash = nmo_hash_bytes_color,
    .to_string = nmo_vt_to_string_color,
    .from_string = nmo_vt_from_string_color,
};

const nmo_type_vtable_t nmo_builtin_vtable_rect = {
    .create = nmo_builtin_create_zero,
    .destroy = nmo_builtin_destroy_noop,
    .copy = nmo_builtin_copy_memcpy,
    .equals = nmo_equals_bytes_rect,
    .hash = nmo_hash_bytes_rect,
    .to_string = nmo_vt_to_string_rect,
    .from_string = nmo_vt_from_string_rect,
};

const nmo_type_vtable_t nmo_builtin_vtable_eulerangles = {
    .create = nmo_builtin_create_zero,
    .destroy = nmo_builtin_destroy_noop,
    .copy = nmo_builtin_copy_memcpy,
    .equals = nmo_equals_bytes_eulerangles,
    .hash = nmo_hash_bytes_eulerangles,
    .to_string = nmo_vt_to_string_eulerangles,
    .from_string = nmo_vt_from_string_eulerangles,
};

const nmo_type_vtable_t nmo_builtin_vtable_box = {
    .create = nmo_builtin_create_zero,
    .destroy = nmo_builtin_destroy_noop,
    .copy = nmo_builtin_copy_memcpy,
    .equals = nmo_equals_bytes_box,
    .hash = nmo_hash_bytes_box,
    .to_string = nmo_vt_to_string_box,
    .from_string = nmo_vt_from_string_box,
};

const nmo_type_vtable_t nmo_builtin_vtable_time = {
    .create = nmo_builtin_create_zero,
    .destroy = nmo_builtin_destroy_noop,
    .copy = nmo_builtin_copy_memcpy,
    .equals = nmo_equals_float_bits,
    .hash = nmo_hash_float_bits,
    .to_string = nmo_vt_to_string_time,
    .from_string = nmo_vt_from_string_float,
};

const nmo_type_vtable_t nmo_builtin_vtable_none = {
    .to_string = nmo_vt_to_string_none,
    .from_string = nmo_vt_from_string_none,
};

const nmo_type_vtable_t nmo_builtin_vtable_voidbuf = {
    .to_string = nmo_vt_to_string_voidbuf,
    .from_string = nmo_vt_from_string_voidbuf,
};

static nmo_status_t nmo_builtin_create_array(void *instance, const nmo_type_descriptor_t *type, void *context) {
    (void)type;
    (void)context;

    if (instance == NULL) {
        NMO_RETURN_ERROR(NMO_ERR_INVALID_ARGUMENT, NMO_SEVERITY_ERROR, "array create: NULL instance");
    }

    nmo_array_t *arr = (nmo_array_t *)instance;
    return nmo_array_init(arr, 1, 0, NULL);
}

static void nmo_builtin_destroy_array(void *instance, const nmo_type_descriptor_t *type, void *context) {
    (void)type;
    (void)context;

    if (instance == NULL) {
        return;
    }

    nmo_array_dispose((nmo_array_t *)instance);
}

static nmo_status_t nmo_builtin_copy_array(
    const void *src,
    void *dst,
    const nmo_type_descriptor_t *type,
    nmo_arena_t *arena
) {
    (void)type;
    (void)arena;

    if (src == NULL || dst == NULL) {
        NMO_RETURN_ERROR(NMO_ERR_INVALID_ARGUMENT, NMO_SEVERITY_ERROR, "array copy: NULL argument");
    }

    const nmo_array_t *src_arr = (const nmo_array_t *)src;
    nmo_array_t *dst_arr = (nmo_array_t *)dst;

    /* Ensure destination starts empty to avoid leaking pre-existing backing store. */
    memset(dst_arr, 0, sizeof(*dst_arr));

    if (src_arr->element_size == 0) {
        /* Treat as empty byte array for resilience. */
        return nmo_array_init(dst_arr, 1, 0, NULL);
    }

    return nmo_array_clone(src_arr, dst_arr, &src_arr->allocator);
}

static bool nmo_builtin_equals_array(const void *a, const void *b) {
    if (a == b) {
        return true;
    }
    if (a == NULL || b == NULL) {
        return false;
    }

    const nmo_array_t *aa = (const nmo_array_t *)a;
    const nmo_array_t *bb = (const nmo_array_t *)b;

    if (aa->element_size != bb->element_size || aa->count != bb->count) {
        return false;
    }
    if (aa->count == 0) {
        return true;
    }
    if (aa->data == NULL || bb->data == NULL) {
        return false;
    }

    size_t byte_len = aa->count * aa->element_size;
    return memcmp(aa->data, bb->data, byte_len) == 0;
}

static uint32_t nmo_builtin_hash_array(const void *instance) {
    if (instance == NULL) {
        return 0;
    }

    const nmo_array_t *arr = (const nmo_array_t *)instance;
    const uint32_t seed = nmo_hash_int32((uint32_t)arr->element_size) ^ nmo_hash_int32((uint32_t)arr->count);

    if (arr->count == 0 || arr->data == NULL || arr->element_size == 0) {
        return seed;
    }

    size_t byte_len = arr->count * arr->element_size;
    return nmo_murmur3_32(arr->data, byte_len, seed);
}

static nmo_status_t nmo_builtin_to_string_array(
    const void *value,
    const nmo_type_descriptor_t *type,
    const nmo_type_registry_t *registry,
    char *buffer,
    size_t buffer_size,
    int depth
) {
    (void)type;
    (void)registry;
    (void)depth;

    if (buffer == NULL || buffer_size == 0) {
        NMO_RETURN_ERROR(NMO_ERR_INVALID_ARGUMENT, NMO_SEVERITY_ERROR, "array to_string: invalid buffer");
    }

    if (value == NULL) {
        int written = snprintf(buffer, buffer_size, "null");
        if (written < 0 || (size_t)written >= buffer_size) {
            NMO_RETURN_ERROR(NMO_ERR_BUFFER_OVERRUN, NMO_SEVERITY_ERROR, "array to_string: buffer too small");
        }
        NMO_RETURN_OK();
    }

    const nmo_array_t *arr = (const nmo_array_t *)value;
    int written = snprintf(buffer, buffer_size, "array(count=%zu, element_size=%zu)", arr->count, arr->element_size);
    if (written < 0 || (size_t)written >= buffer_size) {
        NMO_RETURN_ERROR(NMO_ERR_BUFFER_OVERRUN, NMO_SEVERITY_ERROR, "array to_string: buffer too small");
    }

    NMO_RETURN_OK();
}

static nmo_status_t nmo_builtin_from_string_array(
    void *value,
    const nmo_type_descriptor_t *type,
    const nmo_type_registry_t *registry,
    const char *string
) {
    (void)type;
    (void)registry;

    if (value == NULL || string == NULL) {
        NMO_RETURN_ERROR(NMO_ERR_INVALID_ARGUMENT, NMO_SEVERITY_ERROR, "array from_string: NULL argument");
    }

    /* Minimal parser: accept "[]" as an empty byte array. */
    if (strcmp(string, "[]") != 0) {
        NMO_RETURN_ERROR(NMO_ERR_INVALID_ARGUMENT, NMO_SEVERITY_ERROR, "array from_string: expected []");
    }

    nmo_array_t *arr = (nmo_array_t *)value;
    nmo_array_dispose(arr);
    return nmo_array_init(arr, 1, 0, NULL);
}

const nmo_type_vtable_t nmo_builtin_vtable_array = {
    .create = nmo_builtin_create_array,
    .destroy = nmo_builtin_destroy_array,
    .copy = nmo_builtin_copy_array,
    .equals = nmo_builtin_equals_array,
    .hash = nmo_builtin_hash_array,
    .to_string = nmo_builtin_to_string_array,
    .from_string = nmo_builtin_from_string_array,
};

