/**
 * @file builtin_type_values.c
 * @brief Builtin type value behavior and vtables
 */

#include "type/nmo_type_system.h"
#include "type/nmo_type_string.h"
#include "type/nmo_type_guids.h"
#include "type_value_internal.h"
#include "core/nmo_array.h"
#include "core/nmo_arena.h"
#include "core/nmo_color.h"
#include "core/nmo_error.h"
#include "core/nmo_hash.h"
#include "core/nmo_parse.h"
#include <ctype.h>
#include <math.h>
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>


/* ============================================================================
 * Builtin Type VTables
 * ============================================================================ */

/* Helpers implemented below. */
nmo_status_t nmo_builtin_create_zero(void *instance, const nmo_type_descriptor_t *type, void *context);
void nmo_builtin_destroy_noop(void *instance, const nmo_type_descriptor_t *type, void *context);
nmo_status_t nmo_builtin_copy_memcpy(
    const void *src,
    void *dst,
    const nmo_type_descriptor_t *type,
    nmo_arena_t *arena);
nmo_status_t nmo_builtin_copy_string(
    const void *src,
    void *dst,
    const nmo_type_descriptor_t *type,
    nmo_arena_t *arena);

bool nmo_equals_float_bits(const void *a, const void *b);
uint32_t nmo_hash_float_bits(const void *instance);
bool nmo_equals_double_bits(const void *a, const void *b);
uint32_t nmo_hash_double_bits(const void *instance);

bool nmo_equals_string_value(const void *a, const void *b);
uint32_t nmo_hash_string_value(const void *instance);

bool nmo_vt_equals_int32(const void *a, const void *b);
uint32_t nmo_vt_hash_int32(const void *instance);
bool nmo_vt_equals_uint32(const void *a, const void *b);
uint32_t nmo_vt_hash_uint32(const void *instance);
bool nmo_vt_equals_int8(const void *a, const void *b);
uint32_t nmo_vt_hash_int8(const void *instance);
bool nmo_vt_equals_uint8(const void *a, const void *b);
uint32_t nmo_vt_hash_uint8(const void *instance);
bool nmo_vt_equals_int16(const void *a, const void *b);
uint32_t nmo_vt_hash_int16(const void *instance);
bool nmo_vt_equals_uint16(const void *a, const void *b);
uint32_t nmo_vt_hash_uint16(const void *instance);
bool nmo_vt_equals_int64(const void *a, const void *b);
uint32_t nmo_vt_hash_int64(const void *instance);
bool nmo_vt_equals_uint64(const void *a, const void *b);
uint32_t nmo_vt_hash_uint64(const void *instance);

bool nmo_equals_bool(const void *a, const void *b);
uint32_t nmo_hash_bool(const void *instance);
bool nmo_equals_bool32(const void *a, const void *b);
uint32_t nmo_hash_bool32(const void *instance);
bool nmo_equals_pointer(const void *a, const void *b);
uint32_t nmo_hash_pointer(const void *instance);
bool nmo_equals_guid(const void *a, const void *b);
uint32_t nmo_hash_guid(const void *instance);
bool nmo_equals_object_id(const void *a, const void *b);
uint32_t nmo_hash_object_id(const void *instance);

bool nmo_equals_bytes_vector2(const void *a, const void *b);
uint32_t nmo_hash_bytes_vector2(const void *instance);
bool nmo_equals_bytes_vector3(const void *a, const void *b);
uint32_t nmo_hash_bytes_vector3(const void *instance);
bool nmo_equals_bytes_vector4(const void *a, const void *b);
uint32_t nmo_hash_bytes_vector4(const void *instance);
bool nmo_equals_bytes_quaternion(const void *a, const void *b);
uint32_t nmo_hash_bytes_quaternion(const void *instance);
bool nmo_equals_bytes_matrix(const void *a, const void *b);
uint32_t nmo_hash_bytes_matrix(const void *instance);
bool nmo_equals_bytes_color(const void *a, const void *b);
uint32_t nmo_hash_bytes_color(const void *instance);
bool nmo_equals_bytes_rect(const void *a, const void *b);
uint32_t nmo_hash_bytes_rect(const void *instance);
bool nmo_equals_bytes_eulerangles(const void *a, const void *b);
uint32_t nmo_hash_bytes_eulerangles(const void *instance);
bool nmo_equals_bytes_box(const void *a, const void *b);
uint32_t nmo_hash_bytes_box(const void *instance);

/* Forward declarations for VT wrappers 鈥?generated by NMO_DEFINE_VT_TO_STRING/FROM_STRING macros */
#define NMO_DECL_VT_PAIR(name) \
    nmo_status_t nmo_vt_to_string_##name( \
        const void *value, const nmo_type_descriptor_t *type, \
        const nmo_type_registry_t *registry, \
        char *buffer, size_t buffer_size, int depth); \
    nmo_status_t nmo_vt_from_string_##name( \
        void *value, const nmo_type_descriptor_t *type, \
        const nmo_type_registry_t *registry, const char *string);

NMO_DECL_VT_PAIR(int32)
NMO_DECL_VT_PAIR(uint32)
NMO_DECL_VT_PAIR(int8)
NMO_DECL_VT_PAIR(uint8)
NMO_DECL_VT_PAIR(int16)
NMO_DECL_VT_PAIR(uint16)
NMO_DECL_VT_PAIR(int64)
NMO_DECL_VT_PAIR(uint64)
NMO_DECL_VT_PAIR(float)
NMO_DECL_VT_PAIR(double)
NMO_DECL_VT_PAIR(bool)
NMO_DECL_VT_PAIR(string)
NMO_DECL_VT_PAIR(pointer)
NMO_DECL_VT_PAIR(guid)
NMO_DECL_VT_PAIR(object_id)
NMO_DECL_VT_PAIR(vector2)
NMO_DECL_VT_PAIR(vector3)
NMO_DECL_VT_PAIR(vector4)
NMO_DECL_VT_PAIR(quaternion)
NMO_DECL_VT_PAIR(matrix)
NMO_DECL_VT_PAIR(color)
NMO_DECL_VT_PAIR(rect)
NMO_DECL_VT_PAIR(eulerangles)
NMO_DECL_VT_PAIR(box)

#undef NMO_DECL_VT_PAIR

/* Semantic vtable handlers (hand-written, not macro-generated) */
nmo_status_t nmo_vt_to_string_angle(
    const void *value, const nmo_type_descriptor_t *type,
    const nmo_type_registry_t *registry,
    char *buffer, size_t buffer_size, int depth);
nmo_status_t nmo_vt_to_string_percentage(
    const void *value, const nmo_type_descriptor_t *type,
    const nmo_type_registry_t *registry,
    char *buffer, size_t buffer_size, int depth);
nmo_status_t nmo_vt_from_string_percentage(
    void *value, const nmo_type_descriptor_t *type,
    const nmo_type_registry_t *registry,
    const char *string);
nmo_status_t nmo_vt_to_string_bool32(
    const void *value, const nmo_type_descriptor_t *type,
    const nmo_type_registry_t *registry,
    char *buffer, size_t buffer_size, int depth);
nmo_status_t nmo_vt_from_string_bool32(
    void *value, const nmo_type_descriptor_t *type,
    const nmo_type_registry_t *registry,
    const char *string);
nmo_status_t nmo_vt_to_string_time(
    const void *value, const nmo_type_descriptor_t *type,
    const nmo_type_registry_t *registry,
    char *buffer, size_t buffer_size, int depth);
nmo_status_t nmo_vt_from_string_time(
    void *value, const nmo_type_descriptor_t *type,
    const nmo_type_registry_t *registry,
    const char *string);
nmo_status_t nmo_vt_to_string_classid(
    const void *value, const nmo_type_descriptor_t *type,
    const nmo_type_registry_t *registry,
    char *buffer, size_t buffer_size, int depth);
nmo_status_t nmo_vt_to_string_none(
    const void *value, const nmo_type_descriptor_t *type,
    const nmo_type_registry_t *registry,
    char *buffer, size_t buffer_size, int depth);
nmo_status_t nmo_vt_from_string_none(
    void *value, const nmo_type_descriptor_t *type,
    const nmo_type_registry_t *registry, const char *string);
nmo_status_t nmo_vt_to_string_voidbuf(
    const void *value, const nmo_type_descriptor_t *type,
    const nmo_type_registry_t *registry,
    char *buffer, size_t buffer_size, int depth);
nmo_status_t nmo_vt_from_string_voidbuf(
    void *value, const nmo_type_descriptor_t *type,
    const nmo_type_registry_t *registry, const char *string);

NMO_DEFINE_ZERO_MEMCPY_TYPE_VTABLE(
    nmo_builtin_vtable_int,
    nmo_vt_equals_int32, nmo_vt_hash_int32,
    nmo_vt_to_string_int32, nmo_vt_from_string_int32)
NMO_DEFINE_ZERO_MEMCPY_TYPE_VTABLE(
    nmo_builtin_vtable_float,
    nmo_equals_float_bits, nmo_hash_float_bits,
    nmo_vt_to_string_float, nmo_vt_from_string_float)
NMO_DEFINE_ZERO_MEMCPY_TYPE_VTABLE(
    nmo_builtin_vtable_angle,
    nmo_equals_float_bits, nmo_hash_float_bits,
    nmo_vt_to_string_angle, nmo_vt_from_string_float)
NMO_DEFINE_ZERO_MEMCPY_TYPE_VTABLE(
    nmo_builtin_vtable_percentage,
    nmo_equals_float_bits, nmo_hash_float_bits,
    nmo_vt_to_string_percentage, nmo_vt_from_string_percentage)
NMO_DEFINE_ZERO_MEMCPY_TYPE_VTABLE(
    nmo_builtin_vtable_bool,
    nmo_equals_bool32, nmo_hash_bool32,
    nmo_vt_to_string_bool32, nmo_vt_from_string_bool32)
NMO_DEFINE_ZERO_MEMCPY_TYPE_VTABLE(
    nmo_builtin_vtable_double,
    nmo_equals_double_bits, nmo_hash_double_bits,
    nmo_vt_to_string_double, nmo_vt_from_string_double)
NMO_DEFINE_ZERO_MEMCPY_TYPE_VTABLE(
    nmo_builtin_vtable_int8,
    nmo_vt_equals_int8, nmo_vt_hash_int8,
    nmo_vt_to_string_int8, nmo_vt_from_string_int8)
NMO_DEFINE_ZERO_MEMCPY_TYPE_VTABLE(
    nmo_builtin_vtable_uint8,
    nmo_vt_equals_uint8, nmo_vt_hash_uint8,
    nmo_vt_to_string_uint8, nmo_vt_from_string_uint8)
NMO_DEFINE_ZERO_MEMCPY_TYPE_VTABLE(
    nmo_builtin_vtable_int16,
    nmo_vt_equals_int16, nmo_vt_hash_int16,
    nmo_vt_to_string_int16, nmo_vt_from_string_int16)
NMO_DEFINE_ZERO_MEMCPY_TYPE_VTABLE(
    nmo_builtin_vtable_uint16,
    nmo_vt_equals_uint16, nmo_vt_hash_uint16,
    nmo_vt_to_string_uint16, nmo_vt_from_string_uint16)
NMO_DEFINE_ZERO_MEMCPY_TYPE_VTABLE(
    nmo_builtin_vtable_uint32,
    nmo_vt_equals_uint32, nmo_vt_hash_uint32,
    nmo_vt_to_string_uint32, nmo_vt_from_string_uint32)
NMO_DEFINE_ZERO_MEMCPY_TYPE_VTABLE(
    nmo_builtin_vtable_classid,
    nmo_vt_equals_uint32, nmo_vt_hash_uint32,
    nmo_vt_to_string_classid, nmo_vt_from_string_uint32)
NMO_DEFINE_ZERO_MEMCPY_TYPE_VTABLE(
    nmo_builtin_vtable_int64,
    nmo_vt_equals_int64, nmo_vt_hash_int64,
    nmo_vt_to_string_int64, nmo_vt_from_string_int64)
NMO_DEFINE_ZERO_MEMCPY_TYPE_VTABLE(
    nmo_builtin_vtable_uint64,
    nmo_vt_equals_uint64, nmo_vt_hash_uint64,
    nmo_vt_to_string_uint64, nmo_vt_from_string_uint64)
NMO_DEFINE_ZERO_COPY_TYPE_VTABLE(
    nmo_builtin_vtable_string,
    nmo_builtin_copy_string,
    nmo_equals_string_value, nmo_hash_string_value,
    nmo_vt_to_string_string, nmo_vt_from_string_string)
NMO_DEFINE_ZERO_MEMCPY_TYPE_VTABLE(
    nmo_builtin_vtable_pointer,
    nmo_equals_pointer, nmo_hash_pointer,
    nmo_vt_to_string_pointer, nmo_vt_from_string_pointer)
NMO_DEFINE_ZERO_MEMCPY_TYPE_VTABLE(
    nmo_builtin_vtable_chunk,
    nmo_equals_pointer, nmo_hash_pointer,
    nmo_vt_to_string_pointer, nmo_vt_from_string_pointer)
NMO_DEFINE_ZERO_MEMCPY_TYPE_VTABLE(
    nmo_builtin_vtable_guid,
    nmo_equals_guid, nmo_hash_guid,
    nmo_vt_to_string_guid, nmo_vt_from_string_guid)
NMO_DEFINE_ZERO_MEMCPY_TYPE_VTABLE(
    nmo_builtin_vtable_object_id,
    nmo_equals_object_id, nmo_hash_object_id,
    nmo_vt_to_string_object_id, nmo_vt_from_string_object_id)
NMO_DEFINE_ZERO_MEMCPY_TYPE_VTABLE(
    nmo_builtin_vtable_vector2,
    nmo_equals_bytes_vector2, nmo_hash_bytes_vector2,
    nmo_vt_to_string_vector2, nmo_vt_from_string_vector2)
NMO_DEFINE_ZERO_MEMCPY_TYPE_VTABLE(
    nmo_builtin_vtable_vector3,
    nmo_equals_bytes_vector3, nmo_hash_bytes_vector3,
    nmo_vt_to_string_vector3, nmo_vt_from_string_vector3)
NMO_DEFINE_ZERO_MEMCPY_TYPE_VTABLE(
    nmo_builtin_vtable_vector4,
    nmo_equals_bytes_vector4, nmo_hash_bytes_vector4,
    nmo_vt_to_string_vector4, nmo_vt_from_string_vector4)
NMO_DEFINE_ZERO_MEMCPY_TYPE_VTABLE(
    nmo_builtin_vtable_quaternion,
    nmo_equals_bytes_quaternion, nmo_hash_bytes_quaternion,
    nmo_vt_to_string_quaternion, nmo_vt_from_string_quaternion)
NMO_DEFINE_ZERO_MEMCPY_TYPE_VTABLE(
    nmo_builtin_vtable_matrix,
    nmo_equals_bytes_matrix, nmo_hash_bytes_matrix,
    nmo_vt_to_string_matrix, nmo_vt_from_string_matrix)
NMO_DEFINE_ZERO_MEMCPY_TYPE_VTABLE(
    nmo_builtin_vtable_color,
    nmo_equals_bytes_color, nmo_hash_bytes_color,
    nmo_vt_to_string_color, nmo_vt_from_string_color)
NMO_DEFINE_ZERO_MEMCPY_TYPE_VTABLE(
    nmo_builtin_vtable_rect,
    nmo_equals_bytes_rect, nmo_hash_bytes_rect,
    nmo_vt_to_string_rect, nmo_vt_from_string_rect)
NMO_DEFINE_ZERO_MEMCPY_TYPE_VTABLE(
    nmo_builtin_vtable_eulerangles,
    nmo_equals_bytes_eulerangles, nmo_hash_bytes_eulerangles,
    nmo_vt_to_string_eulerangles, nmo_vt_from_string_eulerangles)
NMO_DEFINE_ZERO_MEMCPY_TYPE_VTABLE(
    nmo_builtin_vtable_box,
    nmo_equals_bytes_box, nmo_hash_bytes_box,
    nmo_vt_to_string_box, nmo_vt_from_string_box)
NMO_DEFINE_ZERO_MEMCPY_TYPE_VTABLE(
    nmo_builtin_vtable_time,
    nmo_equals_float_bits, nmo_hash_float_bits,
    nmo_vt_to_string_time, nmo_vt_from_string_time)

const nmo_type_vtable_t nmo_builtin_vtable_none = {
    .to_string = nmo_vt_to_string_none,
    .from_string = nmo_vt_from_string_none,
};

const nmo_type_vtable_t nmo_builtin_vtable_voidbuf = {
    .to_string = nmo_vt_to_string_voidbuf,
    .from_string = nmo_vt_from_string_voidbuf,
};

static nmo_status_t nmo_builtin_create_array(void *instance, const nmo_type_descriptor_t *type, void *context) {
    (void)type;
    (void)context;

    if (instance == NULL) {
        NMO_RETURN_ERROR(NMO_ERR_INVALID_ARGUMENT, NMO_SEVERITY_ERROR, "array create: NULL instance");
    }

    nmo_array_t *arr = (nmo_array_t *)instance;
    return nmo_array_init(arr, 1, 0, NULL);
}

static void nmo_builtin_destroy_array(void *instance, const nmo_type_descriptor_t *type, void *context) {
    (void)type;
    (void)context;

    if (instance == NULL) {
        return;
    }

    nmo_array_dispose((nmo_array_t *)instance);
}

static nmo_status_t nmo_builtin_copy_array(
    const void *src,
    void *dst,
    const nmo_type_descriptor_t *type,
    nmo_arena_t *arena
) {
    (void)type;
    (void)arena;

    if (src == NULL || dst == NULL) {
        NMO_RETURN_ERROR(NMO_ERR_INVALID_ARGUMENT, NMO_SEVERITY_ERROR, "array copy: NULL argument");
    }

    const nmo_array_t *src_arr = (const nmo_array_t *)src;
    nmo_array_t *dst_arr = (nmo_array_t *)dst;

    /* Ensure destination starts empty to avoid leaking pre-existing backing store. */
    memset(dst_arr, 0, sizeof(*dst_arr));

    if (src_arr->element_size == 0) {
        /* Treat as empty byte array for resilience. */
        return nmo_array_init(dst_arr, 1, 0, NULL);
    }

    return nmo_array_clone(src_arr, dst_arr, &src_arr->allocator);
}

static bool nmo_builtin_equals_array(const void *a, const void *b) {
    if (a == b) {
        return true;
    }
    if (a == NULL || b == NULL) {
        return false;
    }

    const nmo_array_t *aa = (const nmo_array_t *)a;
    const nmo_array_t *bb = (const nmo_array_t *)b;

    if (aa->element_size != bb->element_size || aa->count != bb->count) {
        return false;
    }
    if (aa->count == 0) {
        return true;
    }
    if (aa->data == NULL || bb->data == NULL) {
        return false;
    }

    size_t byte_len = aa->count * aa->element_size;
    return memcmp(aa->data, bb->data, byte_len) == 0;
}

static uint32_t nmo_builtin_hash_array(const void *instance) {
    if (instance == NULL) {
        return 0;
    }

    const nmo_array_t *arr = (const nmo_array_t *)instance;
    const uint32_t seed = nmo_hash_int32((uint32_t)arr->element_size) ^ nmo_hash_int32((uint32_t)arr->count);

    if (arr->count == 0 || arr->data == NULL || arr->element_size == 0) {
        return seed;
    }

    size_t byte_len = arr->count * arr->element_size;
    return nmo_murmur3_32(arr->data, byte_len, seed);
}

static nmo_status_t nmo_builtin_to_string_array(
    const void *value,
    const nmo_type_descriptor_t *type,
    const nmo_type_registry_t *registry,
    char *buffer,
    size_t buffer_size,
    int depth
) {
    (void)type;
    (void)registry;
    (void)depth;

    if (buffer == NULL || buffer_size == 0) {
        NMO_RETURN_ERROR(NMO_ERR_INVALID_ARGUMENT, NMO_SEVERITY_ERROR, "array to_string: invalid buffer");
    }

    if (value == NULL) {
        int written = snprintf(buffer, buffer_size, "null");
        if (written < 0 || (size_t)written >= buffer_size) {
            NMO_RETURN_ERROR(NMO_ERR_BUFFER_OVERRUN, NMO_SEVERITY_ERROR, "array to_string: buffer too small");
        }
        NMO_RETURN_OK();
    }

    const nmo_array_t *arr = (const nmo_array_t *)value;
    int written = snprintf(buffer, buffer_size, "array(count=%zu, element_size=%zu)", arr->count, arr->element_size);
    if (written < 0 || (size_t)written >= buffer_size) {
        NMO_RETURN_ERROR(NMO_ERR_BUFFER_OVERRUN, NMO_SEVERITY_ERROR, "array to_string: buffer too small");
    }

    NMO_RETURN_OK();
}

static nmo_status_t nmo_builtin_from_string_array(
    void *value,
    const nmo_type_descriptor_t *type,
    const nmo_type_registry_t *registry,
    const char *string
) {
    (void)type;
    (void)registry;

    if (value == NULL || string == NULL) {
        NMO_RETURN_ERROR(NMO_ERR_INVALID_ARGUMENT, NMO_SEVERITY_ERROR, "array from_string: NULL argument");
    }

    /* Minimal parser: accept "[]" as an empty byte array. */
    if (strcmp(string, "[]") != 0) {
        NMO_RETURN_ERROR(NMO_ERR_INVALID_ARGUMENT, NMO_SEVERITY_ERROR, "array from_string: expected []");
    }

    nmo_array_t *arr = (nmo_array_t *)value;
    nmo_array_dispose(arr);
    return nmo_array_init(arr, 1, 0, NULL);
}

const nmo_type_vtable_t nmo_builtin_vtable_array = {
    .create = nmo_builtin_create_array,
    .destroy = nmo_builtin_destroy_array,
    .copy = nmo_builtin_copy_array,
    .equals = nmo_builtin_equals_array,
    .hash = nmo_builtin_hash_array,
    .to_string = nmo_builtin_to_string_array,
    .from_string = nmo_builtin_from_string_array,
};


/* ============================================================================
 * Builtin type value handlers
 * ============================================================================ */

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

static nmo_status_t nmo_validate_value_to_string_args(
    const void *value,
    const char *buffer,
    size_t buffer_size,
    size_t min_buffer_size,
    const char *message)
{
    if (!value || !buffer || buffer_size < min_buffer_size) {
        NMO_RETURN_ERROR(NMO_ERR_INVALID_ARGUMENT, NMO_SEVERITY_ERROR, "%s", message);
    }

    NMO_RETURN_OK();
}

static void nmo_format_real_text(
    double value,
    char *buffer,
    size_t buffer_size)
{
    if (isnan(value)) {
        snprintf(buffer, buffer_size, "NaN");
    } else if (isinf(value)) {
        snprintf(buffer, buffer_size, value > 0.0 ? "Infinity" : "-Infinity");
    } else {
        snprintf(buffer, buffer_size, "%.6g", value);
    }
}

static void nmo_format_float_tuple_text(
    const float *values,
    size_t count,
    char *buffer,
    size_t buffer_size)
{
    switch (count) {
        case 2:
            snprintf(buffer, buffer_size, "(%.6g, %.6g)",
                     values[0], values[1]);
            break;
        case 3:
            snprintf(buffer, buffer_size, "(%.6g, %.6g, %.6g)",
                     values[0], values[1], values[2]);
            break;
        case 4:
            snprintf(buffer, buffer_size, "(%.6g, %.6g, %.6g, %.6g)",
                     values[0], values[1], values[2], values[3]);
            break;
        default:
            snprintf(buffer, buffer_size, "()");
            break;
    }
}

static nmo_status_t nmo_format_i64_text(
    int64_t value,
    char *buffer,
    size_t buffer_size)
{
    snprintf(buffer, buffer_size, "%lld", (long long)value);
    NMO_RETURN_OK();
}

static nmo_status_t nmo_format_u64_text(
    uint64_t value,
    char *buffer,
    size_t buffer_size)
{
    snprintf(buffer, buffer_size, "%llu", (unsigned long long)value);
    NMO_RETURN_OK();
}

/* ============================================================================
 * Float Converters
 * ============================================================================ */

nmo_status_t nmo_type_float_to_string(
    const void *value,
    char *buffer,
    size_t buffer_size)
{
    nmo_status_t status = nmo_validate_value_to_string_args(
        value, buffer, buffer_size, 16, "Invalid arguments for float_to_string");
    if (status != NMO_OK) {
        return status;
    }

    nmo_format_real_text((double)*(const float*)value, buffer, buffer_size);
    NMO_RETURN_OK();
}

nmo_status_t nmo_type_float_from_string(
    void *value,
    const char *string)
{
    if (!value || !string) {
        NMO_RETURN_ERROR(NMO_ERR_INVALID_ARGUMENT, NMO_SEVERITY_ERROR, "Invalid arguments for float_from_string");
    }

    // Handle special cases
    if (strcmp(string, "NaN") == 0) {
        *(float*)value = NAN;
        NMO_RETURN_OK();
    }
    if (strcmp(string, "Infinity") == 0 || strcmp(string, "+Infinity") == 0) {
        *(float*)value = INFINITY;
        NMO_RETURN_OK();
    }
    if (strcmp(string, "-Infinity") == 0) {
        *(float*)value = -INFINITY;
        NMO_RETURN_OK();
    }

    float result = 0.0f;
    if (nmo_parse_f32(string, &result) != NMO_OK) {
        NMO_RETURN_ERROR(NMO_ERR_INVALID_FORMAT, NMO_SEVERITY_ERROR, "Invalid float format");
    }

    *(float*)value = result;
    NMO_RETURN_OK();
}

/* ============================================================================
 * Int Converters
 * ============================================================================ */

nmo_status_t nmo_type_int_to_string(
    const void *value,
    char *buffer,
    size_t buffer_size,
    bool use_hex)
{
    nmo_status_t status = nmo_validate_value_to_string_args(
        value, buffer, buffer_size, 16, "Invalid arguments for int_to_string");
    if (status != NMO_OK) {
        return status;
    }

    int32_t i = *(const int32_t*)value;

    if (use_hex) {
        snprintf(buffer, buffer_size, "0x%X", (unsigned int)i);
    } else {
        snprintf(buffer, buffer_size, "%d", i);
    }

    NMO_RETURN_OK();
}

nmo_status_t nmo_type_int_from_string(
    void *value,
    const char *string)
{
    if (!value || !string) {
        NMO_RETURN_ERROR(NMO_ERR_INVALID_ARGUMENT, NMO_SEVERITY_ERROR, "Invalid arguments for int_from_string");
    }

    int32_t result = 0;
    if (nmo_parse_i32_range_base(string, 0, INT32_MIN, INT32_MAX, &result) != NMO_OK) {
        NMO_RETURN_ERROR(NMO_ERR_INVALID_FORMAT, NMO_SEVERITY_ERROR, "Invalid int format");
    }

    *(int32_t*)value = result;
    NMO_RETURN_OK();
}

/* ============================================================================
 * Bool Converters
 * ============================================================================ */

nmo_status_t nmo_type_bool_to_string(
    const void *value,
    char *buffer,
    size_t buffer_size)
{
    nmo_status_t status = nmo_validate_value_to_string_args(
        value, buffer, buffer_size, 6, "Invalid arguments for bool_to_string");
    if (status != NMO_OK) {
        return status;
    }

    bool b = *(const bool*)value;
    snprintf(buffer, buffer_size, b ? "true" : "false");

    NMO_RETURN_OK();
}

nmo_status_t nmo_type_bool_from_string(
    void *value,
    const char *string)
{
    if (!value || !string) {
        NMO_RETURN_ERROR(NMO_ERR_INVALID_ARGUMENT, NMO_SEVERITY_ERROR, "Invalid arguments for bool_from_string");
    }

    // Skip whitespace
    while (*string && isspace(*string)) string++;

    if (strcmp(string, "true") == 0 || strcmp(string, "1") == 0 ||
        strcmp(string, "TRUE") == 0 || strcmp(string, "True") == 0) {
        *(bool*)value = true;
    } else if (strcmp(string, "false") == 0 || strcmp(string, "0") == 0 ||
               strcmp(string, "FALSE") == 0 || strcmp(string, "False") == 0) {
        *(bool*)value = false;
    } else {
        NMO_RETURN_ERROR(NMO_ERR_INVALID_FORMAT, NMO_SEVERITY_ERROR, "Invalid bool format (expected true/false/1/0)");
    }

    NMO_RETURN_OK();
}

/* ============================================================================
 * Vector Converters
 * ============================================================================ */

static nmo_status_t parse_float_tuple(
    const char *kind,
    const char *string,
    float *out,
    int count)
{
    if (!kind || !string || !out || count <= 0) {
        NMO_RETURN_ERROR(NMO_ERR_INVALID_ARGUMENT, NMO_SEVERITY_ERROR, "Invalid arguments for parse_float_tuple");
    }

    nmo_status_t st = nmo_parse_f32_parenthesized_tuple(
        string, ",;", out, (size_t)count);
    if (st != NMO_OK) {
        NMO_RETURN_ERROR(NMO_ERR_INVALID_FORMAT, NMO_SEVERITY_ERROR,
                         "Invalid %s tuple", kind);
    }

    NMO_RETURN_OK();
}

static nmo_status_t nmo_float_tuple_to_string(
    const void *value,
    char *buffer,
    size_t buffer_size,
    size_t min_buffer_size,
    size_t count,
    const char *message)
{
    nmo_status_t status = nmo_validate_value_to_string_args(
        value, buffer, buffer_size, min_buffer_size, message);
    if (status != NMO_OK) {
        return status;
    }

    nmo_format_float_tuple_text(
        (const float *)value, count, buffer, buffer_size);
    NMO_RETURN_OK();
}

static nmo_status_t nmo_float_tuple_from_string(
    void *value,
    const char *string,
    const char *kind,
    size_t count,
    const char *message)
{
    if (!value || !string) {
        NMO_RETURN_ERROR(NMO_ERR_INVALID_ARGUMENT, NMO_SEVERITY_ERROR, "%s", message);
    }

    return parse_float_tuple(kind, string, (float *)value, (int)count);
}

nmo_status_t nmo_type_vector2_to_string(
    const void *value,
    char *buffer,
    size_t buffer_size)
{
    return nmo_float_tuple_to_string(
        value, buffer, buffer_size, 24, 2,
        "Invalid arguments for vector2_to_string");
}

nmo_status_t nmo_type_vector2_from_string(
    void *value,
    const char *string)
{
    return nmo_float_tuple_from_string(
        value, string, "Vector2", 2,
        "Invalid arguments for vector2_from_string");
}

nmo_status_t nmo_type_vector3_to_string(
    const void *value,
    char *buffer,
    size_t buffer_size)
{
    return nmo_float_tuple_to_string(
        value, buffer, buffer_size, 32, 3,
        "Invalid arguments for vector_to_string");
}

nmo_status_t nmo_type_vector3_from_string(
    void *value,
    const char *string)
{
    return nmo_float_tuple_from_string(
        value, string, "Vector", 3,
        "Invalid arguments for vector_from_string");
}

nmo_status_t nmo_type_vector4_to_string(
    const void *value,
    char *buffer,
    size_t buffer_size)
{
    return nmo_float_tuple_to_string(
        value, buffer, buffer_size, 48, 4,
        "Invalid arguments for vector4_to_string");
}

nmo_status_t nmo_type_vector4_from_string(
    void *value,
    const char *string)
{
    return nmo_float_tuple_from_string(
        value, string, "Vector4", 4,
        "Invalid arguments for vector4_from_string");
}

/* ============================================================================
 * Quaternion Converters
 * ============================================================================ */

nmo_status_t nmo_type_quaternion_to_string(
    const void *value,
    char *buffer,
    size_t buffer_size)
{
    return nmo_float_tuple_to_string(
        value, buffer, buffer_size, 48, 4,
        "Invalid arguments for quaternion_to_string");
}

nmo_status_t nmo_type_quaternion_from_string(
    void *value,
    const char *string)
{
    return nmo_float_tuple_from_string(
        value, string, "Quaternion", 4,
        "Invalid arguments for quaternion_from_string");
}

/* ============================================================================
 * Matrix/Color Converters
 * ============================================================================ */

nmo_status_t nmo_type_matrix_to_string(
    const void *value,
    char *buffer,
    size_t buffer_size)
{
    nmo_status_t status = nmo_validate_value_to_string_args(
        value, buffer, buffer_size, 128, "Invalid arguments for matrix_to_string");
    if (status != NMO_OK) {
        return status;
    }

    const nmo_matrix_t *m = (const nmo_matrix_t*)value;
    snprintf(buffer, buffer_size,
             "(%.6g, %.6g, %.6g, %.6g; %.6g, %.6g, %.6g, %.6g; %.6g, %.6g, %.6g, %.6g; %.6g, %.6g, %.6g, %.6g)",
             m->m[0][0], m->m[0][1], m->m[0][2], m->m[0][3],
             m->m[1][0], m->m[1][1], m->m[1][2], m->m[1][3],
             m->m[2][0], m->m[2][1], m->m[2][2], m->m[2][3],
             m->m[3][0], m->m[3][1], m->m[3][2], m->m[3][3]);
    NMO_RETURN_OK();
}

nmo_status_t nmo_type_matrix_from_string(
    void *value,
    const char *string)
{
    if (!value || !string) {
        NMO_RETURN_ERROR(NMO_ERR_INVALID_ARGUMENT, NMO_SEVERITY_ERROR, "Invalid arguments for matrix_from_string");
    }

    float tmp[16];
    nmo_status_t r = parse_float_tuple("Matrix", string, tmp, 16);
    if (r != NMO_OK) {
        return r;
    }

    nmo_matrix_t *m = (nmo_matrix_t*)value;
    for (int row = 0; row < 4; row++) {
        for (int col = 0; col < 4; col++) {
            m->m[row][col] = tmp[row * 4 + col];
        }
    }
    NMO_RETURN_OK();
}

nmo_status_t nmo_type_color_to_string(
    const void *value,
    char *buffer,
    size_t buffer_size)
{
    return nmo_float_tuple_to_string(
        value, buffer, buffer_size, 48, 4,
        "Invalid arguments for color_to_string");
}

nmo_status_t nmo_type_color_from_string(
    void *value,
    const char *string)
{
    return nmo_float_tuple_from_string(
        value, string, "Color", 4,
        "Invalid arguments for color_from_string");
}

/* ============================================================================
 * String Escape/Unescape Utilities
 * ============================================================================ */

size_t nmo_string_escape(
    const char *src,
    char *dst,
    size_t dst_size)
{
    if (!src || !dst || dst_size < 3) {
        return 0;
    }

    size_t offset = 0;
    dst[offset++] = '"';  // Opening quote

    for (const char *p = src; *p && offset + 2 < dst_size; p++) {
        switch (*p) {
            case '"':  dst[offset++] = '\\'; dst[offset++] = '"'; break;
            case '\\': dst[offset++] = '\\'; dst[offset++] = '\\'; break;
            case '\n': dst[offset++] = '\\'; dst[offset++] = 'n'; break;
            case '\r': dst[offset++] = '\\'; dst[offset++] = 'r'; break;
            case '\t': dst[offset++] = '\\'; dst[offset++] = 't'; break;
            default:
                if (*p >= 32 && *p <= 126) {
                    dst[offset++] = *p;
                } else {
                    // Escape non-printable as \xHH
                    if (offset + 4 < dst_size) {
                        offset += snprintf(dst + offset, dst_size - offset, 
                                         "\\x%02X", (unsigned char)*p);
                    }
                }
                break;
        }
    }

    if (offset < dst_size) {
        dst[offset++] = '"';  // Closing quote
    }
    if (offset < dst_size) {
        dst[offset] = '\0';
    } else {
        dst[dst_size - 1] = '\0';
        offset = dst_size - 1;
    }

    return offset;
}

static int nmo_hex_digit_value(char c)
{
    if (c >= '0' && c <= '9') return c - '0';
    if (c >= 'a' && c <= 'f') return c - 'a' + 10;
    if (c >= 'A' && c <= 'F') return c - 'A' + 10;
    return -1;
}

size_t nmo_string_unescape(
    const char *src,
    char *dst,
    size_t dst_size)
{
    if (!src || !dst || dst_size < 1) {
        return 0;
    }

    // Skip opening quote
    if (*src == '"') src++;

    size_t offset = 0;
    for (const char *p = src; *p && offset + 1 < dst_size; p++) {
        if (*p == '"') break;  // Closing quote
        
        if (*p == '\\' && *(p + 1)) {
            p++;
            switch (*p) {
                case '"':  dst[offset++] = '"'; break;
                case '\\': dst[offset++] = '\\'; break;
                case 'n':  dst[offset++] = '\n'; break;
                case 'r':  dst[offset++] = '\r'; break;
                case 't':  dst[offset++] = '\t'; break;
                case 'x':  // Hex escape \xHH
                    if (isxdigit(*(p + 1)) && isxdigit(*(p + 2))) {
                        int hi = nmo_hex_digit_value(*(p + 1));
                        int lo = nmo_hex_digit_value(*(p + 2));
                        dst[offset++] = (char)((hi << 4) | lo);
                        p += 2;
                    }
                    break;
                default:
                    dst[offset++] = *p;
                    break;
            }
        } else {
            dst[offset++] = *p;
        }
    }

    if (offset < dst_size) {
        dst[offset] = '\0';
    } else {
        dst[dst_size - 1] = '\0';
        offset = dst_size - 1;
    }

    return offset;
}

/* ============================================================================
 * String Converters
 * ============================================================================ */

nmo_status_t nmo_type_string_to_string(
    const void *value,
    char *buffer,
    size_t buffer_size)
{
    nmo_status_t status = nmo_validate_value_to_string_args(
        value, buffer, buffer_size, 3, "Invalid arguments for string_to_string");
    if (status != NMO_OK) {
        return status;
    }

    const char *str = *(const char**)value;
    if (!str) {
        snprintf(buffer, buffer_size, "\"\"");
        NMO_RETURN_OK();
    }

    nmo_string_escape(str, buffer, buffer_size);
    NMO_RETURN_OK();
}

nmo_status_t nmo_type_string_from_string(
    void *value,
    const char *string,
    nmo_arena_t *arena)
{
    if (!value || !string || !arena) {
        NMO_RETURN_ERROR(NMO_ERR_INVALID_ARGUMENT, NMO_SEVERITY_ERROR, "Invalid arguments for string_from_string");
    }

    // Estimate unescaped length (worst case: same as input)
    size_t max_len = strlen(string) + 1;
    char *temp = (char*)nmo_arena_alloc(arena, max_len, 1);
    if (!temp) {
        NMO_RETURN_ERROR(NMO_ERR_NOMEM, NMO_SEVERITY_ERROR, "Failed to allocate string buffer");
    }

    nmo_string_unescape(string, temp, max_len);
    
    // Allocate exact size needed
    size_t actual_len = strlen(temp) + 1;
    char *result = (char*)nmo_arena_alloc(arena, actual_len, 1);
    if (!result) {
        NMO_RETURN_ERROR(NMO_ERR_NOMEM, NMO_SEVERITY_ERROR, "Failed to allocate final string");
    }

    memcpy(result, temp, actual_len);
    *(char**)value = result;

    NMO_RETURN_OK();
}

/* ============================================================================
 * Object ID Converters
 * ============================================================================ */

nmo_status_t nmo_type_object_id_to_string(
    const void *value,
    char *buffer,
    size_t buffer_size)
{
    if (!value || !buffer || buffer_size == 0) {
        NMO_RETURN_ERROR(NMO_ERR_INVALID_ARGUMENT, NMO_SEVERITY_ERROR, "Invalid arguments for object_id_to_string");
    }

    nmo_object_id_t id = *(const nmo_object_id_t*)value;
    int written = snprintf(buffer, buffer_size, "#%u", id);
    if (written < 0 || (size_t)written >= buffer_size) {
        NMO_RETURN_ERROR(NMO_ERR_BUFFER_OVERRUN, NMO_SEVERITY_ERROR, "Buffer too small for object id");
    }
    NMO_RETURN_OK();
}

nmo_status_t nmo_type_object_id_from_string(
    void *value,
    const char *string)
{
    if (!value || !string) {
        NMO_RETURN_ERROR(NMO_ERR_INVALID_ARGUMENT, NMO_SEVERITY_ERROR, "Invalid arguments for object_id_from_string");
    }

    // Parse #id format
    if (*string == '#') {
        nmo_object_id_t id = 0;
        if (nmo_parse_object_id(string, &id) == NMO_OK) {
            *(nmo_object_id_t*)value = id;
            NMO_RETURN_OK();
        }
    }

    NMO_RETURN_ERROR(NMO_ERR_INVALID_FORMAT, NMO_SEVERITY_ERROR, "Invalid object ID format (expected #id)");
}

/* ============================================================================
 * General-Purpose Dispatcher
 * ============================================================================ */

/* Semantic vtable handlers — new signature */

nmo_status_t nmo_vt_to_string_angle(
    const void *value, const nmo_type_descriptor_t *type,
    const nmo_type_registry_t *registry,
    char *buffer, size_t buffer_size, int depth)
{
    (void)type; (void)registry; (void)depth;
    float rad = *(const float *)value;
    double deg = (double)rad * (180.0 / M_PI);
    snprintf(buffer, buffer_size, "%.6g\xC2\xB0", deg);
    NMO_RETURN_OK();
}

nmo_status_t nmo_vt_to_string_percentage(
    const void *value, const nmo_type_descriptor_t *type,
    const nmo_type_registry_t *registry,
    char *buffer, size_t buffer_size, int depth)
{
    (void)type; (void)registry; (void)depth;
    float f = *(const float *)value;
    snprintf(buffer, buffer_size, "%.6g%%", (double)f * 100.0);
    NMO_RETURN_OK();
}

nmo_status_t nmo_vt_from_string_percentage(
    void *value,
    const nmo_type_descriptor_t *type,
    const nmo_type_registry_t *registry,
    const char *string)
{
    (void)type;
    (void)registry;
    if (!value || !string) {
        NMO_RETURN_ERROR(NMO_ERR_INVALID_ARGUMENT, NMO_SEVERITY_ERROR,
                         "Invalid arguments for percentage from_string");
    }

    size_t len = strlen(string);
    while (len > 0 && isspace((unsigned char)string[len - 1u])) {
        len--;
    }
    if (len > 0 && string[len - 1u] == '%') {
        len--;
        while (len > 0 && isspace((unsigned char)string[len - 1u])) {
            len--;
        }

        char stack_buf[64];
        char *number = stack_buf;
        if (len + 1u > sizeof(stack_buf)) {
            number = (char *)malloc(len + 1u);
            if (!number) {
                NMO_RETURN_ERROR(NMO_ERR_NOMEM, NMO_SEVERITY_ERROR,
                                 "Failed to allocate percentage value");
            }
        }

        memcpy(number, string, len);
        number[len] = '\0';
        float parsed = 0.0f;
        nmo_status_t st = nmo_type_float_from_string(&parsed, number);
        if (number != stack_buf) {
            free(number);
        }
        if (st != NMO_OK) {
            return st;
        }
        *(float *)value = parsed / 100.0f;
        NMO_RETURN_OK();
    }

    return nmo_type_float_from_string(value, string);
}

nmo_status_t nmo_vt_to_string_time(
    const void *value, const nmo_type_descriptor_t *type,
    const nmo_type_registry_t *registry,
    char *buffer, size_t buffer_size, int depth)
{
    (void)type; (void)registry; (void)depth;
    float f = *(const float *)value;
    snprintf(buffer, buffer_size, "%.1f ms", (double)f);
    NMO_RETURN_OK();
}

nmo_status_t nmo_vt_from_string_time(
    void *value,
    const nmo_type_descriptor_t *type,
    const nmo_type_registry_t *registry,
    const char *string)
{
    (void)type;
    (void)registry;
    if (!value || !string) {
        NMO_RETURN_ERROR(NMO_ERR_INVALID_ARGUMENT, NMO_SEVERITY_ERROR,
                         "Invalid arguments for time from_string");
    }

    float numeric = 0.0f;
    if (nmo_type_float_from_string(&numeric, string) == NMO_OK) {
        *(float *)value = numeric;
        NMO_RETURN_OK();
    }

    const char *cursor = string;
    float total_ms = 0.0f;
    bool saw_component = false;
    while (*cursor) {
        while (isspace((unsigned char)*cursor)) {
            cursor++;
        }
        if (*cursor == '\0') {
            break;
        }

        const char *number_start = cursor;
        if (*cursor == '+' || *cursor == '-') {
            cursor++;
        }
        bool saw_digit = false;
        while (isdigit((unsigned char)*cursor)) {
            saw_digit = true;
            cursor++;
        }
        if (*cursor == '.') {
            cursor++;
            while (isdigit((unsigned char)*cursor)) {
                saw_digit = true;
                cursor++;
            }
        }
        if ((*cursor == 'e' || *cursor == 'E') && saw_digit) {
            const char *exponent = cursor;
            cursor++;
            if (*cursor == '+' || *cursor == '-') {
                cursor++;
            }
            bool saw_exponent_digit = false;
            while (isdigit((unsigned char)*cursor)) {
                saw_exponent_digit = true;
                cursor++;
            }
            if (!saw_exponent_digit) {
                cursor = exponent;
            }
        }
        if (!saw_digit) {
            NMO_RETURN_ERROR(NMO_ERR_INVALID_FORMAT, NMO_SEVERITY_ERROR,
                             "Invalid time value");
        }

        size_t number_len = (size_t)(cursor - number_start);
        if (number_len >= 64u) {
            NMO_RETURN_ERROR(NMO_ERR_INVALID_FORMAT, NMO_SEVERITY_ERROR,
                             "Invalid time value");
        }
        char number[64];
        memcpy(number, number_start, number_len);
        number[number_len] = '\0';

        float amount = 0.0f;
        if (nmo_type_float_from_string(&amount, number) != NMO_OK) {
            NMO_RETURN_ERROR(NMO_ERR_INVALID_FORMAT, NMO_SEVERITY_ERROR,
                             "Invalid time value");
        }
        while (isspace((unsigned char)*cursor)) {
            cursor++;
        }

        if (cursor[0] == 'm' && cursor[1] == 's') {
            total_ms += amount;
            cursor += 2;
        } else if (cursor[0] == 'm') {
            total_ms += amount * 60000.0f;
            cursor += 1;
        } else if (cursor[0] == 's') {
            total_ms += amount * 1000.0f;
            cursor += 1;
        } else {
            NMO_RETURN_ERROR(NMO_ERR_INVALID_FORMAT, NMO_SEVERITY_ERROR,
                             "Invalid time unit");
        }
        saw_component = true;
    }

    if (!saw_component) {
        NMO_RETURN_ERROR(NMO_ERR_INVALID_FORMAT, NMO_SEVERITY_ERROR,
                         "Invalid time value");
    }
    *(float *)value = total_ms;
    NMO_RETURN_OK();
}

nmo_status_t nmo_vt_to_string_classid(
    const void *value, const nmo_type_descriptor_t *type,
    const nmo_type_registry_t *registry,
    char *buffer, size_t buffer_size, int depth)
{
    (void)type; (void)registry; (void)depth;
    int32_t cid = *(const int32_t *)value;
    snprintf(buffer, buffer_size, "ClassID(%d)", cid);
    NMO_RETURN_OK();
}

#define NMO_DEFINE_PLACEHOLDER_VTABLE(name, literal, error_message) \
    nmo_status_t nmo_vt_to_string_##name( \
        const void *value, const nmo_type_descriptor_t *type, \
        const nmo_type_registry_t *registry, \
        char *buffer, size_t buffer_size, int depth) \
    { \
        (void)value; \
        (void)type; \
        (void)registry; \
        (void)depth; \
        snprintf(buffer, buffer_size, literal); \
        NMO_RETURN_OK(); \
    } \
    nmo_status_t nmo_vt_from_string_##name( \
        void *value, const nmo_type_descriptor_t *type, \
        const nmo_type_registry_t *registry, const char *string) \
    { \
        (void)value; \
        (void)type; \
        (void)registry; \
        if (string && strcmp(string, literal) == 0) { \
            NMO_RETURN_OK(); \
        } \
        NMO_RETURN_ERROR( \
            NMO_ERR_INVALID_FORMAT, NMO_SEVERITY_ERROR, error_message); \
    }

NMO_DEFINE_PLACEHOLDER_VTABLE(none, "(none)", "Invalid none placeholder")
NMO_DEFINE_PLACEHOLDER_VTABLE(voidbuf, "<voidbuf>", "Invalid voidbuf placeholder")

static nmo_status_t parse_i64(const char *string, int64_t *out_value)
{
    if (!string || !out_value) {
        NMO_RETURN_ERROR(NMO_ERR_INVALID_ARGUMENT, NMO_SEVERITY_ERROR, "Invalid integer parse args");
    }

    int64_t parsed = 0;
    nmo_status_t st = nmo_parse_i64_range_base(
        string, 0, INT64_MIN, INT64_MAX, &parsed);
    if (st != NMO_OK) {
        NMO_RETURN_ERROR(NMO_ERR_INVALID_FORMAT, NMO_SEVERITY_ERROR, "Invalid integer format");
    }

    *out_value = parsed;
    NMO_RETURN_OK();
}

static nmo_status_t parse_u64(const char *string, uint64_t *out_value)
{
    if (!string || !out_value) {
        NMO_RETURN_ERROR(NMO_ERR_INVALID_ARGUMENT, NMO_SEVERITY_ERROR, "Invalid unsigned parse args");
    }

    uint64_t parsed = 0;
    nmo_status_t st = nmo_parse_u64_range_base(
        string, 0, 0, UINT64_MAX, &parsed);
    if (st != NMO_OK) {
        NMO_RETURN_ERROR(NMO_ERR_INVALID_FORMAT, NMO_SEVERITY_ERROR, "Invalid unsigned integer format");
    }

    *out_value = parsed;
    NMO_RETURN_OK();
}

static nmo_status_t parse_i64_checked(
    const char *string,
    int64_t min_value,
    int64_t max_value,
    const char *range_message,
    int64_t *out_value)
{
    int64_t parsed = 0;
    nmo_status_t st = parse_i64(string, &parsed);
    if (st != NMO_OK) {
        return st;
    }
    if (parsed < min_value || parsed > max_value) {
        NMO_RETURN_ERROR(NMO_ERR_OUT_OF_BOUNDS, NMO_SEVERITY_ERROR, "%s", range_message);
    }

    *out_value = parsed;
    NMO_RETURN_OK();
}

static nmo_status_t parse_u64_checked(
    const char *string,
    uint64_t max_value,
    const char *range_message,
    uint64_t *out_value)
{
    uint64_t parsed = 0;
    nmo_status_t st = parse_u64(string, &parsed);
    if (st != NMO_OK) {
        return st;
    }
    if (parsed > max_value) {
        NMO_RETURN_ERROR(NMO_ERR_OUT_OF_BOUNDS, NMO_SEVERITY_ERROR, "%s", range_message);
    }

    *out_value = parsed;
    NMO_RETURN_OK();
}

static nmo_status_t parse_f64(const char *string, double *out_value)
{
    if (!string || !out_value) {
        NMO_RETURN_ERROR(NMO_ERR_INVALID_ARGUMENT, NMO_SEVERITY_ERROR, "Invalid floating parse args");
    }

    if (strcmp(string, "NaN") == 0) {
        *out_value = NAN;
        NMO_RETURN_OK();
    }
    if (strcmp(string, "Infinity") == 0 || strcmp(string, "+Infinity") == 0) {
        *out_value = INFINITY;
        NMO_RETURN_OK();
    }
    if (strcmp(string, "-Infinity") == 0) {
        *out_value = -INFINITY;
        NMO_RETURN_OK();
    }

    double parsed = 0.0;
    if (nmo_parse_f64(string, &parsed) != NMO_OK) {
        NMO_RETURN_ERROR(NMO_ERR_INVALID_FORMAT, NMO_SEVERITY_ERROR, "Invalid floating-point format");
    }

    *out_value = parsed;
    NMO_RETURN_OK();
}

static nmo_status_t nmo_parse_int8(
    void *value,
    const nmo_type_registry_t *registry,
    const char *string)
{
    (void)registry;
    int64_t parsed = 0;
    nmo_status_t st = parse_i64_checked(
        string, INT8_MIN, INT8_MAX, "INT8 out of range", &parsed);
    if (st != NMO_OK) return st;
    *(int8_t *)value = (int8_t)parsed;
    NMO_RETURN_OK();
}

static nmo_status_t nmo_parse_int16(
    void *value,
    const nmo_type_registry_t *registry,
    const char *string)
{
    (void)registry;
    int64_t parsed = 0;
    nmo_status_t st = parse_i64_checked(
        string, INT16_MIN, INT16_MAX, "INT16 out of range", &parsed);
    if (st != NMO_OK) return st;
    *(int16_t *)value = (int16_t)parsed;
    NMO_RETURN_OK();
}

static nmo_status_t nmo_parse_int32(
    void *value,
    const nmo_type_registry_t *registry,
    const char *string)
{
    (void)registry;
    return nmo_type_int_from_string(value, string);
}

static nmo_status_t nmo_parse_int64(
    void *value,
    const nmo_type_registry_t *registry,
    const char *string)
{
    (void)registry;
    int64_t parsed = 0;
    nmo_status_t st = parse_i64(string, &parsed);
    if (st != NMO_OK) return st;
    *(int64_t *)value = parsed;
    NMO_RETURN_OK();
}

static nmo_status_t nmo_parse_uint8(
    void *value,
    const nmo_type_registry_t *registry,
    const char *string)
{
    (void)registry;
    uint64_t parsed = 0;
    nmo_status_t st = parse_u64_checked(
        string, UINT8_MAX, "UINT8 out of range", &parsed);
    if (st != NMO_OK) return st;
    *(uint8_t *)value = (uint8_t)parsed;
    NMO_RETURN_OK();
}

static nmo_status_t nmo_parse_uint16(
    void *value,
    const nmo_type_registry_t *registry,
    const char *string)
{
    (void)registry;
    uint64_t parsed = 0;
    nmo_status_t st = parse_u64_checked(
        string, UINT16_MAX, "UINT16 out of range", &parsed);
    if (st != NMO_OK) return st;
    *(uint16_t *)value = (uint16_t)parsed;
    NMO_RETURN_OK();
}

static nmo_status_t nmo_parse_uint32(
    void *value,
    const nmo_type_registry_t *registry,
    const char *string)
{
    (void)registry;
    uint64_t parsed = 0;
    nmo_status_t st = parse_u64_checked(
        string, UINT32_MAX, "UINT32 out of range", &parsed);
    if (st != NMO_OK) return st;
    *(uint32_t *)value = (uint32_t)parsed;
    NMO_RETURN_OK();
}

static nmo_status_t nmo_parse_uint64(
    void *value,
    const nmo_type_registry_t *registry,
    const char *string)
{
    (void)registry;
    uint64_t parsed = 0;
    nmo_status_t st = parse_u64(string, &parsed);
    if (st != NMO_OK) return st;
    *(uint64_t *)value = parsed;
    NMO_RETURN_OK();
}

#define NMO_DEFINE_PARSE_ADAPTER(name, parse_fn) \
    static nmo_status_t nmo_parse_##name( \
        void *value, \
        const nmo_type_registry_t *registry, \
        const char *string) \
    { \
        (void)registry; \
        return (parse_fn)(value, string); \
    }

NMO_DEFINE_PARSE_ADAPTER(bool, nmo_type_bool_from_string)
NMO_DEFINE_PARSE_ADAPTER(float, nmo_type_float_from_string)

static nmo_status_t nmo_parse_double(
    void *value,
    const nmo_type_registry_t *registry,
    const char *string)
{
    (void)registry;
    double parsed = 0.0;
    nmo_status_t st = parse_f64(string, &parsed);
    if (st != NMO_OK) return st;
    *(double *)value = parsed;
    NMO_RETURN_OK();
}

static nmo_status_t nmo_parse_string(
    void *value,
    const nmo_type_registry_t *registry,
    const char *string)
{
    if (!registry || !registry->arena) {
        NMO_RETURN_ERROR(NMO_ERR_INVALID_ARGUMENT, NMO_SEVERITY_ERROR,
                         "Registry with arena required for string parsing");
    }
    return nmo_type_string_from_string(value, string, (nmo_arena_t *)registry->arena);
}

NMO_DEFINE_PARSE_ADAPTER(vector2, nmo_type_vector2_from_string)
NMO_DEFINE_PARSE_ADAPTER(vector3, nmo_type_vector3_from_string)
NMO_DEFINE_PARSE_ADAPTER(vector4, nmo_type_vector4_from_string)
NMO_DEFINE_PARSE_ADAPTER(quaternion, nmo_type_quaternion_from_string)
NMO_DEFINE_PARSE_ADAPTER(matrix, nmo_type_matrix_from_string)
NMO_DEFINE_PARSE_ADAPTER(color, nmo_type_color_from_string)

static nmo_status_t nmo_parse_guid(
    void *value,
    const nmo_type_registry_t *registry,
    const char *string)
{
    (void)registry;
    if (!value || !string) {
        NMO_RETURN_ERROR(NMO_ERR_INVALID_ARGUMENT, NMO_SEVERITY_ERROR, "Invalid arguments for guid parse");
    }

    while (*string && isspace((unsigned char)*string)) string++;
    nmo_guid_t g = nmo_guid_parse(string);
    if (nmo_guid_is_null(g) && !(string[0] == '0' && string[1] == '\0')) {
        /* Accept {00000000-00000000} as valid null GUID, but reject parse failures */
        if (strcmp(string, "{00000000-00000000}") != 0 &&
            strcmp(string, "00000000-00000000") != 0 &&
            strcmp(string, "0000000000000000") != 0) {
            NMO_RETURN_ERROR(NMO_ERR_INVALID_FORMAT, NMO_SEVERITY_ERROR, "Invalid GUID format");
        }
    }

    *(nmo_guid_t *)value = g;
    NMO_RETURN_OK();
}

static nmo_status_t nmo_parse_pointer(
    void *value,
    const nmo_type_registry_t *registry,
    const char *string)
{
    (void)registry;
    if (!value || !string) {
        NMO_RETURN_ERROR(NMO_ERR_INVALID_ARGUMENT, NMO_SEVERITY_ERROR, "Invalid arguments for pointer parse");
    }

    while (*string && isspace((unsigned char)*string)) string++;
    if (strcmp(string, "null") == 0 || strcmp(string, "NULL") == 0) {
        *(void **)value = NULL;
        NMO_RETURN_OK();
    }

    uint64_t parsed = 0;
    nmo_status_t st = nmo_parse_u64_range_base(
        string, 0, 0, UINT64_MAX, &parsed);
    if (st != NMO_OK) {
        /* Try hex without 0x (common %p style) */
        st = nmo_parse_u64_range_base(string, 16, 0, UINT64_MAX, &parsed);
    }
    if (st != NMO_OK) {
        NMO_RETURN_ERROR(NMO_ERR_INVALID_FORMAT, NMO_SEVERITY_ERROR, "Invalid pointer format");
    }

    *(void **)value = (void *)(uintptr_t)parsed;
    NMO_RETURN_OK();
}

static nmo_status_t nmo_parse_object_id_value(
    void *value,
    const nmo_type_registry_t *registry,
    const char *string)
{
    (void)registry;
    if (!value || !string) {
        NMO_RETURN_ERROR(NMO_ERR_INVALID_ARGUMENT, NMO_SEVERITY_ERROR, "Invalid arguments for object id parse");
    }

    /* Prefer #id format */
    nmo_status_t st = nmo_type_object_id_from_string(value, string);
    if (st == NMO_OK) {
        return st;
    }

    /* Back-compat: accept raw integer without '#' */
    return nmo_parse_uint32(value, registry, string);
}

static nmo_status_t nmo_parse_rect(
    void *value,
    const nmo_type_registry_t *registry,
    const char *string)
{
    (void)registry;
    if (!value || !string) {
        NMO_RETURN_ERROR(NMO_ERR_INVALID_ARGUMENT, NMO_SEVERITY_ERROR, "Invalid arguments for rect parse");
    }

    float out[4] = {0};
    nmo_status_t st = parse_float_tuple("Rect", string, out, 4);
    if (st != NMO_OK) {
        char tail = '\0';
        int matched = sscanf(
            string, " ( %f , %f ) , ( %f , %f ) %c",
            &out[0], &out[1], &out[2], &out[3], &tail);
        if (matched == 4) {
            st = NMO_OK;
        }
    }
    if (st != NMO_OK) return st;

    nmo_rect_t *r = (nmo_rect_t *)value;
    r->left = out[0];
    r->top = out[1];
    r->right = out[2];
    r->bottom = out[3];
    NMO_RETURN_OK();
}

static const char *find_matching_paren_end(const char *text)
{
    int depth = 0;
    for (const char *p = text; *p != '\0'; ++p) {
        if (*p == '(') {
            depth++;
        } else if (*p == ')') {
            depth--;
            if (depth == 0) {
                return p + 1;
            }
        }
    }
    return NULL;
}

static nmo_status_t parse_vector_segment(
    const char *start,
    const char *end,
    nmo_vector_t *out_value)
{
    if (!start || !end || end <= start || !out_value) {
        NMO_RETURN_ERROR(NMO_ERR_INVALID_ARGUMENT, NMO_SEVERITY_ERROR,
                         "Invalid vector segment");
    }

    size_t len = (size_t)(end - start);
    char stack_buf[128];
    char *buf = stack_buf;
    if (len + 1u > sizeof(stack_buf)) {
        buf = (char *)malloc(len + 1u);
        if (!buf) {
            NMO_RETURN_ERROR(NMO_ERR_NOMEM, NMO_SEVERITY_ERROR,
                             "Failed to allocate vector segment");
        }
    }

    memcpy(buf, start, len);
    buf[len] = '\0';
    nmo_status_t st = nmo_type_vector3_from_string(out_value, buf);
    if (buf != stack_buf) {
        free(buf);
    }
    return st;
}

static nmo_status_t nmo_parse_box(
    void *value,
    const nmo_type_registry_t *registry,
    const char *string)
{
    (void)registry;
    if (!value || !string) {
        NMO_RETURN_ERROR(NMO_ERR_INVALID_ARGUMENT, NMO_SEVERITY_ERROR, "Invalid arguments for box parse");
    }

    /* Format: ((x,y,z), (x,y,z)) with optional whitespace */
    while (*string && isspace((unsigned char)*string)) string++;
    if (*string != '(') {
        NMO_RETURN_ERROR(NMO_ERR_INVALID_FORMAT, NMO_SEVERITY_ERROR, "Box must start with '('");
    }
    string++;
    while (*string && isspace((unsigned char)*string)) string++;
    if (*string != '(') {
        NMO_RETURN_ERROR(NMO_ERR_INVALID_FORMAT, NMO_SEVERITY_ERROR, "Box must contain '(min, max)'");
    }

    /* Parse first vector3 */
    nmo_vector_t minv = {0};
    const char *p = find_matching_paren_end(string);
    if (!p) {
        NMO_RETURN_ERROR(NMO_ERR_INVALID_FORMAT, NMO_SEVERITY_ERROR, "Unclosed min vector");
    }
    NMO_RETURN_IF_ERROR(parse_vector_segment(string, p, &minv));

    while (*p && isspace((unsigned char)*p)) p++;
    if (*p != ',') {
        NMO_RETURN_ERROR(NMO_ERR_INVALID_FORMAT, NMO_SEVERITY_ERROR, "Box vectors must be separated by ','");
    }
    p++;
    while (*p && isspace((unsigned char)*p)) p++;
    if (*p != '(') {
        NMO_RETURN_ERROR(NMO_ERR_INVALID_FORMAT, NMO_SEVERITY_ERROR, "Box max vector must start with '('");
    }

    nmo_vector_t maxv = {0};
    const char *q = find_matching_paren_end(p);
    if (!q) {
        NMO_RETURN_ERROR(NMO_ERR_INVALID_FORMAT, NMO_SEVERITY_ERROR, "Unclosed max vector");
    }
    NMO_RETURN_IF_ERROR(parse_vector_segment(p, q, &maxv));

    while (*q && isspace((unsigned char)*q)) q++;
    if (*q != ')') {
        NMO_RETURN_ERROR(NMO_ERR_INVALID_FORMAT, NMO_SEVERITY_ERROR, "Box must end with ')'");
    }

    nmo_box_t *b = (nmo_box_t *)value;
    b->min = minv;
    b->max = maxv;
    NMO_RETURN_OK();
}

static nmo_status_t nmo_parse_eulerangles(
    void *value,
    const nmo_type_registry_t *registry,
    const char *string)
{
    (void)registry;
    if (!value || !string) {
        NMO_RETURN_ERROR(NMO_ERR_INVALID_ARGUMENT, NMO_SEVERITY_ERROR, "Invalid arguments for euler parse");
    }

    float out[3] = {0};
    nmo_status_t st = parse_float_tuple("EulerAngles", string, out, 3);
    if (st != NMO_OK) return st;

    nmo_eulerangles_t *e = (nmo_eulerangles_t *)value;
    e->x = out[0];
    e->y = out[1];
    e->z = out[2];
    NMO_RETURN_OK();
}

/* ============================================================================
 * Builtin Type VTable Helpers
 *
 * These functions are referenced by builtin vtables.
 * The vtable objects themselves are defined in builtin_operations.c.
 * ============================================================================ */

nmo_status_t nmo_builtin_create_zero(void *instance, const nmo_type_descriptor_t *type, void *context)
{
    (void)context;
    if (!instance || !type) {
        NMO_RETURN_ERROR(NMO_ERR_INVALID_ARGUMENT, NMO_SEVERITY_ERROR, "Invalid args for create");
    }
    if (type->size > 0) {
        memset(instance, 0, type->size);
    }
    NMO_RETURN_OK();
}

void nmo_builtin_destroy_noop(void *instance, const nmo_type_descriptor_t *type, void *context)
{
    (void)instance;
    (void)type;
    (void)context;
}

nmo_status_t nmo_builtin_copy_memcpy(
    const void *src,
    void *dst,
    const nmo_type_descriptor_t *type,
    nmo_arena_t *arena)
{
    (void)arena;
    if (!src || !dst || !type) {
        NMO_RETURN_ERROR(NMO_ERR_INVALID_ARGUMENT, NMO_SEVERITY_ERROR, "Invalid args for copy");
    }
    if (type->size > 0) {
        memcpy(dst, src, type->size);
    }
    NMO_RETURN_OK();
}

nmo_status_t nmo_builtin_copy_string(
    const void *src,
    void *dst,
    const nmo_type_descriptor_t *type,
    nmo_arena_t *arena)
{
    (void)type;
    if (!src || !dst) {
        NMO_RETURN_ERROR(NMO_ERR_INVALID_ARGUMENT, NMO_SEVERITY_ERROR, "Invalid args for string copy");
    }

    const char *s = *(const char *const *)src;
    if (!s) {
        *(char **)dst = NULL;
        NMO_RETURN_OK();
    }

    if (!arena) {
        *(char **)dst = (char *)s;
        NMO_RETURN_OK();
    }

    const char *copy = nmo_arena_strdup(arena, s);
    if (!copy) {
        NMO_RETURN_ERROR(NMO_ERR_NOMEM, NMO_SEVERITY_ERROR, "Failed to copy string");
    }
    *(const char **)dst = copy;
    NMO_RETURN_OK();
}

static uint32_t nmo_hash_u64_fold(uint64_t v)
{
    uint64_t h = nmo_hash_int64(v);
    return (uint32_t)(h ^ (h >> 32));
}

bool nmo_equals_float_bits(const void *a, const void *b)
{
    uint32_t av = 0;
    uint32_t bv = 0;
    memcpy(&av, a, sizeof(av));
    memcpy(&bv, b, sizeof(bv));
    return av == bv;
}

uint32_t nmo_hash_float_bits(const void *instance)
{
    uint32_t bits = 0;
    memcpy(&bits, instance, sizeof(bits));
    return nmo_hash_int32(bits);
}

bool nmo_equals_double_bits(const void *a, const void *b)
{
    uint64_t av = 0;
    uint64_t bv = 0;
    memcpy(&av, a, sizeof(av));
    memcpy(&bv, b, sizeof(bv));
    return av == bv;
}

uint32_t nmo_hash_double_bits(const void *instance)
{
    uint64_t bits = 0;
    memcpy(&bits, instance, sizeof(bits));
    return nmo_hash_u64_fold(bits);
}

bool nmo_equals_string_value(const void *a, const void *b)
{
    const char *sa = *(const char *const *)a;
    const char *sb = *(const char *const *)b;
    if (sa == sb) {
        return true;
    }
    if (!sa || !sb) {
        return false;
    }
    return strcmp(sa, sb) == 0;
}

uint32_t nmo_hash_string_value(const void *instance)
{
    const char *s = *(const char *const *)instance;
    if (!s) {
        return 0;
    }
    return nmo_murmur3_32(s, strlen(s), 0);
}

#define NMO_DEFINE_EQ_HASH_U32(tag, c_type) \
    bool nmo_vt_equals_##tag(const void *a, const void *b) { \
        return *(const c_type *)a == *(const c_type *)b; \
    } \
    uint32_t nmo_vt_hash_##tag(const void *instance) { \
        return (uint32_t)nmo_hash_int32((uint32_t)(*(const c_type *)instance)); \
    }

#define NMO_DEFINE_EQ_HASH_U64(tag, c_type) \
    bool nmo_vt_equals_##tag(const void *a, const void *b) { \
        return *(const c_type *)a == *(const c_type *)b; \
    } \
    uint32_t nmo_vt_hash_##tag(const void *instance) { \
        return nmo_hash_u64_fold((uint64_t)(*(const c_type *)instance)); \
    }

#define NMO_DEFINE_EQ_HASH_BYTES(tag, c_type) \
    bool nmo_equals_bytes_##tag(const void *a, const void *b) { \
        return memcmp(a, b, sizeof(c_type)) == 0; \
    } \
    uint32_t nmo_hash_bytes_##tag(const void *instance) { \
        return nmo_murmur3_32(instance, sizeof(c_type), 0); \
    }

NMO_DEFINE_EQ_HASH_U32(int32, int32_t)
NMO_DEFINE_EQ_HASH_U32(uint32, uint32_t)
NMO_DEFINE_EQ_HASH_U32(int8, int8_t)
NMO_DEFINE_EQ_HASH_U32(uint8, uint8_t)
NMO_DEFINE_EQ_HASH_U32(int16, int16_t)
NMO_DEFINE_EQ_HASH_U32(uint16, uint16_t)
NMO_DEFINE_EQ_HASH_U64(int64, int64_t)
NMO_DEFINE_EQ_HASH_U64(uint64, uint64_t)

bool nmo_equals_bool(const void *a, const void *b)
{
    return *(const bool *)a == *(const bool *)b;
}

uint32_t nmo_hash_bool(const void *instance)
{
    return nmo_hash_int32(*(const bool *)instance ? 1u : 0u);
}

bool nmo_equals_bool32(const void *a, const void *b)
{
    return (*(const uint32_t *)a != 0u) == (*(const uint32_t *)b != 0u);
}

uint32_t nmo_hash_bool32(const void *instance)
{
    return nmo_hash_int32(*(const uint32_t *)instance != 0u ? 1u : 0u);
}

bool nmo_equals_pointer(const void *a, const void *b)
{
    return *(const void *const *)a == *(const void *const *)b;
}

uint32_t nmo_hash_pointer(const void *instance)
{
    uintptr_t v = (uintptr_t)(*(const void *const *)instance);
    return nmo_hash_u64_fold((uint64_t)v);
}

bool nmo_equals_guid(const void *a, const void *b)
{
    return nmo_guid_equals(*(const nmo_guid_t *)a, *(const nmo_guid_t *)b);
}

uint32_t nmo_hash_guid(const void *instance)
{
    return nmo_murmur3_32(instance, sizeof(nmo_guid_t), 0);
}

bool nmo_equals_object_id(const void *a, const void *b)
{
    return *(const nmo_object_id_t *)a == *(const nmo_object_id_t *)b;
}

uint32_t nmo_hash_object_id(const void *instance)
{
    return nmo_hash_int32((uint32_t)(*(const nmo_object_id_t *)instance));
}

NMO_DEFINE_EQ_HASH_BYTES(vector2, nmo_vector2_t)
NMO_DEFINE_EQ_HASH_BYTES(vector3, nmo_vector_t)
NMO_DEFINE_EQ_HASH_BYTES(vector4, nmo_vector4_t)
NMO_DEFINE_EQ_HASH_BYTES(quaternion, nmo_quaternion_t)
NMO_DEFINE_EQ_HASH_BYTES(matrix, nmo_matrix_t)
NMO_DEFINE_EQ_HASH_BYTES(color, nmo_color_t)
NMO_DEFINE_EQ_HASH_BYTES(rect, nmo_rect_t)
NMO_DEFINE_EQ_HASH_BYTES(eulerangles, nmo_eulerangles_t)
NMO_DEFINE_EQ_HASH_BYTES(box, nmo_box_t)

#define NMO_DEFINE_VT_TO_STRING(name, value_to_string_fn) \
    nmo_status_t nmo_vt_to_string_##name( \
        const void *value, const nmo_type_descriptor_t *type, \
        const nmo_type_registry_t *registry, \
        char *buffer, size_t buffer_size, int depth) \
    { \
        (void)type; \
        (void)registry; \
        (void)depth; \
        return (value_to_string_fn)(value, buffer, buffer_size); \
    }

#define NMO_DEFINE_VT_FROM_STRING(name, parse_fn) \
    nmo_status_t nmo_vt_from_string_##name( \
        void *value, const nmo_type_descriptor_t *type, \
        const nmo_type_registry_t *registry, const char *string) \
    { \
        (void)type; \
        return (parse_fn)(value, registry, string); \
    }

/* Hand-written vtable to_string handlers for types with extra args or inline logic */

#define NMO_DEFINE_SIGNED_VT_TO_STRING(name, c_type) \
    nmo_status_t nmo_vt_to_string_##name( \
        const void *value, const nmo_type_descriptor_t *type, \
        const nmo_type_registry_t *registry, \
        char *buffer, size_t buffer_size, int depth) \
    { \
        (void)type; \
        (void)registry; \
        (void)depth; \
        return nmo_format_i64_text( \
            *(const c_type *)value, buffer, buffer_size); \
    }

#define NMO_DEFINE_UNSIGNED_VT_TO_STRING(name, c_type) \
    nmo_status_t nmo_vt_to_string_##name( \
        const void *value, const nmo_type_descriptor_t *type, \
        const nmo_type_registry_t *registry, \
        char *buffer, size_t buffer_size, int depth) \
    { \
        (void)type; \
        (void)registry; \
        (void)depth; \
        return nmo_format_u64_text( \
            *(const c_type *)value, buffer, buffer_size); \
    }

nmo_status_t nmo_vt_to_string_int32(
    const void *value, const nmo_type_descriptor_t *type,
    const nmo_type_registry_t *registry,
    char *buffer, size_t buffer_size, int depth)
{
    (void)type; (void)registry; (void)depth;
    return nmo_type_int_to_string(value, buffer, buffer_size, false);
}
NMO_DEFINE_VT_FROM_STRING(int32, nmo_parse_int32)

NMO_DEFINE_UNSIGNED_VT_TO_STRING(uint32, uint32_t)
NMO_DEFINE_VT_FROM_STRING(uint32, nmo_parse_uint32)

NMO_DEFINE_SIGNED_VT_TO_STRING(int8, int8_t)
NMO_DEFINE_VT_FROM_STRING(int8, nmo_parse_int8)

NMO_DEFINE_UNSIGNED_VT_TO_STRING(uint8, uint8_t)
NMO_DEFINE_VT_FROM_STRING(uint8, nmo_parse_uint8)

NMO_DEFINE_SIGNED_VT_TO_STRING(int16, int16_t)
NMO_DEFINE_VT_FROM_STRING(int16, nmo_parse_int16)

NMO_DEFINE_UNSIGNED_VT_TO_STRING(uint16, uint16_t)
NMO_DEFINE_VT_FROM_STRING(uint16, nmo_parse_uint16)

NMO_DEFINE_SIGNED_VT_TO_STRING(int64, int64_t)
NMO_DEFINE_VT_FROM_STRING(int64, nmo_parse_int64)

NMO_DEFINE_UNSIGNED_VT_TO_STRING(uint64, uint64_t)
NMO_DEFINE_VT_FROM_STRING(uint64, nmo_parse_uint64)

NMO_DEFINE_VT_TO_STRING(float, nmo_type_float_to_string)
NMO_DEFINE_VT_FROM_STRING(float, nmo_parse_float)

nmo_status_t nmo_vt_to_string_double(
    const void *value, const nmo_type_descriptor_t *type,
    const nmo_type_registry_t *registry,
    char *buffer, size_t buffer_size, int depth)
{
    (void)type; (void)registry; (void)depth;
    nmo_format_real_text(*(const double *)value, buffer, buffer_size);
    NMO_RETURN_OK();
}
NMO_DEFINE_VT_FROM_STRING(double, nmo_parse_double)

NMO_DEFINE_VT_TO_STRING(bool, nmo_type_bool_to_string)
NMO_DEFINE_VT_FROM_STRING(bool, nmo_parse_bool)

nmo_status_t nmo_vt_to_string_bool32(
    const void *value, const nmo_type_descriptor_t *type,
    const nmo_type_registry_t *registry,
    char *buffer, size_t buffer_size, int depth)
{
    (void)type; (void)registry; (void)depth;
    nmo_status_t status = nmo_validate_value_to_string_args(
        value, buffer, buffer_size, 6, "Invalid arguments for bool_to_string");
    if (status != NMO_OK) {
        return status;
    }

    snprintf(buffer, buffer_size, *(const uint32_t *)value != 0u ? "true" : "false");
    NMO_RETURN_OK();
}

nmo_status_t nmo_vt_from_string_bool32(
    void *value, const nmo_type_descriptor_t *type,
    const nmo_type_registry_t *registry, const char *string)
{
    (void)type; (void)registry;
    if (!value || !string) {
        NMO_RETURN_ERROR(NMO_ERR_INVALID_ARGUMENT, NMO_SEVERITY_ERROR, "Invalid arguments for bool_from_string");
    }

    bool parsed = false;
    nmo_status_t status = nmo_type_bool_from_string(&parsed, string);
    if (status != NMO_OK) {
        return status;
    }

    *(uint32_t *)value = parsed ? 1u : 0u;
    NMO_RETURN_OK();
}

NMO_DEFINE_VT_TO_STRING(string, nmo_type_string_to_string)
NMO_DEFINE_VT_FROM_STRING(string, nmo_parse_string)

nmo_status_t nmo_vt_to_string_pointer(
    const void *value, const nmo_type_descriptor_t *type,
    const nmo_type_registry_t *registry,
    char *buffer, size_t buffer_size, int depth)
{
    (void)type; (void)registry; (void)depth;
    const void *ptr = *(const void *const *)value;
    if (!ptr) {
        snprintf(buffer, buffer_size, "null");
    } else {
        uintptr_t v = (uintptr_t)ptr;
        snprintf(buffer, buffer_size, "0x%llX", (unsigned long long)v);
    }
    NMO_RETURN_OK();
}
NMO_DEFINE_VT_FROM_STRING(pointer, nmo_parse_pointer)

nmo_status_t nmo_vt_to_string_guid(
    const void *value, const nmo_type_descriptor_t *type,
    const nmo_type_registry_t *registry,
    char *buffer, size_t buffer_size, int depth)
{
    (void)type; (void)registry; (void)depth;
    int wrote = nmo_guid_format(*(const nmo_guid_t *)value, buffer, buffer_size);
    if (wrote < 0) {
        NMO_RETURN_ERROR(NMO_ERR_BUFFER_OVERRUN, NMO_SEVERITY_ERROR, "Buffer too small");
    }
    NMO_RETURN_OK();
}
NMO_DEFINE_VT_FROM_STRING(guid, nmo_parse_guid)

nmo_status_t nmo_vt_to_string_object_id(
    const void *value, const nmo_type_descriptor_t *type,
    const nmo_type_registry_t *registry,
    char *buffer, size_t buffer_size, int depth)
{
    (void)type; (void)registry; (void)depth;
    return nmo_type_object_id_to_string(value, buffer, buffer_size);
}
NMO_DEFINE_VT_FROM_STRING(object_id, nmo_parse_object_id_value)

NMO_DEFINE_VT_TO_STRING(vector2, nmo_type_vector2_to_string)
NMO_DEFINE_VT_FROM_STRING(vector2, nmo_parse_vector2)

NMO_DEFINE_VT_TO_STRING(vector3, nmo_type_vector3_to_string)
NMO_DEFINE_VT_FROM_STRING(vector3, nmo_parse_vector3)

NMO_DEFINE_VT_TO_STRING(vector4, nmo_type_vector4_to_string)
NMO_DEFINE_VT_FROM_STRING(vector4, nmo_parse_vector4)

NMO_DEFINE_VT_TO_STRING(quaternion, nmo_type_quaternion_to_string)
NMO_DEFINE_VT_FROM_STRING(quaternion, nmo_parse_quaternion)

NMO_DEFINE_VT_TO_STRING(matrix, nmo_type_matrix_to_string)
NMO_DEFINE_VT_FROM_STRING(matrix, nmo_parse_matrix)

NMO_DEFINE_VT_TO_STRING(color, nmo_type_color_to_string)
NMO_DEFINE_VT_FROM_STRING(color, nmo_parse_color)

nmo_status_t nmo_vt_to_string_rect(
    const void *value, const nmo_type_descriptor_t *type,
    const nmo_type_registry_t *registry,
    char *buffer, size_t buffer_size, int depth)
{
    (void)type; (void)registry; (void)depth;
    const nmo_rect_t *r = (const nmo_rect_t *)value;
    const float values[4] = { r->left, r->top, r->right, r->bottom };
    nmo_format_float_tuple_text(values, 4, buffer, buffer_size);
    NMO_RETURN_OK();
}
NMO_DEFINE_VT_FROM_STRING(rect, nmo_parse_rect)

nmo_status_t nmo_vt_to_string_eulerangles(
    const void *value, const nmo_type_descriptor_t *type,
    const nmo_type_registry_t *registry,
    char *buffer, size_t buffer_size, int depth)
{
    (void)type; (void)registry; (void)depth;
    const nmo_eulerangles_t *e = (const nmo_eulerangles_t *)value;
    const float values[3] = { e->x, e->y, e->z };
    nmo_format_float_tuple_text(values, 3, buffer, buffer_size);
    NMO_RETURN_OK();
}
NMO_DEFINE_VT_FROM_STRING(eulerangles, nmo_parse_eulerangles)

nmo_status_t nmo_vt_to_string_box(
    const void *value, const nmo_type_descriptor_t *type,
    const nmo_type_registry_t *registry,
    char *buffer, size_t buffer_size, int depth)
{
    (void)type; (void)registry; (void)depth;
    const nmo_box_t *b = (const nmo_box_t *)value;
    snprintf(buffer, buffer_size,
             "((%.6g, %.6g, %.6g), (%.6g, %.6g, %.6g))",
             b->min.x, b->min.y, b->min.z,
             b->max.x, b->max.y, b->max.z);
    NMO_RETURN_OK();
}
NMO_DEFINE_VT_FROM_STRING(box, nmo_parse_box)
