/**
 * @file type_registry_virtools.c
 * @brief Register Virtools CK2 parameter types and operation types
 *
 * Bulk-registers 142 parameter types and 183 operation types exported from
 * the Virtools runtime via VirtoolsDataExporter. Types already registered
 * by the core are skipped.
 *
 * Data source: data/virtools_data.json
 * Generated by: tools/scripts/gen_type_registry_data.py
 */

#include "type/nmo_type_system.h"
#include "core/nmo_guid.h"
#include "core/nmo_error.h"

#include <string.h>

/* Include the generated registration functions */
#include "type_registry_virtools_data.inc"

nmo_status_t nmo_register_virtools_types(nmo_type_registry_t *registry) {
    if (!registry) {
        NMO_RETURN_ERROR(NMO_ERR_INVALID_ARGUMENT, NMO_SEVERITY_ERROR,
                         "NULL registry");
    }

    nmo_status_t st;

    st = register_virtools_param_types(registry);
    if (st != NMO_OK) return st;

    st = register_virtools_operation_types(registry);
    if (st != NMO_OK) return st;

    return NMO_OK;
}
