/**
 * @file type_registry_virtools.c
 * @brief Register CK2 parameter types and operation types from Virtools data
 *
 * Data source: data/virtools_parameter_types.json, data/virtools_operation_types.json
 * Generated by: tools/scripts/gen_virtools_data.py
 */

#include "type/nmo_type_virtools.h"
#include "type/nmo_type_system.h"
#include "core/nmo_guid.h"
#include "core/nmo_error.h"

#include <string.h>

#include "virtools_param_types.inc"
#include "virtools_operations.inc"

nmo_status_t nmo_register_virtools_types(nmo_type_registry_t *registry) {
    if (!registry) {
        NMO_RETURN_ERROR(NMO_ERR_INVALID_ARGUMENT, NMO_SEVERITY_ERROR,
                         "NULL registry");
    }

    nmo_status_t st;

    st = register_virtools_param_types(registry);
    if (st != NMO_OK) return st;

    st = register_virtools_operation_types(registry);
    if (st != NMO_OK) return st;

    return NMO_OK;
}
