/**
 * @file nmo_builtin_type_guids.h
 * @brief Built-in type GUID definitions (field + builtin parameter types)
 *
 * Centralized GUIDs for:
 * - Reflection field primitive/composite types (NMO_GUID_FIELD_*)
 * - Builtin parameter types used by operation system (NMO_TYPE_GUID_*)
 */

#ifndef NMO_BUILTIN_TYPE_GUIDS_H
#define NMO_BUILTIN_TYPE_GUIDS_H

#include "core/nmo_guid.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ============================================================================
 * Field Type GUIDs (Reflection)
 * ============================================================================ */

/* Encoded GUID layout for field types:
 * - d1: 0x4E4D4F00 ('NMO\0') | class_id
 * - d2: [size_bits:16][sub_id:16]
 * This makes class/size visible and stable while keeping GUIDs compact.
 */
#define NMO_GUID_FIELD_BASE                 0x4E4D4F00u
#define NMO_GUID_FIELD_CLASS_VOID           0x00u
#define NMO_GUID_FIELD_CLASS_BOOL           0x01u
#define NMO_GUID_FIELD_CLASS_INT            0x02u
#define NMO_GUID_FIELD_CLASS_UINT           0x03u
#define NMO_GUID_FIELD_CLASS_FLOAT          0x04u
#define NMO_GUID_FIELD_CLASS_STRING         0x05u
#define NMO_GUID_FIELD_CLASS_POINTER        0x06u
#define NMO_GUID_FIELD_CLASS_OBJECT_ID      0x07u
#define NMO_GUID_FIELD_CLASS_COMPOSITE      0x08u
#define NMO_GUID_FIELD_CLASS_CONTAINER      0x09u
#define NMO_GUID_FIELD_BASE_MASK            0xFFFFFF00u

#define NMO_GUID_FIELD_MAKE_D1(_class_id)   (NMO_GUID_FIELD_BASE | (_class_id))
#define NMO_GUID_FIELD_MAKE_D2(_size_bits, _sub_id) ((uint32_t)(((_size_bits) << 16) | (_sub_id)))

/* Primitive type GUIDs - brace form for static init (use in struct initializers) */
#define NMO_GUID_FIELD_VOID       NMO_GUID_FIELD_VOID_VAL
#define NMO_GUID_FIELD_BOOL       NMO_GUID_FIELD_BOOL_VAL
#define NMO_GUID_FIELD_INT8       NMO_GUID_FIELD_INT8_VAL
#define NMO_GUID_FIELD_UINT8      NMO_GUID_FIELD_UINT8_VAL
#define NMO_GUID_FIELD_INT16      NMO_GUID_FIELD_INT16_VAL
#define NMO_GUID_FIELD_UINT16     NMO_GUID_FIELD_UINT16_VAL
#define NMO_GUID_FIELD_INT32      NMO_GUID_FIELD_INT32_VAL
#define NMO_GUID_FIELD_UINT32     NMO_GUID_FIELD_UINT32_VAL
#define NMO_GUID_FIELD_INT64      NMO_GUID_FIELD_INT64_VAL
#define NMO_GUID_FIELD_UINT64     NMO_GUID_FIELD_UINT64_VAL
#define NMO_GUID_FIELD_FLOAT      NMO_GUID_FIELD_FLOAT_VAL
#define NMO_GUID_FIELD_DOUBLE     NMO_GUID_FIELD_DOUBLE_VAL
#define NMO_GUID_FIELD_STRING     NMO_GUID_FIELD_STRING_VAL
#define NMO_GUID_FIELD_POINTER    NMO_GUID_FIELD_POINTER_VAL
#define NMO_GUID_FIELD_OBJECT_ID  NMO_GUID_FIELD_OBJECT_ID_VAL

/* Composite type GUIDs - brace form */
#define NMO_GUID_FIELD_VECTOR2    NMO_GUID_FIELD_VECTOR2_VAL
#define NMO_GUID_FIELD_VECTOR3    NMO_GUID_FIELD_VECTOR3_VAL
#define NMO_GUID_FIELD_VECTOR4    NMO_GUID_FIELD_VECTOR4_VAL
#define NMO_GUID_FIELD_MATRIX     NMO_GUID_FIELD_MATRIX_VAL
#define NMO_GUID_FIELD_QUATERNION NMO_GUID_FIELD_QUATERNION_VAL
#define NMO_GUID_FIELD_RECT       NMO_GUID_FIELD_RECT_VAL
#define NMO_GUID_FIELD_COLOR      NMO_GUID_FIELD_COLOR_VAL
#define NMO_GUID_FIELD_GUID       NMO_GUID_FIELD_GUID_VAL
#define NMO_GUID_FIELD_CHUNK      NMO_GUID_FIELD_CHUNK_VAL
#define NMO_GUID_FIELD_ARRAY      NMO_GUID_FIELD_ARRAY_VAL

/* Initializer form for static contexts */
#define NMO_GUID_FIELD_VOID_VAL       {NMO_GUID_FIELD_MAKE_D1(NMO_GUID_FIELD_CLASS_VOID), NMO_GUID_FIELD_MAKE_D2(0, 0)}
#define NMO_GUID_FIELD_BOOL_VAL       {NMO_GUID_FIELD_MAKE_D1(NMO_GUID_FIELD_CLASS_BOOL), NMO_GUID_FIELD_MAKE_D2(1, 0)}
#define NMO_GUID_FIELD_INT8_VAL       {NMO_GUID_FIELD_MAKE_D1(NMO_GUID_FIELD_CLASS_INT), NMO_GUID_FIELD_MAKE_D2(8, 0)}
#define NMO_GUID_FIELD_UINT8_VAL      {NMO_GUID_FIELD_MAKE_D1(NMO_GUID_FIELD_CLASS_UINT), NMO_GUID_FIELD_MAKE_D2(8, 0)}
#define NMO_GUID_FIELD_INT16_VAL      {NMO_GUID_FIELD_MAKE_D1(NMO_GUID_FIELD_CLASS_INT), NMO_GUID_FIELD_MAKE_D2(16, 0)}
#define NMO_GUID_FIELD_UINT16_VAL     {NMO_GUID_FIELD_MAKE_D1(NMO_GUID_FIELD_CLASS_UINT), NMO_GUID_FIELD_MAKE_D2(16, 0)}
#define NMO_GUID_FIELD_INT32_VAL      {NMO_GUID_FIELD_MAKE_D1(NMO_GUID_FIELD_CLASS_INT), NMO_GUID_FIELD_MAKE_D2(32, 0)}
#define NMO_GUID_FIELD_UINT32_VAL     {NMO_GUID_FIELD_MAKE_D1(NMO_GUID_FIELD_CLASS_UINT), NMO_GUID_FIELD_MAKE_D2(32, 0)}
#define NMO_GUID_FIELD_INT64_VAL      {NMO_GUID_FIELD_MAKE_D1(NMO_GUID_FIELD_CLASS_INT), NMO_GUID_FIELD_MAKE_D2(64, 0)}
#define NMO_GUID_FIELD_UINT64_VAL     {NMO_GUID_FIELD_MAKE_D1(NMO_GUID_FIELD_CLASS_UINT), NMO_GUID_FIELD_MAKE_D2(64, 0)}
#define NMO_GUID_FIELD_FLOAT_VAL      {NMO_GUID_FIELD_MAKE_D1(NMO_GUID_FIELD_CLASS_FLOAT), NMO_GUID_FIELD_MAKE_D2(32, 0)}
#define NMO_GUID_FIELD_DOUBLE_VAL     {NMO_GUID_FIELD_MAKE_D1(NMO_GUID_FIELD_CLASS_FLOAT), NMO_GUID_FIELD_MAKE_D2(64, 0)}
#define NMO_GUID_FIELD_STRING_VAL     {NMO_GUID_FIELD_MAKE_D1(NMO_GUID_FIELD_CLASS_STRING), NMO_GUID_FIELD_MAKE_D2(0, 1)}
#define NMO_GUID_FIELD_POINTER_VAL    {NMO_GUID_FIELD_MAKE_D1(NMO_GUID_FIELD_CLASS_POINTER), NMO_GUID_FIELD_MAKE_D2(0, 1)}
#define NMO_GUID_FIELD_OBJECT_ID_VAL  {NMO_GUID_FIELD_MAKE_D1(NMO_GUID_FIELD_CLASS_OBJECT_ID), NMO_GUID_FIELD_MAKE_D2(0, 1)}
#define NMO_GUID_FIELD_VECTOR2_VAL    {NMO_GUID_FIELD_MAKE_D1(NMO_GUID_FIELD_CLASS_COMPOSITE), NMO_GUID_FIELD_MAKE_D2(64, 1)}
#define NMO_GUID_FIELD_VECTOR3_VAL    {NMO_GUID_FIELD_MAKE_D1(NMO_GUID_FIELD_CLASS_COMPOSITE), NMO_GUID_FIELD_MAKE_D2(96, 2)}
#define NMO_GUID_FIELD_VECTOR4_VAL    {NMO_GUID_FIELD_MAKE_D1(NMO_GUID_FIELD_CLASS_COMPOSITE), NMO_GUID_FIELD_MAKE_D2(128, 3)}
#define NMO_GUID_FIELD_MATRIX_VAL     {NMO_GUID_FIELD_MAKE_D1(NMO_GUID_FIELD_CLASS_COMPOSITE), NMO_GUID_FIELD_MAKE_D2(512, 4)}
#define NMO_GUID_FIELD_QUATERNION_VAL {NMO_GUID_FIELD_MAKE_D1(NMO_GUID_FIELD_CLASS_COMPOSITE), NMO_GUID_FIELD_MAKE_D2(128, 5)}
#define NMO_GUID_FIELD_RECT_VAL       {NMO_GUID_FIELD_MAKE_D1(NMO_GUID_FIELD_CLASS_COMPOSITE), NMO_GUID_FIELD_MAKE_D2(128, 6)}
#define NMO_GUID_FIELD_COLOR_VAL      {NMO_GUID_FIELD_MAKE_D1(NMO_GUID_FIELD_CLASS_COMPOSITE), NMO_GUID_FIELD_MAKE_D2(128, 7)}
#define NMO_GUID_FIELD_GUID_VAL       {NMO_GUID_FIELD_MAKE_D1(NMO_GUID_FIELD_CLASS_COMPOSITE), NMO_GUID_FIELD_MAKE_D2(128, 8)}
#define NMO_GUID_FIELD_CHUNK_VAL      {NMO_GUID_FIELD_MAKE_D1(NMO_GUID_FIELD_CLASS_CONTAINER), NMO_GUID_FIELD_MAKE_D2(0, 1)}
#define NMO_GUID_FIELD_ARRAY_VAL      {NMO_GUID_FIELD_MAKE_D1(NMO_GUID_FIELD_CLASS_CONTAINER), NMO_GUID_FIELD_MAKE_D2(0, 2)}

/* ============================================================================
 * Builtin Parameter Type GUIDs (Operation System)
 * ============================================================================ */

#define NMO_TYPE_GUID_BASE                0x4E4D4F54u /* 'NMOT' */
#define NMO_TYPE_GUID_MAKE_D1(_class_id)  (NMO_TYPE_GUID_BASE | (_class_id))

#define NMO_TYPE_GUID_INT        ((nmo_guid_t){NMO_TYPE_GUID_MAKE_D1(NMO_GUID_FIELD_CLASS_INT), NMO_GUID_FIELD_MAKE_D2(32, 0)})
#define NMO_TYPE_GUID_FLOAT      ((nmo_guid_t){NMO_TYPE_GUID_MAKE_D1(NMO_GUID_FIELD_CLASS_FLOAT), NMO_GUID_FIELD_MAKE_D2(32, 0)})
#define NMO_TYPE_GUID_BOOL       ((nmo_guid_t){NMO_TYPE_GUID_MAKE_D1(NMO_GUID_FIELD_CLASS_BOOL), NMO_GUID_FIELD_MAKE_D2(1, 0)})
#define NMO_TYPE_GUID_VECTOR2    ((nmo_guid_t){NMO_TYPE_GUID_MAKE_D1(NMO_GUID_FIELD_CLASS_COMPOSITE), NMO_GUID_FIELD_MAKE_D2(64, 1)})
#define NMO_TYPE_GUID_VECTOR3    ((nmo_guid_t){NMO_TYPE_GUID_MAKE_D1(NMO_GUID_FIELD_CLASS_COMPOSITE), NMO_GUID_FIELD_MAKE_D2(96, 2)})
#define NMO_TYPE_GUID_VECTOR4    ((nmo_guid_t){NMO_TYPE_GUID_MAKE_D1(NMO_GUID_FIELD_CLASS_COMPOSITE), NMO_GUID_FIELD_MAKE_D2(128, 3)})
#define NMO_TYPE_GUID_QUATERNION ((nmo_guid_t){NMO_TYPE_GUID_MAKE_D1(NMO_GUID_FIELD_CLASS_COMPOSITE), NMO_GUID_FIELD_MAKE_D2(128, 5)})
#define NMO_TYPE_GUID_MATRIX     ((nmo_guid_t){NMO_TYPE_GUID_MAKE_D1(NMO_GUID_FIELD_CLASS_COMPOSITE), NMO_GUID_FIELD_MAKE_D2(512, 4)})
#define NMO_TYPE_GUID_COLOR      ((nmo_guid_t){NMO_TYPE_GUID_MAKE_D1(NMO_GUID_FIELD_CLASS_COMPOSITE), NMO_GUID_FIELD_MAKE_D2(128, 7)})
#define NMO_TYPE_GUID_RECT       ((nmo_guid_t){NMO_TYPE_GUID_MAKE_D1(NMO_GUID_FIELD_CLASS_COMPOSITE), NMO_GUID_FIELD_MAKE_D2(128, 6)})
#define NMO_TYPE_GUID_DOUBLE     ((nmo_guid_t){NMO_TYPE_GUID_MAKE_D1(NMO_GUID_FIELD_CLASS_FLOAT), NMO_GUID_FIELD_MAKE_D2(64, 0)})
#define NMO_TYPE_GUID_INT8       ((nmo_guid_t){NMO_TYPE_GUID_MAKE_D1(NMO_GUID_FIELD_CLASS_INT), NMO_GUID_FIELD_MAKE_D2(8, 0)})
#define NMO_TYPE_GUID_UINT8      ((nmo_guid_t){NMO_TYPE_GUID_MAKE_D1(NMO_GUID_FIELD_CLASS_UINT), NMO_GUID_FIELD_MAKE_D2(8, 0)})
#define NMO_TYPE_GUID_INT16      ((nmo_guid_t){NMO_TYPE_GUID_MAKE_D1(NMO_GUID_FIELD_CLASS_INT), NMO_GUID_FIELD_MAKE_D2(16, 0)})
#define NMO_TYPE_GUID_UINT16     ((nmo_guid_t){NMO_TYPE_GUID_MAKE_D1(NMO_GUID_FIELD_CLASS_UINT), NMO_GUID_FIELD_MAKE_D2(16, 0)})
#define NMO_TYPE_GUID_UINT32     ((nmo_guid_t){NMO_TYPE_GUID_MAKE_D1(NMO_GUID_FIELD_CLASS_UINT), NMO_GUID_FIELD_MAKE_D2(32, 0)})
#define NMO_TYPE_GUID_STRING     ((nmo_guid_t){NMO_TYPE_GUID_MAKE_D1(NMO_GUID_FIELD_CLASS_STRING), NMO_GUID_FIELD_MAKE_D2(0, 1)})
#define NMO_TYPE_GUID_INT64      ((nmo_guid_t){NMO_TYPE_GUID_MAKE_D1(NMO_GUID_FIELD_CLASS_INT), NMO_GUID_FIELD_MAKE_D2(64, 0)})
#define NMO_TYPE_GUID_UINT64     ((nmo_guid_t){NMO_TYPE_GUID_MAKE_D1(NMO_GUID_FIELD_CLASS_UINT), NMO_GUID_FIELD_MAKE_D2(64, 0)})
#define NMO_TYPE_GUID_POINTER    ((nmo_guid_t){NMO_TYPE_GUID_MAKE_D1(NMO_GUID_FIELD_CLASS_POINTER), NMO_GUID_FIELD_MAKE_D2(0, 1)})
#define NMO_TYPE_GUID_GUID       ((nmo_guid_t){NMO_TYPE_GUID_MAKE_D1(NMO_GUID_FIELD_CLASS_COMPOSITE), NMO_GUID_FIELD_MAKE_D2(128, 8)})
#define NMO_TYPE_GUID_OBJECT_ID  ((nmo_guid_t){NMO_TYPE_GUID_MAKE_D1(NMO_GUID_FIELD_CLASS_OBJECT_ID), NMO_GUID_FIELD_MAKE_D2(0, 1)})
#define NMO_TYPE_GUID_CHUNK      ((nmo_guid_t){NMO_TYPE_GUID_MAKE_D1(NMO_GUID_FIELD_CLASS_CONTAINER), NMO_GUID_FIELD_MAKE_D2(0, 1)})

/* Initializer-friendly forms for static const arrays */
#define NMO_TYPE_GUID_INT_INIT        {NMO_TYPE_GUID_MAKE_D1(NMO_GUID_FIELD_CLASS_INT), NMO_GUID_FIELD_MAKE_D2(32, 0)}
#define NMO_TYPE_GUID_FLOAT_INIT      {NMO_TYPE_GUID_MAKE_D1(NMO_GUID_FIELD_CLASS_FLOAT), NMO_GUID_FIELD_MAKE_D2(32, 0)}
#define NMO_TYPE_GUID_BOOL_INIT       {NMO_TYPE_GUID_MAKE_D1(NMO_GUID_FIELD_CLASS_BOOL), NMO_GUID_FIELD_MAKE_D2(1, 0)}
#define NMO_TYPE_GUID_VECTOR2_INIT    {NMO_TYPE_GUID_MAKE_D1(NMO_GUID_FIELD_CLASS_COMPOSITE), NMO_GUID_FIELD_MAKE_D2(64, 1)}
#define NMO_TYPE_GUID_VECTOR3_INIT    {NMO_TYPE_GUID_MAKE_D1(NMO_GUID_FIELD_CLASS_COMPOSITE), NMO_GUID_FIELD_MAKE_D2(96, 2)}
#define NMO_TYPE_GUID_VECTOR4_INIT    {NMO_TYPE_GUID_MAKE_D1(NMO_GUID_FIELD_CLASS_COMPOSITE), NMO_GUID_FIELD_MAKE_D2(128, 3)}
#define NMO_TYPE_GUID_QUATERNION_INIT {NMO_TYPE_GUID_MAKE_D1(NMO_GUID_FIELD_CLASS_COMPOSITE), NMO_GUID_FIELD_MAKE_D2(128, 5)}
#define NMO_TYPE_GUID_MATRIX_INIT     {NMO_TYPE_GUID_MAKE_D1(NMO_GUID_FIELD_CLASS_COMPOSITE), NMO_GUID_FIELD_MAKE_D2(512, 4)}
#define NMO_TYPE_GUID_COLOR_INIT      {NMO_TYPE_GUID_MAKE_D1(NMO_GUID_FIELD_CLASS_COMPOSITE), NMO_GUID_FIELD_MAKE_D2(128, 7)}
#define NMO_TYPE_GUID_RECT_INIT       {NMO_TYPE_GUID_MAKE_D1(NMO_GUID_FIELD_CLASS_COMPOSITE), NMO_GUID_FIELD_MAKE_D2(128, 6)}
#define NMO_TYPE_GUID_DOUBLE_INIT     {NMO_TYPE_GUID_MAKE_D1(NMO_GUID_FIELD_CLASS_FLOAT), NMO_GUID_FIELD_MAKE_D2(64, 0)}
#define NMO_TYPE_GUID_INT8_INIT       {NMO_TYPE_GUID_MAKE_D1(NMO_GUID_FIELD_CLASS_INT), NMO_GUID_FIELD_MAKE_D2(8, 0)}
#define NMO_TYPE_GUID_UINT8_INIT      {NMO_TYPE_GUID_MAKE_D1(NMO_GUID_FIELD_CLASS_UINT), NMO_GUID_FIELD_MAKE_D2(8, 0)}
#define NMO_TYPE_GUID_INT16_INIT      {NMO_TYPE_GUID_MAKE_D1(NMO_GUID_FIELD_CLASS_INT), NMO_GUID_FIELD_MAKE_D2(16, 0)}
#define NMO_TYPE_GUID_UINT16_INIT     {NMO_TYPE_GUID_MAKE_D1(NMO_GUID_FIELD_CLASS_UINT), NMO_GUID_FIELD_MAKE_D2(16, 0)}
#define NMO_TYPE_GUID_UINT32_INIT     {NMO_TYPE_GUID_MAKE_D1(NMO_GUID_FIELD_CLASS_UINT), NMO_GUID_FIELD_MAKE_D2(32, 0)}
#define NMO_TYPE_GUID_STRING_INIT     {NMO_TYPE_GUID_MAKE_D1(NMO_GUID_FIELD_CLASS_STRING), NMO_GUID_FIELD_MAKE_D2(0, 1)}
#define NMO_TYPE_GUID_INT64_INIT      {NMO_TYPE_GUID_MAKE_D1(NMO_GUID_FIELD_CLASS_INT), NMO_GUID_FIELD_MAKE_D2(64, 0)}
#define NMO_TYPE_GUID_UINT64_INIT     {NMO_TYPE_GUID_MAKE_D1(NMO_GUID_FIELD_CLASS_UINT), NMO_GUID_FIELD_MAKE_D2(64, 0)}
#define NMO_TYPE_GUID_POINTER_INIT    {NMO_TYPE_GUID_MAKE_D1(NMO_GUID_FIELD_CLASS_POINTER), NMO_GUID_FIELD_MAKE_D2(0, 1)}
#define NMO_TYPE_GUID_GUID_INIT       {NMO_TYPE_GUID_MAKE_D1(NMO_GUID_FIELD_CLASS_COMPOSITE), NMO_GUID_FIELD_MAKE_D2(128, 8)}
#define NMO_TYPE_GUID_OBJECT_ID_INIT  {NMO_TYPE_GUID_MAKE_D1(NMO_GUID_FIELD_CLASS_OBJECT_ID), NMO_GUID_FIELD_MAKE_D2(0, 1)}
#define NMO_TYPE_GUID_CHUNK_INIT      {NMO_TYPE_GUID_MAKE_D1(NMO_GUID_FIELD_CLASS_CONTAINER), NMO_GUID_FIELD_MAKE_D2(0, 1)}

NMO_API int nmo_guid_is_field_type(nmo_guid_t guid);
NMO_API nmo_guid_t nmo_guid_field_to_type(nmo_guid_t guid);

#ifdef __cplusplus
}
#endif

#endif /* NMO_BUILTIN_TYPE_GUIDS_H */
