/**
 * @file nmo_type_guid_compat.h
 * @brief Temporary compatibility aliases for legacy NMO_TYPE_GUID_* names.
 *
 * These aliases map the legacy NMO_TYPE_GUID_* identifiers to canonical
 * CKPGUID_* values. This header exists to stage the transition away from
 * NMO_TYPE_GUID_* usage and will be removed once all call sites migrate.
 */

#ifndef NMO_TYPE_GUID_COMPAT_H
#define NMO_TYPE_GUID_COMPAT_H

#ifdef __cplusplus
extern "C" {
#endif

/* Core scalar types */
#define NMO_TYPE_GUID_BOOL       CKPGUID_BOOL
#define NMO_TYPE_GUID_INT        CKPGUID_INT
#define NMO_TYPE_GUID_FLOAT      CKPGUID_FLOAT
#define NMO_TYPE_GUID_STRING     CKPGUID_STRING
#define NMO_TYPE_GUID_DOUBLE     CKPGUID_DOUBLE
#define NMO_TYPE_GUID_UINT32     CKPGUID_UINT32
#define NMO_TYPE_GUID_INT8       CKPGUID_INT8
#define NMO_TYPE_GUID_UINT8      CKPGUID_UINT8
#define NMO_TYPE_GUID_INT16      CKPGUID_INT16
#define NMO_TYPE_GUID_UINT16     CKPGUID_UINT16
#define NMO_TYPE_GUID_INT64      CKPGUID_INT64
#define NMO_TYPE_GUID_UINT64     CKPGUID_UINT64
#define NMO_TYPE_GUID_POINTER    CKPGUID_POINTER
#define NMO_TYPE_GUID_GUID       CKPGUID_GUID
#define NMO_TYPE_GUID_OBJECT_ID  CKPGUID_ID

/* Math and geometry types */
#define NMO_TYPE_GUID_VECTOR2    CKPGUID_2DVECTOR
#define NMO_TYPE_GUID_VECTOR3    CKPGUID_VECTOR
#define NMO_TYPE_GUID_VECTOR4    CKPGUID_VECTOR4
#define NMO_TYPE_GUID_QUATERNION CKPGUID_QUATERNION
#define NMO_TYPE_GUID_MATRIX     CKPGUID_MATRIX
#define NMO_TYPE_GUID_COLOR      CKPGUID_COLOR
#define NMO_TYPE_GUID_RECT       CKPGUID_RECT

/* Container types */
#define NMO_TYPE_GUID_CHUNK      CKPGUID_STATECHUNK

/* Initializer aliases for static tables */
#define NMO_TYPE_GUID_BOOL_INIT       NMO_TYPE_GUID_BOOL
#define NMO_TYPE_GUID_INT_INIT        NMO_TYPE_GUID_INT
#define NMO_TYPE_GUID_FLOAT_INIT      NMO_TYPE_GUID_FLOAT
#define NMO_TYPE_GUID_STRING_INIT     NMO_TYPE_GUID_STRING
#define NMO_TYPE_GUID_DOUBLE_INIT     NMO_TYPE_GUID_DOUBLE
#define NMO_TYPE_GUID_UINT32_INIT     NMO_TYPE_GUID_UINT32
#define NMO_TYPE_GUID_INT8_INIT       NMO_TYPE_GUID_INT8
#define NMO_TYPE_GUID_UINT8_INIT      NMO_TYPE_GUID_UINT8
#define NMO_TYPE_GUID_INT16_INIT      NMO_TYPE_GUID_INT16
#define NMO_TYPE_GUID_UINT16_INIT     NMO_TYPE_GUID_UINT16
#define NMO_TYPE_GUID_INT64_INIT      NMO_TYPE_GUID_INT64
#define NMO_TYPE_GUID_UINT64_INIT     NMO_TYPE_GUID_UINT64
#define NMO_TYPE_GUID_POINTER_INIT    NMO_TYPE_GUID_POINTER
#define NMO_TYPE_GUID_GUID_INIT       NMO_TYPE_GUID_GUID
#define NMO_TYPE_GUID_OBJECT_ID_INIT  NMO_TYPE_GUID_OBJECT_ID
#define NMO_TYPE_GUID_VECTOR2_INIT    NMO_TYPE_GUID_VECTOR2
#define NMO_TYPE_GUID_VECTOR3_INIT    NMO_TYPE_GUID_VECTOR3
#define NMO_TYPE_GUID_VECTOR4_INIT    NMO_TYPE_GUID_VECTOR4
#define NMO_TYPE_GUID_QUATERNION_INIT NMO_TYPE_GUID_QUATERNION
#define NMO_TYPE_GUID_MATRIX_INIT     NMO_TYPE_GUID_MATRIX
#define NMO_TYPE_GUID_COLOR_INIT      NMO_TYPE_GUID_COLOR
#define NMO_TYPE_GUID_RECT_INIT       NMO_TYPE_GUID_RECT
#define NMO_TYPE_GUID_CHUNK_INIT      NMO_TYPE_GUID_CHUNK

#ifdef __cplusplus
}
#endif

#endif /* NMO_TYPE_GUID_COMPAT_H */
