# PowerShell completion for nmo - Virtools NMO file tool
# Auto-generated by tools/scripts/gen_completions.py; do not edit by hand.


$_nmo_groups = @{
    'file' = @('info', 'i', 'header', 'hdr', 'stats', 'st', 'classes', 'cls', 'plugins', 'pl', 'space', 'sp')
    'chunk' = @('list', 'ls', 'tree', 't', 'show', 's', 'find', 'f')
    'object' = @('list', 'ls', 'tree', 't', 'show', 's', 'find', 'f', 'refs', 'r', 'rename', 'ren', 'export', 'x', 'impact', 'imp', 'orphans', 'orp', 'cycles', 'cyc', 'delete', 'del', 'create', 'copy', 'cp', 'import', 'graph', 'gr', 'set-field', 'sf', 'list-fields', 'lf')
    'behavior' = @('list', 'ls', 'stats', 'st', 'show', 's', 'graph', 'g', 'graph-boundary', 'replace-bb', 'fold', 'fold-candidates', 'dump', 'd', 'find', 'f', 'trace', 'tr', 'add-link', 'remove-link', 'interface', 'iface')
    'patch' = @('apply', 'diff')
    'parameter' = @('list', 'ls', 'show', 's', 'dump', 'd', 'set')
    'script' = @('graph', 'g', 'run', 'node', 'io', 'link', 'param', 'op')
    'resource' = @('list', 'ls', 'show', 's', 'extract', 'x', 'import', 'imp', 'replace', 'rep', 'remove', 'rm', 'info')
    'texture' = @('list', 'ls', 'show', 's', 'extract', 'x', 'replace', 'rep')
    'data' = @('list', 'ls', 'show', 's', 'dump', 'd', 'set-cell', 'sc')
    'scene' = @('list', 'ls', 'show', 's', 'set')
    'entity' = @('list', 'ls', 'show', 's', 'set-position', 'sp', 'set-parent', 'set-camera', 'sc', 'set-light', 'sl')
    'material' = @('list', 'ls', 'show', 's', 'set')
    'mesh' = @('list', 'ls', 'show', 's', 'export', 'x', 'import', 'imp')
    'animation' = @('list', 'ls', 'show', 's', 'keys', 'k', 'export', 'x', 'import', 'imp')
    'type' = @('list', 'ls', 'show', 's', 'class-tree', 'ct')
    'validate' = @('all', 'a', 'structure', 'st', 'references', 'ref', 'resources', 'res', 'orphans', 'orp')
    'convert' = @('copy', 'cp', 'version', 'v', 'strip', 'st', 'merge', 'm', 'export', 'x')
    'diff' = @('summary', 's', 'objects', 'obj', 'chunks', 'ch', 'full', 'f')
    'extension' = @('list', 'ls', 'load', 'ld', 'info', 'i', 'check', 'ch')
    'completion' = @('bash', 'fish', 'zsh', 'powershell', 'ps1')
    'debug' = @('load-phases', 'lp', 'chunks', 'ch', 'objects', 'obj', 'export', 'x', 'probe')
    'repl' = @('start')
}
$_nmo_sub_actions = @{
    'behavior/interface' = @('show', 'set-pos', 'fold', 'unfold', 'set-color', 'canonicalize', 'add-comment', 'remove-comment', 'set-comment-text', 'move-comment', 'set-comment-style', 'add-point', 'clear-points', 'remove-point', 'move-point', 'set-link-highlight', 'move-op', 'move-param', 'set-param-style', 'resize', 'set-expand', 'set-viewport', 'set-graph-io', 'translate')
    'behavior/iface' = @('show', 'set-pos', 'fold', 'unfold', 'set-color', 'canonicalize', 'add-comment', 'remove-comment', 'set-comment-text', 'move-comment', 'set-comment-style', 'add-point', 'clear-points', 'remove-point', 'move-point', 'set-link-highlight', 'move-op', 'move-param', 'set-param-style', 'resize', 'set-expand', 'set-viewport', 'set-graph-io', 'translate')
}
$_nmo_aliases = @{
    'f' = 'file'
    'ch' = 'chunk'
    'obj' = 'object'
    'beh' = 'behavior'
    'param' = 'parameter'
    'res' = 'resource'
    'tex' = 'texture'
    'da' = 'data'
    'sc' = 'scene'
    'ent' = 'entity'
    'mat' = 'material'
    'm' = 'mesh'
    'anim' = 'animation'
    't' = 'type'
    'val' = 'validate'
    'conv' = 'convert'
    'd' = 'diff'
    'ext' = 'extension'
    'comp' = 'completion'
    'dbg' = 'debug'
}
$_nmo_group_descriptions = @{
    'file' = 'File information and statistics'
    'chunk' = 'Chunk inspection'
    'object' = 'Object inspection'
    'behavior' = 'Behavior inspection'
    'patch' = 'Patch apply and diff'
    'parameter' = 'Parameter inspection'
    'script' = 'Script editing and graph queries'
    'resource' = 'Resource management'
    'texture' = 'Texture management'
    'data' = 'Data array inspection'
    'scene' = 'Scene/level inspection'
    'entity' = '3D entity inspection'
    'material' = 'Material inspection'
    'mesh' = 'Mesh inspection and export'
    'animation' = 'Animation inspection and export'
    'type' = 'Type system information'
    'validate' = 'File validation'
    'convert' = 'Format conversion'
    'diff' = 'File comparison'
    'extension' = 'Extension management'
    'completion' = 'Shell completion scripts'
    'debug' = 'Debugging tools'
    'repl' = 'Interactive debugger'
}
$_nmo_flags = @(
    @{ Name = '-h'; Desc = 'Show help' }
    @{ Name = '--help'; Desc = 'Show help' }
    @{ Name = '-V'; Desc = 'Show version' }
    @{ Name = '--version'; Desc = 'Show version' }
    @{ Name = '-f'; Desc = 'Output format' }
    @{ Name = '--format'; Desc = 'Output format' }
    @{ Name = '--color'; Desc = 'Color mode' }
    @{ Name = '-o'; Desc = 'Write output to file' }
    @{ Name = '--output'; Desc = 'Write output to file' }
    @{ Name = '-v'; Desc = 'Increase verbosity' }
    @{ Name = '--verbose'; Desc = 'Increase verbosity' }
    @{ Name = '-q'; Desc = 'Suppress non-essential output' }
    @{ Name = '--quiet'; Desc = 'Suppress non-essential output' }
    @{ Name = '--no-pager'; Desc = 'Disable pager' }
    @{ Name = '--strict'; Desc = 'Enable strict validation mode' }
    @{ Name = '--fail-on-warning'; Desc = 'Exit with code 4 on warnings' }
    @{ Name = '--plugin'; Desc = 'Load extension plugin' }
    @{ Name = '-F'; Desc = 'Filter objects by name pattern' }
    @{ Name = '--filter'; Desc = 'Filter objects by name pattern' }
    @{ Name = '--batch'; Desc = 'Process multiple files for supported commands' }
)
$_nmo_action_flags = @{
    'file/info/' = @()
    'file/i/' = @()
    'file/header/' = @()
    'file/hdr/' = @()
    'file/stats/' = @()
    'file/st/' = @()
    'file/classes/' = @()
    'file/cls/' = @()
    'file/plugins/' = @()
    'file/pl/' = @()
    'file/space/' = @(@{ Name = '--top'; Desc = 'Show top N objects by size (default: 15)' })
    'file/sp/' = @(@{ Name = '--top'; Desc = 'Show top N objects by size (default: 15)' })
    'chunk/list/' = @()
    'chunk/ls/' = @()
    'chunk/tree/' = @()
    'chunk/t/' = @()
    'chunk/show/' = @(@{ Name = '--hexdump'; Desc = 'Include hexdump -C compatible output (text) or data_hex (JSON)' }, @{ Name = '-m'; Desc = '' }, @{ Name = '--max-bytes'; Desc = '' })
    'chunk/s/' = @(@{ Name = '--hexdump'; Desc = 'Include hexdump -C compatible output (text) or data_hex (JSON)' }, @{ Name = '-m'; Desc = '' }, @{ Name = '--max-bytes'; Desc = '' })
    'chunk/find/' = @()
    'chunk/f/' = @()
    'object/list/' = @(@{ Name = '-c'; Desc = 'Filter by class (includes derived classes)' }, @{ Name = '--class'; Desc = 'Filter by class (includes derived classes)' })
    'object/ls/' = @(@{ Name = '-c'; Desc = 'Filter by class (includes derived classes)' }, @{ Name = '--class'; Desc = 'Filter by class (includes derived classes)' })
    'object/tree/' = @()
    'object/t/' = @()
    'object/show/' = @()
    'object/s/' = @()
    'object/find/' = @(@{ Name = '--name'; Desc = 'Name filter (case-insensitive). Patterns: *, prefix*, *suffix, exact' }, @{ Name = '-c'; Desc = 'Class filter (includes derived classes)' }, @{ Name = '--class'; Desc = 'Class filter (includes derived classes)' })
    'object/f/' = @(@{ Name = '--name'; Desc = 'Name filter (case-insensitive). Patterns: *, prefix*, *suffix, exact' }, @{ Name = '-c'; Desc = 'Class filter (includes derived classes)' }, @{ Name = '--class'; Desc = 'Class filter (includes derived classes)' })
    'object/refs/' = @()
    'object/r/' = @()
    'object/rename/' = @(@{ Name = '-o'; Desc = 'Output file (required)' }, @{ Name = '--output'; Desc = 'Output file (required)' })
    'object/ren/' = @(@{ Name = '-o'; Desc = 'Output file (required)' }, @{ Name = '--output'; Desc = 'Output file (required)' })
    'object/export/' = @(@{ Name = '-c'; Desc = 'Filter by class (includes derived classes)' }, @{ Name = '--class'; Desc = 'Filter by class (includes derived classes)' }, @{ Name = '-n'; Desc = 'Filter by name pattern' }, @{ Name = '--name'; Desc = 'Filter by name pattern' }, @{ Name = '-d'; Desc = 'Recursion depth (default: 4)' }, @{ Name = '--depth'; Desc = 'Recursion depth (default: 4)' }, @{ Name = '--full'; Desc = 'Full detail mode for text output (depth 8)' }, @{ Name = '--id'; Desc = 'Export specific object by ID' })
    'object/x/' = @(@{ Name = '-c'; Desc = 'Filter by class (includes derived classes)' }, @{ Name = '--class'; Desc = 'Filter by class (includes derived classes)' }, @{ Name = '-n'; Desc = 'Filter by name pattern' }, @{ Name = '--name'; Desc = 'Filter by name pattern' }, @{ Name = '-d'; Desc = 'Recursion depth (default: 4)' }, @{ Name = '--depth'; Desc = 'Recursion depth (default: 4)' }, @{ Name = '--full'; Desc = 'Full detail mode for text output (depth 8)' }, @{ Name = '--id'; Desc = 'Export specific object by ID' })
    'object/impact/' = @()
    'object/imp/' = @()
    'object/orphans/' = @(@{ Name = '-c'; Desc = 'Filter by class (includes derived classes)' }, @{ Name = '--class'; Desc = 'Filter by class (includes derived classes)' })
    'object/orp/' = @(@{ Name = '-c'; Desc = 'Filter by class (includes derived classes)' }, @{ Name = '--class'; Desc = 'Filter by class (includes derived classes)' })
    'object/cycles/' = @()
    'object/cyc/' = @()
    'object/delete/' = @(@{ Name = '-o'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '--output'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '-c'; Desc = 'Filter by class (includes derived)' }, @{ Name = '--class'; Desc = 'Filter by class (includes derived)' }, @{ Name = '-n'; Desc = 'Filter by name wildcard pattern' }, @{ Name = '--name'; Desc = 'Filter by name wildcard pattern' }, @{ Name = '--cascade'; Desc = 'Delete dependents (default: safe-detach)' }, @{ Name = '--dry-run'; Desc = 'Preview only, do not save' }, @{ Name = '--strict'; Desc = 'Fail if any ID not found' })
    'object/del/' = @(@{ Name = '-o'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '--output'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '-c'; Desc = 'Filter by class (includes derived)' }, @{ Name = '--class'; Desc = 'Filter by class (includes derived)' }, @{ Name = '-n'; Desc = 'Filter by name wildcard pattern' }, @{ Name = '--name'; Desc = 'Filter by name wildcard pattern' }, @{ Name = '--cascade'; Desc = 'Delete dependents (default: safe-detach)' }, @{ Name = '--dry-run'; Desc = 'Preview only, do not save' }, @{ Name = '--strict'; Desc = 'Fail if any ID not found' })
    'object/create/' = @(@{ Name = '-o'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '--output'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '-c'; Desc = 'Class name (required)' }, @{ Name = '--class'; Desc = 'Class name (required)' }, @{ Name = '-n'; Desc = 'Object name' }, @{ Name = '--name'; Desc = 'Object name' }, @{ Name = '--type-guid'; Desc = 'Type GUID (d1,d2 format)' }, @{ Name = '--dry-run'; Desc = 'Preview without saving' })
    'object/copy/' = @(@{ Name = '-o'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '--output'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '-c'; Desc = 'Filter by class (includes derived)' }, @{ Name = '--class'; Desc = 'Filter by class (includes derived)' }, @{ Name = '-n'; Desc = 'Filter by name wildcard pattern' }, @{ Name = '--name'; Desc = 'Filter by name wildcard pattern' }, @{ Name = '--cascade'; Desc = 'Copy dependents' }, @{ Name = '--dry-run'; Desc = 'Preview without saving' })
    'object/cp/' = @(@{ Name = '-o'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '--output'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '-c'; Desc = 'Filter by class (includes derived)' }, @{ Name = '--class'; Desc = 'Filter by class (includes derived)' }, @{ Name = '-n'; Desc = 'Filter by name wildcard pattern' }, @{ Name = '--name'; Desc = 'Filter by name wildcard pattern' }, @{ Name = '--cascade'; Desc = 'Copy dependents' }, @{ Name = '--dry-run'; Desc = 'Preview without saving' })
    'object/import/' = @(@{ Name = '-f'; Desc = 'Input format (required)' }, @{ Name = '--format'; Desc = 'Input format (required)' }, @{ Name = '-o'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '--output'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '--create'; Desc = 'Create objects not found by ID' }, @{ Name = '--dry-run'; Desc = 'Preview changes without saving' })
    'object/graph/' = @(@{ Name = '--dot'; Desc = 'Output DOT digraph format' }, @{ Name = '--kind'; Desc = 'Filter edges by ref kind (case-insensitive)' })
    'object/gr/' = @(@{ Name = '--dot'; Desc = 'Output DOT digraph format' }, @{ Name = '--kind'; Desc = 'Filter edges by ref kind (case-insensitive)' })
    'object/set-field/' = @(@{ Name = '-o'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '--output'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '--dry-run'; Desc = 'Preview without saving' })
    'object/sf/' = @(@{ Name = '-o'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '--output'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '--dry-run'; Desc = 'Preview without saving' })
    'object/list-fields/' = @()
    'object/lf/' = @()
    'behavior/list/' = @()
    'behavior/ls/' = @()
    'behavior/stats/' = @()
    'behavior/st/' = @()
    'behavior/show/' = @(@{ Name = '--raw'; Desc = 'Show raw reflection output (like object show)' })
    'behavior/s/' = @(@{ Name = '--raw'; Desc = 'Show raw reflection output (like object show)' })
    'behavior/graph/' = @(@{ Name = '--dot'; Desc = '' }, @{ Name = '--max-nodes'; Desc = 'Limit node output (0 = no limit)' }, @{ Name = '--max-edges'; Desc = 'Limit edge output (0 = no limit)' })
    'behavior/g/' = @(@{ Name = '--dot'; Desc = '' }, @{ Name = '--max-nodes'; Desc = 'Limit node output (0 = no limit)' }, @{ Name = '--max-edges'; Desc = 'Limit edge output (0 = no limit)' })
    'behavior/graph-boundary/' = @(@{ Name = '--depth'; Desc = 'Recursion depth (default: unlimited)' })
    'behavior/replace-bb/' = @(@{ Name = '--bb-guid'; Desc = 'Replacement building-block GUID (required)' }, @{ Name = '--name'; Desc = 'Replacement behavior name' }, @{ Name = '--version'; Desc = 'Replacement building-block version (default: 65536)' }, @{ Name = '--preserve-links'; Desc = 'Require unchanged control boundary links' }, @{ Name = '--preserve-params'; Desc = 'Require unchanged parameter boundary edges' }, @{ Name = '-o'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '--output'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '--dry-run'; Desc = 'Preview without saving' })
    'behavior/fold/' = @(@{ Name = '-p'; Desc = 'Parent behavior ID' }, @{ Name = '--parent'; Desc = 'Parent behavior ID' }, @{ Name = '--nodes'; Desc = 'Comma-separated behavior node IDs' }, @{ Name = '--bb-guid'; Desc = 'Target building-block GUID' }, @{ Name = '--name'; Desc = 'Target behavior name' }, @{ Name = '--version'; Desc = 'Target building-block version (default: 65536)' }, @{ Name = '--preserve-links'; Desc = 'Require control boundary preservation' }, @{ Name = '--preserve-params'; Desc = 'Require parameter boundary preservation' }, @{ Name = '-o'; Desc = 'Future output file path' }, @{ Name = '--output'; Desc = 'Future output file path' }, @{ Name = '--dry-run'; Desc = 'Report planned fold without saving (currently required)' })
    'behavior/fold-candidates/' = @(@{ Name = '-p'; Desc = 'Parent behavior ID' }, @{ Name = '--parent'; Desc = 'Parent behavior ID' }, @{ Name = '-d'; Desc = 'Recursion depth (default: unlimited)' }, @{ Name = '--depth'; Desc = 'Recursion depth (default: unlimited)' })
    'behavior/dump/' = @(@{ Name = '--all'; Desc = 'Dump all script behavior trees' }, @{ Name = '--flows'; Desc = 'Include execution/data flow summaries for one behavior' }, @{ Name = '--values'; Desc = 'Include decoded local/output parameter values' })
    'behavior/d/' = @(@{ Name = '--all'; Desc = 'Dump all script behavior trees' }, @{ Name = '--flows'; Desc = 'Include execution/data flow summaries for one behavior' }, @{ Name = '--values'; Desc = 'Include decoded local/output parameter values' })
    'behavior/find/' = @(@{ Name = '--name'; Desc = 'Name wildcard pattern' }, @{ Name = '--guid'; Desc = 'Building block GUID' }, @{ Name = '--type'; Desc = 'Behavior type filter' })
    'behavior/f/' = @(@{ Name = '--name'; Desc = 'Name wildcard pattern' }, @{ Name = '--guid'; Desc = 'Building block GUID' }, @{ Name = '--type'; Desc = 'Behavior type filter' })
    'behavior/trace/' = @(@{ Name = '--from'; Desc = 'Starting IO port' }, @{ Name = '--max-depth'; Desc = 'Maximum trace depth' })
    'behavior/tr/' = @(@{ Name = '--from'; Desc = 'Starting IO port' }, @{ Name = '--max-depth'; Desc = 'Maximum trace depth' })
    'behavior/add-link/' = @(@{ Name = '-p'; Desc = 'Parent behavior ID (required)' }, @{ Name = '--parent'; Desc = 'Parent behavior ID (required)' }, @{ Name = '--from'; Desc = 'Source IO port ID (required)' }, @{ Name = '--to'; Desc = 'Target IO port ID (required)' }, @{ Name = '-d'; Desc = 'Activation delay in frames (default: 1)' }, @{ Name = '--delay'; Desc = 'Activation delay in frames (default: 1)' }, @{ Name = '-o'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '--output'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '--dry-run'; Desc = 'Preview without saving' })
    'behavior/remove-link/' = @(@{ Name = '-p'; Desc = 'Parent behavior ID (required)' }, @{ Name = '--parent'; Desc = 'Parent behavior ID (required)' }, @{ Name = '-o'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '--output'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '--dry-run'; Desc = 'Preview without saving' })
    'behavior/interface/' = @()
    'behavior/iface/' = @()
    'behavior/interface/show' = @()
    'behavior/iface/show' = @()
    'behavior/interface/set-pos' = @()
    'behavior/iface/set-pos' = @()
    'behavior/interface/fold' = @()
    'behavior/iface/fold' = @()
    'behavior/interface/unfold' = @()
    'behavior/iface/unfold' = @()
    'behavior/interface/set-color' = @()
    'behavior/iface/set-color' = @()
    'behavior/interface/canonicalize' = @()
    'behavior/iface/canonicalize' = @()
    'behavior/interface/add-comment' = @()
    'behavior/iface/add-comment' = @()
    'behavior/interface/remove-comment' = @()
    'behavior/iface/remove-comment' = @()
    'behavior/interface/set-comment-text' = @()
    'behavior/iface/set-comment-text' = @()
    'behavior/interface/move-comment' = @()
    'behavior/iface/move-comment' = @()
    'behavior/interface/set-comment-style' = @()
    'behavior/iface/set-comment-style' = @()
    'behavior/interface/add-point' = @()
    'behavior/iface/add-point' = @()
    'behavior/interface/clear-points' = @()
    'behavior/iface/clear-points' = @()
    'behavior/interface/remove-point' = @()
    'behavior/iface/remove-point' = @()
    'behavior/interface/move-point' = @()
    'behavior/iface/move-point' = @()
    'behavior/interface/set-link-highlight' = @()
    'behavior/iface/set-link-highlight' = @()
    'behavior/interface/move-op' = @()
    'behavior/iface/move-op' = @()
    'behavior/interface/move-param' = @()
    'behavior/iface/move-param' = @()
    'behavior/interface/set-param-style' = @()
    'behavior/iface/set-param-style' = @()
    'behavior/interface/resize' = @()
    'behavior/iface/resize' = @()
    'behavior/interface/set-expand' = @()
    'behavior/iface/set-expand' = @()
    'behavior/interface/set-viewport' = @()
    'behavior/iface/set-viewport' = @()
    'behavior/interface/set-graph-io' = @()
    'behavior/iface/set-graph-io' = @()
    'behavior/interface/translate' = @()
    'behavior/iface/translate' = @()
    'patch/apply/' = @(@{ Name = '-o'; Desc = 'Output file for project generation' }, @{ Name = '--output'; Desc = 'Output file for project generation' }, @{ Name = '--project'; Desc = 'Project manifest to generate' }, @{ Name = '--dry-run'; Desc = 'Preview operations without saving output' })
    'patch/diff/' = @()
    'parameter/list/' = @()
    'parameter/ls/' = @()
    'parameter/show/' = @()
    'parameter/s/' = @()
    'parameter/dump/' = @(@{ Name = '--all'; Desc = 'Dump all parameters in the file' }, @{ Name = '--type'; Desc = 'Filter by parameter type GUID' })
    'parameter/d/' = @(@{ Name = '--all'; Desc = 'Dump all parameters in the file' }, @{ Name = '--type'; Desc = 'Filter by parameter type GUID' })
    'parameter/set/' = @(@{ Name = '-o'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '--output'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '-b'; Desc = 'Owner behavior/object ID' }, @{ Name = '--owner'; Desc = 'Owner behavior/object ID' }, @{ Name = '-n'; Desc = 'Parameter name within owner' }, @{ Name = '--name'; Desc = 'Parameter name within owner' }, @{ Name = '-i'; Desc = 'Parameter index within owner' }, @{ Name = '--index'; Desc = 'Parameter index within owner' }, @{ Name = '--hex'; Desc = 'Value is raw hex bytes' }, @{ Name = '--dry-run'; Desc = 'Show old/new without saving' })
    'script/graph/' = @()
    'script/g/' = @()
    'script/run/' = @()
    'script/node/' = @()
    'script/io/' = @()
    'script/link/' = @()
    'script/param/' = @()
    'script/op/' = @()
    'resource/list/' = @()
    'resource/ls/' = @()
    'resource/show/' = @()
    'resource/s/' = @()
    'resource/extract/' = @()
    'resource/x/' = @()
    'resource/import/' = @(@{ Name = '-o'; Desc = 'Output file (required)' }, @{ Name = '--output'; Desc = 'Output file (required)' }, @{ Name = '-n'; Desc = 'Resource name (default: basename of disk file)' }, @{ Name = '--name'; Desc = 'Resource name (default: basename of disk file)' }, @{ Name = '--owner'; Desc = 'Owner object IDs (comma-separated)' })
    'resource/imp/' = @(@{ Name = '-o'; Desc = 'Output file (required)' }, @{ Name = '--output'; Desc = 'Output file (required)' }, @{ Name = '-n'; Desc = 'Resource name (default: basename of disk file)' }, @{ Name = '--name'; Desc = 'Resource name (default: basename of disk file)' }, @{ Name = '--owner'; Desc = 'Owner object IDs (comma-separated)' })
    'resource/replace/' = @(@{ Name = '-o'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '--output'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '-i'; Desc = 'Resource index' }, @{ Name = '--index'; Desc = 'Resource index' }, @{ Name = '-n'; Desc = 'Resource name' }, @{ Name = '--name'; Desc = 'Resource name' }, @{ Name = '--dry-run'; Desc = 'Preview only, do not save' })
    'resource/rep/' = @(@{ Name = '-o'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '--output'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '-i'; Desc = 'Resource index' }, @{ Name = '--index'; Desc = 'Resource index' }, @{ Name = '-n'; Desc = 'Resource name' }, @{ Name = '--name'; Desc = 'Resource name' }, @{ Name = '--dry-run'; Desc = 'Preview only, do not save' })
    'resource/remove/' = @(@{ Name = '-o'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '--output'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '-i'; Desc = 'Resource index' }, @{ Name = '--index'; Desc = 'Resource index' }, @{ Name = '-n'; Desc = 'Resource name' }, @{ Name = '--name'; Desc = 'Resource name' }, @{ Name = '--dry-run'; Desc = 'Preview only, do not save' })
    'resource/rm/' = @(@{ Name = '-o'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '--output'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '-i'; Desc = 'Resource index' }, @{ Name = '--index'; Desc = 'Resource index' }, @{ Name = '-n'; Desc = 'Resource name' }, @{ Name = '--name'; Desc = 'Resource name' }, @{ Name = '--dry-run'; Desc = 'Preview only, do not save' })
    'resource/info/' = @(@{ Name = '-i'; Desc = 'Resource index (in NMO)' }, @{ Name = '--index'; Desc = 'Resource index (in NMO)' }, @{ Name = '-n'; Desc = 'Resource name (in NMO)' }, @{ Name = '--name'; Desc = 'Resource name (in NMO)' })
    'texture/list/' = @(@{ Name = '-s'; Desc = 'Sort by: id, name, size' }, @{ Name = '--sort'; Desc = 'Sort by: id, name, size' }, @{ Name = '-t'; Desc = 'Show only top N textures' }, @{ Name = '--top'; Desc = 'Show only top N textures' }, @{ Name = '-r'; Desc = 'Reverse sort order' }, @{ Name = '--reverse'; Desc = 'Reverse sort order' })
    'texture/ls/' = @(@{ Name = '-s'; Desc = 'Sort by: id, name, size' }, @{ Name = '--sort'; Desc = 'Sort by: id, name, size' }, @{ Name = '-t'; Desc = 'Show only top N textures' }, @{ Name = '--top'; Desc = 'Show only top N textures' }, @{ Name = '-r'; Desc = 'Reverse sort order' }, @{ Name = '--reverse'; Desc = 'Reverse sort order' })
    'texture/show/' = @(@{ Name = '--id'; Desc = 'Texture object ID (alternative to positional)' }, @{ Name = '-n'; Desc = 'Exact texture object name' }, @{ Name = '--name'; Desc = 'Exact texture object name' })
    'texture/s/' = @(@{ Name = '--id'; Desc = 'Texture object ID (alternative to positional)' }, @{ Name = '-n'; Desc = 'Exact texture object name' }, @{ Name = '--name'; Desc = 'Exact texture object name' })
    'texture/extract/' = @(@{ Name = '-d'; Desc = 'Output directory (required)' }, @{ Name = '--out-dir'; Desc = 'Output directory (required)' }, @{ Name = '--id'; Desc = 'Extract single texture by ID' }, @{ Name = '-n'; Desc = 'Filter by name wildcard' }, @{ Name = '--name'; Desc = 'Filter by name wildcard' }, @{ Name = '-f'; Desc = 'Output format: png, bmp, tga, jpg (default: png)' }, @{ Name = '--format'; Desc = 'Output format: png, bmp, tga, jpg (default: png)' }, @{ Name = '-q'; Desc = 'JPEG quality 1-100 (default: 90)' }, @{ Name = '--quality'; Desc = 'JPEG quality 1-100 (default: 90)' }, @{ Name = '--overwrite'; Desc = 'Overwrite existing files' })
    'texture/x/' = @(@{ Name = '-d'; Desc = 'Output directory (required)' }, @{ Name = '--out-dir'; Desc = 'Output directory (required)' }, @{ Name = '--id'; Desc = 'Extract single texture by ID' }, @{ Name = '-n'; Desc = 'Filter by name wildcard' }, @{ Name = '--name'; Desc = 'Filter by name wildcard' }, @{ Name = '-f'; Desc = 'Output format: png, bmp, tga, jpg (default: png)' }, @{ Name = '--format'; Desc = 'Output format: png, bmp, tga, jpg (default: png)' }, @{ Name = '-q'; Desc = 'JPEG quality 1-100 (default: 90)' }, @{ Name = '--quality'; Desc = 'JPEG quality 1-100 (default: 90)' }, @{ Name = '--overwrite'; Desc = 'Overwrite existing files' })
    'texture/replace/' = @(@{ Name = '--id'; Desc = 'Texture object ID (alternative to positional)' }, @{ Name = '-n'; Desc = 'Exact texture object name' }, @{ Name = '--name'; Desc = 'Exact texture object name' }, @{ Name = '-f'; Desc = 'Image file to load (required)' }, @{ Name = '--file'; Desc = 'Image file to load (required)' }, @{ Name = '-o'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '--output'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '--dry-run'; Desc = 'Preview without saving' })
    'texture/rep/' = @(@{ Name = '--id'; Desc = 'Texture object ID (alternative to positional)' }, @{ Name = '-n'; Desc = 'Exact texture object name' }, @{ Name = '--name'; Desc = 'Exact texture object name' }, @{ Name = '-f'; Desc = 'Image file to load (required)' }, @{ Name = '--file'; Desc = 'Image file to load (required)' }, @{ Name = '-o'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '--output'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '--dry-run'; Desc = 'Preview without saving' })
    'data/list/' = @()
    'data/ls/' = @()
    'data/show/' = @()
    'data/s/' = @()
    'data/dump/' = @(@{ Name = '-r'; Desc = 'Dump a single row by index (key-value format)' }, @{ Name = '--row'; Desc = 'Dump a single row by index (key-value format)' })
    'data/d/' = @(@{ Name = '-r'; Desc = 'Dump a single row by index (key-value format)' }, @{ Name = '--row'; Desc = 'Dump a single row by index (key-value format)' })
    'data/set-cell/' = @(@{ Name = '-r'; Desc = 'Row index (0-based, required)' }, @{ Name = '--row'; Desc = 'Row index (0-based, required)' }, @{ Name = '-c'; Desc = 'Column index (0-based, required)' }, @{ Name = '--col'; Desc = 'Column index (0-based, required)' }, @{ Name = '-v'; Desc = 'New cell value (required)' }, @{ Name = '--value'; Desc = 'New cell value (required)' }, @{ Name = '-o'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '--output'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '--dry-run'; Desc = 'Preview without saving' })
    'data/sc/' = @(@{ Name = '-r'; Desc = 'Row index (0-based, required)' }, @{ Name = '--row'; Desc = 'Row index (0-based, required)' }, @{ Name = '-c'; Desc = 'Column index (0-based, required)' }, @{ Name = '--col'; Desc = 'Column index (0-based, required)' }, @{ Name = '-v'; Desc = 'New cell value (required)' }, @{ Name = '--value'; Desc = 'New cell value (required)' }, @{ Name = '-o'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '--output'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '--dry-run'; Desc = 'Preview without saving' })
    'scene/list/' = @()
    'scene/ls/' = @()
    'scene/show/' = @()
    'scene/s/' = @()
    'scene/set/' = @(@{ Name = '--id'; Desc = 'Scene object ID (alternative to positional)' }, @{ Name = '-n'; Desc = 'Exact scene object name' }, @{ Name = '--name'; Desc = 'Exact scene object name' }, @{ Name = '-o'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '--output'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '--bg-color'; Desc = 'Background color (ARGB hex, e.g. 0xFF000000)' }, @{ Name = '--ambient'; Desc = 'Ambient light color (ARGB hex)' }, @{ Name = '--fog-color'; Desc = 'Fog color (ARGB hex)' }, @{ Name = '--camera'; Desc = 'Starting camera object ID' }, @{ Name = '--dry-run'; Desc = 'Preview without saving' })
    'entity/list/' = @(@{ Name = '-c'; Desc = 'Filter by class (e.g. CKCamera, CKLight)' }, @{ Name = '--class'; Desc = 'Filter by class (e.g. CKCamera, CKLight)' })
    'entity/ls/' = @(@{ Name = '-c'; Desc = 'Filter by class (e.g. CKCamera, CKLight)' }, @{ Name = '--class'; Desc = 'Filter by class (e.g. CKCamera, CKLight)' })
    'entity/show/' = @()
    'entity/s/' = @()
    'entity/set-position/' = @(@{ Name = '-o'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '--output'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '--dry-run'; Desc = 'Preview without saving' })
    'entity/sp/' = @(@{ Name = '-o'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '--output'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '--dry-run'; Desc = 'Preview without saving' })
    'entity/set-parent/' = @(@{ Name = '-o'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '--output'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '--dry-run'; Desc = 'Preview without saving' })
    'entity/set-camera/' = @(@{ Name = '-o'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '--output'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '--fov'; Desc = 'Field of view (radians)' }, @{ Name = '--near'; Desc = 'Near clipping plane' }, @{ Name = '--far'; Desc = 'Far clipping plane' }, @{ Name = '--dry-run'; Desc = 'Preview without saving' })
    'entity/sc/' = @(@{ Name = '-o'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '--output'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '--fov'; Desc = 'Field of view (radians)' }, @{ Name = '--near'; Desc = 'Near clipping plane' }, @{ Name = '--far'; Desc = 'Far clipping plane' }, @{ Name = '--dry-run'; Desc = 'Preview without saving' })
    'entity/set-light/' = @(@{ Name = '-o'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '--output'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '--diffuse'; Desc = 'Diffuse color' }, @{ Name = '--range'; Desc = 'Light range' }, @{ Name = '--dry-run'; Desc = 'Preview without saving' })
    'entity/sl/' = @(@{ Name = '-o'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '--output'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '--diffuse'; Desc = 'Diffuse color' }, @{ Name = '--range'; Desc = 'Light range' }, @{ Name = '--dry-run'; Desc = 'Preview without saving' })
    'material/list/' = @()
    'material/ls/' = @()
    'material/show/' = @()
    'material/s/' = @()
    'material/set/' = @(@{ Name = '--id'; Desc = 'Material object ID (alternative to positional)' }, @{ Name = '-n'; Desc = 'Exact material object name' }, @{ Name = '--name'; Desc = 'Exact material object name' }, @{ Name = '-o'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '--output'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '--diffuse'; Desc = 'Diffuse color (ARGB hex, e.g. 0xFFFF0000)' }, @{ Name = '--ambient'; Desc = 'Ambient color (ARGB hex)' }, @{ Name = '--specular'; Desc = 'Specular color (ARGB hex)' }, @{ Name = '--emissive'; Desc = 'Emissive color (ARGB hex)' }, @{ Name = '--power'; Desc = 'Specular power' }, @{ Name = '--dry-run'; Desc = 'Preview without saving' })
    'mesh/list/' = @()
    'mesh/ls/' = @()
    'mesh/show/' = @()
    'mesh/s/' = @()
    'mesh/export/' = @(@{ Name = '-d'; Desc = 'Output directory (required)' }, @{ Name = '--out-dir'; Desc = 'Output directory (required)' }, @{ Name = '--id'; Desc = 'Export single mesh by ID' }, @{ Name = '-a'; Desc = 'Export all meshes' }, @{ Name = '--all'; Desc = 'Export all meshes' })
    'mesh/x/' = @(@{ Name = '-d'; Desc = 'Output directory (required)' }, @{ Name = '--out-dir'; Desc = 'Output directory (required)' }, @{ Name = '--id'; Desc = 'Export single mesh by ID' }, @{ Name = '-a'; Desc = 'Export all meshes' }, @{ Name = '--all'; Desc = 'Export all meshes' })
    'mesh/import/' = @(@{ Name = '-o'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '--output'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '--replace'; Desc = 'Replace existing mesh by ID' }, @{ Name = '--replace-name'; Desc = 'Replace existing mesh by exact name' }, @{ Name = '-n'; Desc = 'Mesh name' }, @{ Name = '--name'; Desc = 'Mesh name' }, @{ Name = '--dry-run'; Desc = 'Preview without saving' })
    'mesh/imp/' = @(@{ Name = '-o'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '--output'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '--replace'; Desc = 'Replace existing mesh by ID' }, @{ Name = '--replace-name'; Desc = 'Replace existing mesh by exact name' }, @{ Name = '-n'; Desc = 'Mesh name' }, @{ Name = '--name'; Desc = 'Mesh name' }, @{ Name = '--dry-run'; Desc = 'Preview without saving' })
    'animation/list/' = @()
    'animation/ls/' = @()
    'animation/show/' = @()
    'animation/s/' = @()
    'animation/keys/' = @()
    'animation/k/' = @()
    'animation/export/' = @(@{ Name = '-d'; Desc = 'Output directory (required)' }, @{ Name = '--out-dir'; Desc = 'Output directory (required)' }, @{ Name = '-i'; Desc = 'Export single animation by ID' }, @{ Name = '--id'; Desc = 'Export single animation by ID' }, @{ Name = '--all'; Desc = 'Export all CKObjectAnimation objects' })
    'animation/x/' = @(@{ Name = '-d'; Desc = 'Output directory (required)' }, @{ Name = '--out-dir'; Desc = 'Output directory (required)' }, @{ Name = '-i'; Desc = 'Export single animation by ID' }, @{ Name = '--id'; Desc = 'Export single animation by ID' }, @{ Name = '--all'; Desc = 'Export all CKObjectAnimation objects' })
    'animation/import/' = @(@{ Name = '-o'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '--output'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '--replace'; Desc = 'Replace existing animation by ID' }, @{ Name = '--replace-name'; Desc = 'Replace existing animation by exact name' }, @{ Name = '--dry-run'; Desc = 'Preview without saving' })
    'animation/imp/' = @(@{ Name = '-o'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '--output'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '--replace'; Desc = 'Replace existing animation by ID' }, @{ Name = '--replace-name'; Desc = 'Replace existing animation by exact name' }, @{ Name = '--dry-run'; Desc = 'Preview without saving' })
    'type/list/' = @()
    'type/ls/' = @()
    'type/show/' = @()
    'type/s/' = @()
    'type/class-tree/' = @()
    'type/ct/' = @()
    'validate/all/' = @()
    'validate/a/' = @()
    'validate/structure/' = @(@{ Name = '--fix'; Desc = 'Show suggested fixes for each issue' }, @{ Name = '--strict'; Desc = 'Exit with code 3 if errors exist' }, @{ Name = '--fail-on-warning'; Desc = 'Exit with code 4 if warnings exist' })
    'validate/st/' = @(@{ Name = '--fix'; Desc = 'Show suggested fixes for each issue' }, @{ Name = '--strict'; Desc = 'Exit with code 3 if errors exist' }, @{ Name = '--fail-on-warning'; Desc = 'Exit with code 4 if warnings exist' })
    'validate/references/' = @(@{ Name = '--fix'; Desc = 'Show suggested fixes for each issue' }, @{ Name = '--strict'; Desc = 'Exit with code 3 if errors exist' }, @{ Name = '--fail-on-warning'; Desc = 'Exit with code 4 if warnings exist' })
    'validate/ref/' = @(@{ Name = '--fix'; Desc = 'Show suggested fixes for each issue' }, @{ Name = '--strict'; Desc = 'Exit with code 3 if errors exist' }, @{ Name = '--fail-on-warning'; Desc = 'Exit with code 4 if warnings exist' })
    'validate/resources/' = @(@{ Name = '--strict'; Desc = 'Exit with code 3 if errors exist' }, @{ Name = '--fail-on-warning'; Desc = 'Exit with code 4 if warnings exist' })
    'validate/res/' = @(@{ Name = '--strict'; Desc = 'Exit with code 3 if errors exist' }, @{ Name = '--fail-on-warning'; Desc = 'Exit with code 4 if warnings exist' })
    'validate/orphans/' = @(@{ Name = '-c'; Desc = 'Filter by class (includes derived classes)' }, @{ Name = '--class'; Desc = 'Filter by class (includes derived classes)' }, @{ Name = '--strict'; Desc = 'Exit with code 3 if orphans found' }, @{ Name = '--summary'; Desc = 'Summary only (no per-object listing)' }, @{ Name = '-o'; Desc = 'Remove orphans and save cleaned file' }, @{ Name = '--strip'; Desc = 'Remove orphans and save cleaned file' })
    'validate/orp/' = @(@{ Name = '-c'; Desc = 'Filter by class (includes derived classes)' }, @{ Name = '--class'; Desc = 'Filter by class (includes derived classes)' }, @{ Name = '--strict'; Desc = 'Exit with code 3 if orphans found' }, @{ Name = '--summary'; Desc = 'Summary only (no per-object listing)' }, @{ Name = '-o'; Desc = 'Remove orphans and save cleaned file' }, @{ Name = '--strip'; Desc = 'Remove orphans and save cleaned file' })
    'convert/copy/' = @(@{ Name = '-o'; Desc = 'Output file (required)' }, @{ Name = '--output'; Desc = 'Output file (required)' }, @{ Name = '--compress'; Desc = 'Compression level (0-9)' }, @{ Name = '--sequential-ids'; Desc = 'Use sequential file IDs' }, @{ Name = '--no-managers'; Desc = 'Exclude manager state' }, @{ Name = '--strip-resources'; Desc = 'Strip included files/resources' }, @{ Name = '--validate'; Desc = 'Validate before writing' }, @{ Name = '--fast-save'; Desc = 'Skip explicit save flush/write-through' })
    'convert/cp/' = @(@{ Name = '-o'; Desc = 'Output file (required)' }, @{ Name = '--output'; Desc = 'Output file (required)' }, @{ Name = '--compress'; Desc = 'Compression level (0-9)' }, @{ Name = '--sequential-ids'; Desc = 'Use sequential file IDs' }, @{ Name = '--no-managers'; Desc = 'Exclude manager state' }, @{ Name = '--strip-resources'; Desc = 'Strip included files/resources' }, @{ Name = '--validate'; Desc = 'Validate before writing' }, @{ Name = '--fast-save'; Desc = 'Skip explicit save flush/write-through' })
    'convert/version/' = @()
    'convert/v/' = @()
    'convert/strip/' = @(@{ Name = '-o'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '--output'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '-c'; Desc = 'Strip objects of this class' }, @{ Name = '--class'; Desc = 'Strip objects of this class' }, @{ Name = '--name'; Desc = 'Strip objects matching name pattern' }, @{ Name = '--dry-run'; Desc = 'Preview matching objects without modifying' }, @{ Name = '--fast-save'; Desc = 'Skip explicit save flush/write-through' })
    'convert/st/' = @(@{ Name = '-o'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '--output'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '-c'; Desc = 'Strip objects of this class' }, @{ Name = '--class'; Desc = 'Strip objects of this class' }, @{ Name = '--name'; Desc = 'Strip objects matching name pattern' }, @{ Name = '--dry-run'; Desc = 'Preview matching objects without modifying' }, @{ Name = '--fast-save'; Desc = 'Skip explicit save flush/write-through' })
    'convert/merge/' = @(@{ Name = '-o'; Desc = 'Output file (required)' }, @{ Name = '--output'; Desc = 'Output file (required)' }, @{ Name = '--fast-save'; Desc = 'Skip explicit save flush/write-through' })
    'convert/m/' = @(@{ Name = '-o'; Desc = 'Output file (required)' }, @{ Name = '--output'; Desc = 'Output file (required)' }, @{ Name = '--fast-save'; Desc = 'Skip explicit save flush/write-through' })
    'convert/export/' = @(@{ Name = '-o'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '--output'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '-c'; Desc = 'Filter by class (includes derived classes)' }, @{ Name = '--class'; Desc = 'Filter by class (includes derived classes)' }, @{ Name = '-n'; Desc = 'Filter by name pattern' }, @{ Name = '--name'; Desc = 'Filter by name pattern' }, @{ Name = '--all'; Desc = 'Export all objects (no filter required)' }, @{ Name = '--deps'; Desc = 'Include transitive dependencies' }, @{ Name = '--dry-run'; Desc = 'Preview matching objects without writing' }, @{ Name = '--compress'; Desc = 'Compression level' }, @{ Name = '--fast-save'; Desc = 'Skip explicit save flush/write-through' })
    'convert/x/' = @(@{ Name = '-o'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '--output'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '-c'; Desc = 'Filter by class (includes derived classes)' }, @{ Name = '--class'; Desc = 'Filter by class (includes derived classes)' }, @{ Name = '-n'; Desc = 'Filter by name pattern' }, @{ Name = '--name'; Desc = 'Filter by name pattern' }, @{ Name = '--all'; Desc = 'Export all objects (no filter required)' }, @{ Name = '--deps'; Desc = 'Include transitive dependencies' }, @{ Name = '--dry-run'; Desc = 'Preview matching objects without writing' }, @{ Name = '--compress'; Desc = 'Compression level' }, @{ Name = '--fast-save'; Desc = 'Skip explicit save flush/write-through' })
    'diff/summary/' = @(@{ Name = '--ignore-order'; Desc = 'Ignore object order differences' })
    'diff/s/' = @(@{ Name = '--ignore-order'; Desc = 'Ignore object order differences' })
    'diff/objects/' = @(@{ Name = '--max-objects'; Desc = 'Max changed objects to show (default: unlimited)' }, @{ Name = '--max-fields'; Desc = 'Max changed fields per object (default: unlimited)' }, @{ Name = '--min-similarity'; Desc = 'Min match similarity in [0,1] (default: 0.0)' }, @{ Name = '--rename-similarity'; Desc = '' })
    'diff/obj/' = @(@{ Name = '--max-objects'; Desc = 'Max changed objects to show (default: unlimited)' }, @{ Name = '--max-fields'; Desc = 'Max changed fields per object (default: unlimited)' }, @{ Name = '--min-similarity'; Desc = 'Min match similarity in [0,1] (default: 0.0)' }, @{ Name = '--rename-similarity'; Desc = '' })
    'diff/chunks/' = @(@{ Name = '--object'; Desc = 'Compare a specific object''s chunks' })
    'diff/ch/' = @(@{ Name = '--object'; Desc = 'Compare a specific object''s chunks' })
    'diff/full/' = @()
    'diff/f/' = @()
    'extension/list/' = @()
    'extension/ls/' = @()
    'extension/load/' = @()
    'extension/ld/' = @()
    'extension/info/' = @()
    'extension/i/' = @()
    'extension/check/' = @()
    'extension/ch/' = @()
    'completion/bash/' = @()
    'completion/fish/' = @()
    'completion/zsh/' = @()
    'completion/powershell/' = @()
    'completion/ps1/' = @()
    'debug/load-phases/' = @()
    'debug/lp/' = @()
    'debug/chunks/' = @()
    'debug/ch/' = @()
    'debug/objects/' = @()
    'debug/obj/' = @()
    'debug/export/' = @(@{ Name = '--data'; Desc = 'Include chunk raw bytes as data_hex' }, @{ Name = '--max-bytes'; Desc = 'Limit emitted chunk bytes when --data is set (default 4096)' })
    'debug/x/' = @(@{ Name = '--data'; Desc = 'Include chunk raw bytes as data_hex' }, @{ Name = '--max-bytes'; Desc = 'Limit emitted chunk bytes when --data is set (default 4096)' })
    'debug/probe/' = @(@{ Name = '--behavior'; Desc = 'Parent behavior receiving the probe' }, @{ Name = '--remove-link'; Desc = 'Existing link removed before inserting the probe' }, @{ Name = '--from-io'; Desc = 'Existing source IO linked to the probe input' }, @{ Name = '--to-io'; Desc = 'Existing target IO linked from the probe output' }, @{ Name = '--message-node'; Desc = 'Message BB selected by message-logger probes' }, @{ Name = '--parameter'; Desc = 'Source parameter connected to parameter-logger text input' }, @{ Name = '--dataarray'; Desc = 'Data array id tagged by data-cell-logger' }, @{ Name = '--row'; Desc = 'Data array row tagged by data-cell-logger' }, @{ Name = '--col'; Desc = 'Data array column tagged by data-cell-logger' }, @{ Name = '--write-node'; Desc = 'Explicit data write behavior for data-cell-logger' }, @{ Name = '--write-operation'; Desc = 'Explicit data write operation for data-cell-logger' }, @{ Name = '--write-link'; Desc = 'Explicit data write control link for data-cell-logger' }, @{ Name = '--delay'; Desc = 'Activation delay for the first generated probe link' }, @{ Name = '--name'; Desc = 'Probe node name (default: nmo debug probe)' }, @{ Name = '--text'; Desc = 'Probe text for 2d-text, console, debug-output, message-logger, or data-cell-logger' }, @{ Name = '--dry-run'; Desc = 'Report the edit without saving' }, @{ Name = '-o'; Desc = 'Output file (required unless --dry-run)' }, @{ Name = '--output'; Desc = 'Output file (required unless --dry-run)' })
    'repl/start/' = @()
}

Register-ArgumentCompleter -CommandName nmo -Native -ScriptBlock {
    param($wordToComplete, $commandAst, $cursorPosition)
    $tokens = $commandAst.ToString().Substring(0, $cursorPosition).Trim() -split '\s+'
    $valueOptions = @('-f','--format','--color','-o','--output','--plugin','-F','--filter','--top', '-m', '--max-bytes', '-c', '--class', '--name', '-o', '--output', '-n', '-d', '--depth', '--id', '--type-guid', '--kind', '--max-nodes', '--max-edges', '--bb-guid', '--version', '-p', '--parent', '--nodes', '--guid', '--type', '--from', '--max-depth', '--to', '--delay', '--project', '-b', '--owner', '-i', '--index', '-s', '--sort', '-t', '--out-dir', '-f', '--format', '-q', '--quality', '--file', '-r', '--row', '--col', '-v', '--value', '--bg-color', '--ambient', '--fog-color', '--camera', '--fov', '--near', '--far', '--diffuse', '--range', '--specular', '--emissive', '--power', '--replace', '--replace-name', '--strip', '--compress', '--max-objects', '--max-fields', '--min-similarity', '--rename-similarity', '--object', '--behavior', '--remove-link', '--from-io', '--to-io', '--message-node', '--parameter', '--dataarray', '--write-node', '--write-operation', '--write-link', '--text')
    $positional = @()
    $expectValue = $false
    for ($i = 1; $i -lt $tokens.Count; $i++) {
        if ($expectValue) { $expectValue = $false; continue }
        if ($tokens[$i].StartsWith('-')) { if ($valueOptions -contains $tokens[$i]) { $expectValue = $true }; continue }
        $positional += $tokens[$i]
    }
    if ($wordToComplete -ne '' -and $positional.Count -gt 0 -and $tokens[-1] -eq $wordToComplete) {
        $positional = @($positional[0..($positional.Count - 2)])
    }
    $group = if ($positional.Count -ge 1) { $positional[0] } else { $null }
    if ($group -and $_nmo_aliases.ContainsKey($group)) { $group = $_nmo_aliases[$group] }
    if ($wordToComplete.StartsWith('-')) {
        $actionFlags = @()
        if ($positional.Count -ge 2) {
            $flagKey = if ($positional.Count -ge 3) { "$group/$($positional[1])/$($positional[2])" } else { "$group/$($positional[1])/" }
            if ($_nmo_action_flags.ContainsKey($flagKey)) { $actionFlags = $_nmo_action_flags[$flagKey] }
        }
        ($_nmo_flags + $actionFlags) | Where-Object { $_.Name -like "$wordToComplete*" } | ForEach-Object { [System.Management.Automation.CompletionResult]::new($_.Name, $_.Name, 'ParameterValue', $_.Desc) }
        return
    }
    if ($positional.Count -eq 0) {
        $items = @()
        foreach ($g in $_nmo_groups.Keys) { $items += @{ Name = $g; Desc = $_nmo_group_descriptions[$g] } }
        foreach ($a in $_nmo_aliases.Keys) { $items += @{ Name = $a; Desc = "Alias for $($_nmo_aliases[$a])" } }
        $items | Where-Object { $_.Name -like "$wordToComplete*" } | Sort-Object Name | ForEach-Object { [System.Management.Automation.CompletionResult]::new($_.Name, $_.Name, 'ParameterValue', $_.Desc) }
        return
    }
    if ($positional.Count -eq 1 -and $_nmo_groups.ContainsKey($group)) {
        $_nmo_groups[$group] | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object { [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', "$group $_") }
        return
    }
    if ($positional.Count -eq 2) {
        $key = "$group/$($positional[1])"
        if ($_nmo_sub_actions.ContainsKey($key)) {
            $_nmo_sub_actions[$key] | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object { [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', "$key $_") }
            return
        }
    }
    $pattern = if ($wordToComplete) { "$wordToComplete*" } else { '*' }
    Get-ChildItem -Path . -Filter $pattern -File -ErrorAction SilentlyContinue | Where-Object { $_.Extension -in '.nmo', '.cmo', '.vmo', '.json', '.obj' } | ForEach-Object { [System.Management.Automation.CompletionResult]::new($_.Name, $_.Name, 'ProviderItem', $_.Name) }
    $_nmo_flags | Where-Object { $_.Name -like "$wordToComplete*" } | ForEach-Object { [System.Management.Automation.CompletionResult]::new($_.Name, $_.Name, 'ParameterValue', $_.Desc) }
}
