# PowerShell completion for nmo - Virtools NMO file tool
# Auto-generated by tools/scripts/gen_completions.py; do not edit by hand.


$_nmo_groups = @{
    'file' = @('info', 'i', 'header', 'hdr', 'stats', 'st', 'classes', 'cls', 'plugins', 'pl', 'space', 'sp')
    'chunk' = @('list', 'ls', 'tree', 't', 'show', 's', 'find', 'f')
    'object' = @('list', 'ls', 'tree', 't', 'show', 's', 'find', 'f', 'refs', 'r', 'rename', 'ren', 'export', 'x', 'impact', 'imp', 'orphans', 'orp', 'cycles', 'cyc', 'delete', 'del', 'create', 'copy', 'cp', 'import-json', 'graph', 'gr', 'set-field', 'sf', 'list-fields', 'lf')
    'behavior' = @('list', 'ls', 'stats', 'st', 'show', 's', 'graph', 'g', 'dump', 'd', 'find', 'f', 'trace', 'tr', 'add-link', 'remove-link', 'interface', 'iface')
    'parameter' = @('list', 'ls', 'show', 's', 'dump', 'd', 'set')
    'resource' = @('list', 'ls', 'show', 's', 'extract', 'x', 'import', 'imp', 'replace', 'rep', 'remove', 'rm', 'info')
    'texture' = @('list', 'ls', 'show', 's', 'extract', 'x', 'replace', 'rep')
    'data' = @('list', 'ls', 'show', 's', 'dump', 'd', 'set-cell', 'sc')
    'scene' = @('list', 'ls', 'show', 's', 'set')
    'entity' = @('list', 'ls', 'show', 's', 'set-position', 'sp', 'set-parent', 'set-camera', 'sc', 'set-light', 'sl')
    'material' = @('list', 'ls', 'show', 's', 'set')
    'mesh' = @('list', 'ls', 'show', 's', 'export', 'x', 'import', 'imp')
    'animation' = @('list', 'ls', 'show', 's', 'keys', 'k', 'export', 'x', 'import', 'imp')
    'type' = @('list', 'ls', 'show', 's', 'class-tree', 'ct')
    'validate' = @('all', 'a', 'structure', 'st', 'references', 'ref', 'resources', 'res', 'orphans', 'orp')
    'convert' = @('copy', 'cp', 'version', 'v', 'strip', 'st', 'merge', 'm', 'export', 'x')
    'diff' = @('summary', 's', 'objects', 'obj', 'chunks', 'ch', 'full', 'f')
    'query' = @('eval', 'e', 'script', 's', 'schema', 'sc', 'module', 'm')
    'extension' = @('list', 'ls', 'load', 'ld', 'info', 'i', 'check', 'ch')
    'completion' = @('bash', 'fish', 'zsh', 'powershell', 'ps1')
    'debug' = @('load-phases', 'lp', 'chunks', 'ch', 'objects', 'obj', 'export', 'x')
    'repl' = @('start')
}
$_nmo_sub_actions = @{
    'behavior/interface' = @('show', 'set-pos', 'fold', 'unfold', 'set-color', 'canonicalize', 'add-comment', 'remove-comment', 'set-comment-text', 'move-comment', 'set-comment-style', 'add-point', 'clear-points', 'remove-point', 'move-point', 'set-link-highlight', 'move-op', 'move-param', 'set-param-style', 'resize', 'set-expand', 'set-viewport', 'set-graph-io', 'translate')
    'behavior/iface' = @('show', 'set-pos', 'fold', 'unfold', 'set-color', 'canonicalize', 'add-comment', 'remove-comment', 'set-comment-text', 'move-comment', 'set-comment-style', 'add-point', 'clear-points', 'remove-point', 'move-point', 'set-link-highlight', 'move-op', 'move-param', 'set-param-style', 'resize', 'set-expand', 'set-viewport', 'set-graph-io', 'translate')
}
$_nmo_aliases = @{
    'f' = 'file'
    'ch' = 'chunk'
    'obj' = 'object'
    'beh' = 'behavior'
    'param' = 'parameter'
    'res' = 'resource'
    'tex' = 'texture'
    'da' = 'data'
    'sc' = 'scene'
    'ent' = 'entity'
    'mat' = 'material'
    'm' = 'mesh'
    'anim' = 'animation'
    't' = 'type'
    'val' = 'validate'
    'conv' = 'convert'
    'd' = 'diff'
    'q' = 'query'
    'ext' = 'extension'
    'comp' = 'completion'
    'dbg' = 'debug'
}
$_nmo_group_descriptions = @{
    'file' = 'File information and statistics'
    'chunk' = 'Chunk inspection'
    'object' = 'Object inspection'
    'behavior' = 'Behavior inspection'
    'parameter' = 'Parameter inspection'
    'resource' = 'Resource management'
    'texture' = 'Texture management'
    'data' = 'Data array inspection'
    'scene' = 'Scene/level inspection'
    'entity' = '3D entity inspection'
    'material' = 'Material inspection'
    'mesh' = 'Mesh inspection and export'
    'animation' = 'Animation inspection and export'
    'type' = 'Type system information'
    'validate' = 'File validation'
    'convert' = 'Format conversion'
    'diff' = 'File comparison'
    'query' = 'DSL query engine'
    'extension' = 'Extension management'
    'completion' = 'Shell completion scripts'
    'debug' = 'Debugging tools'
    'repl' = 'Interactive debugger'
}
$_nmo_flags = @(
    @{ Name = '-h'; Desc = 'Show help' }
    @{ Name = '--help'; Desc = 'Show help' }
    @{ Name = '-V'; Desc = 'Show version' }
    @{ Name = '--version'; Desc = 'Show version' }
    @{ Name = '-f'; Desc = 'Output format' }
    @{ Name = '--format'; Desc = 'Output format' }
    @{ Name = '--color'; Desc = 'Color mode' }
    @{ Name = '-o'; Desc = 'Write output to file' }
    @{ Name = '--output'; Desc = 'Write output to file' }
    @{ Name = '-v'; Desc = 'Increase verbosity' }
    @{ Name = '--verbose'; Desc = 'Increase verbosity' }
    @{ Name = '-q'; Desc = 'Suppress non-essential output' }
    @{ Name = '--quiet'; Desc = 'Suppress non-essential output' }
    @{ Name = '--no-pager'; Desc = 'Disable pager' }
    @{ Name = '--strict'; Desc = 'Enable strict validation mode' }
    @{ Name = '--fail-on-warning'; Desc = 'Exit with code 4 on warnings' }
    @{ Name = '--plugin'; Desc = 'Load extension plugin' }
    @{ Name = '-F'; Desc = 'Filter objects by name pattern' }
    @{ Name = '--filter'; Desc = 'Filter objects by name pattern' }
    @{ Name = '--batch'; Desc = 'Process multiple files' }
    @{ Name = '-c'; Desc = 'Filter by class' }
    @{ Name = '--class'; Desc = 'Filter by class' }
    @{ Name = '-n'; Desc = 'Filter by name' }
    @{ Name = '--name'; Desc = 'Filter by name' }
    @{ Name = '-i'; Desc = 'Select by index' }
    @{ Name = '--index'; Desc = 'Select by index' }
    @{ Name = '-m'; Desc = 'Limit emitted bytes' }
    @{ Name = '--max-bytes'; Desc = 'Limit emitted bytes' }
    @{ Name = '-d'; Desc = 'Output directory' }
    @{ Name = '--out-dir'; Desc = 'Output directory' }
    @{ Name = '--id'; Desc = 'Object ID' }
    @{ Name = '--top'; Desc = 'Show top N results' }
    @{ Name = '--sort'; Desc = 'Sort output' }
    @{ Name = '--reverse'; Desc = 'Reverse sort order' }
    @{ Name = '--dry-run'; Desc = 'Preview changes' }
    @{ Name = '--overwrite'; Desc = 'Overwrite existing files' }
    @{ Name = '--fix'; Desc = 'Show suggested fixes' }
    @{ Name = '--summary'; Desc = 'Summary only' }
    @{ Name = '--strip'; Desc = 'Strip matching data' }
    @{ Name = '--cascade'; Desc = 'Include dependents' }
    @{ Name = '--create'; Desc = 'Create missing objects' }
    @{ Name = '--dot'; Desc = 'Output DOT graph' }
    @{ Name = '--raw'; Desc = 'Show raw data' }
    @{ Name = '--all'; Desc = 'Process all matching entries' }
    @{ Name = '--replace'; Desc = 'Replace existing entry' }
)

Register-ArgumentCompleter -CommandName nmo -Native -ScriptBlock {
    param($wordToComplete, $commandAst, $cursorPosition)
    $tokens = $commandAst.ToString().Substring(0, $cursorPosition).Trim() -split '\s+'
    $valueOptions = @('-f','--format','--color','-o','--output','--plugin','-F','--filter','-c','--class','-n','--name','-i','--index','-m','--max-bytes','-d','--out-dir','--id','--top','--sort','--replace')
    $positional = @()
    $expectValue = $false
    for ($i = 1; $i -lt $tokens.Count; $i++) {
        if ($expectValue) { $expectValue = $false; continue }
        if ($tokens[$i].StartsWith('-')) { if ($valueOptions -contains $tokens[$i]) { $expectValue = $true }; continue }
        $positional += $tokens[$i]
    }
    if ($wordToComplete -ne '' -and $positional.Count -gt 0 -and $tokens[-1] -eq $wordToComplete) {
        $positional = @($positional[0..($positional.Count - 2)])
    }
    if ($wordToComplete.StartsWith('-')) {
        $_nmo_flags | Where-Object { $_.Name -like "$wordToComplete*" } | ForEach-Object { [System.Management.Automation.CompletionResult]::new($_.Name, $_.Name, 'ParameterValue', $_.Desc) }
        return
    }
    if ($positional.Count -eq 0) {
        $items = @()
        foreach ($g in $_nmo_groups.Keys) { $items += @{ Name = $g; Desc = $_nmo_group_descriptions[$g] } }
        foreach ($a in $_nmo_aliases.Keys) { $items += @{ Name = $a; Desc = "Alias for $($_nmo_aliases[$a])" } }
        $items | Where-Object { $_.Name -like "$wordToComplete*" } | Sort-Object Name | ForEach-Object { [System.Management.Automation.CompletionResult]::new($_.Name, $_.Name, 'ParameterValue', $_.Desc) }
        return
    }
    $group = $positional[0]
    if ($_nmo_aliases.ContainsKey($group)) { $group = $_nmo_aliases[$group] }
    if ($positional.Count -eq 1 -and $_nmo_groups.ContainsKey($group)) {
        $_nmo_groups[$group] | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object { [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', "$group $_") }
        return
    }
    if ($positional.Count -eq 2) {
        $key = "$group/$($positional[1])"
        if ($_nmo_sub_actions.ContainsKey($key)) {
            $_nmo_sub_actions[$key] | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object { [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', "$key $_") }
            return
        }
    }
    $pattern = if ($wordToComplete) { "$wordToComplete*" } else { '*' }
    Get-ChildItem -Path . -Filter $pattern -File -ErrorAction SilentlyContinue | Where-Object { $_.Extension -in '.nmo', '.cmo', '.vmo', '.json', '.obj' } | ForEach-Object { [System.Management.Automation.CompletionResult]::new($_.Name, $_.Name, 'ProviderItem', $_.Name) }
    $_nmo_flags | Where-Object { $_.Name -like "$wordToComplete*" } | ForEach-Object { [System.Management.Automation.CompletionResult]::new($_.Name, $_.Name, 'ParameterValue', $_.Desc) }
}
