# Bash completion for nmo - Virtools NMO file tool
# Auto-generated by tools/scripts/gen_completions.py; do not edit by hand.


_nmo() {
    local cur prev words cword
    if declare -F _init_completion >/dev/null 2>&1; then
        _init_completion || return
    else
        COMPREPLY=()
        cur=${COMP_WORDS[COMP_CWORD]}
        prev=${COMP_WORDS[COMP_CWORD-1]}
        words=("${COMP_WORDS[@]}")
        cword=$COMP_CWORD
    fi
    local groups="file f chunk ch object obj behavior beh parameter param resource res texture tex data da scene sc entity ent material mat mesh m animation anim type t validate val convert conv diff d query q extension ext completion comp debug dbg repl"
    local flags="-h --help -V --version -f --format --color -o --output -v --verbose -q --quiet --no-pager --strict --fail-on-warning --plugin -F --filter --batch"
    local value_options="-f --format --color -o --output --plugin -F --filter -c --class -n --name -i --index -m --max-bytes -d --out-dir --id --top --sort --replace"

    case "$prev" in
        -f|--format) COMPREPLY=( $(compgen -W "text json json-pretty" -- "$cur") ); return ;;
        --color) COMPREPLY=( $(compgen -W "auto always never" -- "$cur") ); return ;;
        -o|--output|--plugin|-F|--filter|-d|--out-dir) compopt -o filenames 2>/dev/null; COMPREPLY=( $(compgen -f -- "$cur") ); return ;;
        --*) if [[ " $value_options " == *" $prev "* ]]; then return; fi ;;
        -*) if [[ " $value_options " == *" $prev "* ]]; then return; fi ;;
    esac

    _nmo_resolve_group() {
        case "$1" in
            f) echo 'file' ;;
            ch) echo 'chunk' ;;
            obj) echo 'object' ;;
            beh) echo 'behavior' ;;
            param) echo 'parameter' ;;
            res) echo 'resource' ;;
            tex) echo 'texture' ;;
            da) echo 'data' ;;
            sc) echo 'scene' ;;
            ent) echo 'entity' ;;
            mat) echo 'material' ;;
            m) echo 'mesh' ;;
            anim) echo 'animation' ;;
            t) echo 'type' ;;
            val) echo 'validate' ;;
            conv) echo 'convert' ;;
            d) echo 'diff' ;;
            q) echo 'query' ;;
            ext) echo 'extension' ;;
            comp) echo 'completion' ;;
            dbg) echo 'debug' ;;
            *) echo "$1" ;;
        esac
    }

    _nmo_actions() {
        case "$1" in
            file) echo 'info i header hdr stats st classes cls plugins pl space sp' ;;
            chunk) echo 'list ls tree t show s find f' ;;
            object) echo 'list ls tree t show s find f refs r rename ren export x impact imp orphans orp cycles cyc delete del create copy cp import-json graph gr set-field sf list-fields lf' ;;
            behavior) echo 'list ls stats st show s graph g dump d find f trace tr add-link remove-link interface iface' ;;
            parameter) echo 'list ls show s dump d set' ;;
            resource) echo 'list ls show s extract x import imp replace rep remove rm info' ;;
            texture) echo 'list ls show s extract x replace rep' ;;
            data) echo 'list ls show s dump d set-cell sc' ;;
            scene) echo 'list ls show s set' ;;
            entity) echo 'list ls show s set-position sp set-parent set-camera sc set-light sl' ;;
            material) echo 'list ls show s set' ;;
            mesh) echo 'list ls show s export x import imp' ;;
            animation) echo 'list ls show s keys k export x import imp' ;;
            type) echo 'list ls show s class-tree ct' ;;
            validate) echo 'all a structure st references ref resources res orphans orp' ;;
            convert) echo 'copy cp version v strip st merge m export x' ;;
            diff) echo 'summary s objects obj chunks ch full f' ;;
            query) echo 'eval e script s schema sc module m' ;;
            extension) echo 'list ls load ld info i check ch' ;;
            completion) echo 'bash fish zsh powershell ps1' ;;
            debug) echo 'load-phases lp chunks ch objects obj export x' ;;
            repl) echo 'start' ;;
            *) echo "" ;;
        esac
    }

    _nmo_sub_actions() {
        case "$1/$2" in
            behavior/interface) echo 'show set-pos fold unfold set-color canonicalize add-comment remove-comment set-comment-text move-comment set-comment-style add-point clear-points remove-point move-point set-link-highlight move-op move-param set-param-style resize set-expand set-viewport set-graph-io translate' ;;
            behavior/iface) echo 'show set-pos fold unfold set-color canonicalize add-comment remove-comment set-comment-text move-comment set-comment-style add-point clear-points remove-point move-point set-link-highlight move-op move-param set-param-style resize set-expand set-viewport set-graph-io translate' ;;
            *) echo "" ;;
        esac
    }

    local positional=()
    local expect_value=0
    local i word
    for (( i=1; i < cword; i++ )); do
        word=${words[$i]}
        if (( expect_value )); then expect_value=0; continue; fi
        if [[ "$word" == -* ]]; then
            if [[ " $value_options " == *" $word "* ]]; then expect_value=1; fi
            continue
        fi
        positional+=("$word")
    done

    if [[ "$cur" == -* ]]; then COMPREPLY=( $(compgen -W "$flags" -- "$cur") ); return; fi
    if (( ${#positional[@]} == 0 )); then COMPREPLY=( $(compgen -W "$groups" -- "$cur") ); return; fi
    local group canonical actions subactions
    group=${positional[0]}
    canonical=$(_nmo_resolve_group "$group")
    if (( ${#positional[@]} == 1 )); then
        actions=$(_nmo_actions "$canonical")
        COMPREPLY=( $(compgen -W "$actions" -- "$cur") )
        return
    fi
    if (( ${#positional[@]} == 2 )); then
        subactions=$(_nmo_sub_actions "$canonical" "${positional[1]}")
        if [[ -n "$subactions" ]]; then
            COMPREPLY=( $(compgen -W "$subactions" -- "$cur") )
            return
        fi
    fi
    local IFS=$'\n'
    COMPREPLY=( $(compgen -f -X '!*.@(nmo|cmo|vmo|json|obj)' -- "$cur") )
    COMPREPLY+=( $(compgen -d -- "$cur") )
    compopt -o filenames 2>/dev/null
}

complete -o default -F _nmo nmo
