/**
 * @file test_public_api_smoke.c
 * @brief Smoke tests for the main public header (nmo.h)
 */

#include "test_framework.h"
#include "nmo.h"
#include "app/nmo_comparison.h"
#include "app/nmo_load.h"
#include "app/nmo_object_diff.h"
#include "app/nmo_object_import.h"
#include "app/nmo_report_result.h"
#include "app/nmo_save.h"
#include "app/nmo_object_summary.h"
#include "behavior/nmo_bb_registry.h"
#include "behavior/nmo_behavior_graph.h"
#include "behavior/nmo_behavior_index.h"
#include "behavior/nmo_behavior_view.h"
#include "behavior/nmo_script_edit.h"
#include "behavior/nmo_script_edit_graph.h"
#include "behavior/nmo_script_view.h"
#include "behavior/nmo_script_walker.h"
#include "extension/nmo_extension_registry.h"
#include "format/nmo_chunk_api.h"
#include "format/nmo_interface_chunk.h"
#include "format/nmo_interface_edit.h"
#include "format/nmo_interface_view.h"
#include "format/nmo_object.h"
#include "object/nmo_object_index.h"
#include "object/nmo_object_query.h"
#include "object/nmo_object_iter.h"
#include "object/nmo_ref_query.h"
#include "object/nmo_ref_graph.h"
#include "object/nmo_object_type_common.h"
#include "object/nmo_object_repository.h"
#include "session/nmo_context.h"
#include "session/nmo_reference_resolver.h"
#include "session/nmo_session_query.h"
#include "session/nmo_session_edit.h"
#include "session/nmo_session_pipeline.h"
#include "session/nmo_runtime_kernel.h"
#include "session/nmo_serializer.h"
#include "session/nmo_session.h"
#include "type/nmo_operation_system.h"
#include "type/nmo_reflection.h"
#include "type/nmo_type_query.h"
#include "type/nmo_type_runtime.h"
#include "type/nmo_type_system.h"
#include "type/nmo_type_view.h"

#ifdef NMO_JSON_STREAM_PUBLIC_HEADER_KIND
#define NMO_TEST_HAS_JSON_STREAM_PUBLIC_API 1
#else
#define NMO_TEST_HAS_JSON_STREAM_PUBLIC_API 0
#endif

TEST(public_api_smoke, version) {
    const char *ver = nmo_version();
    ASSERT_NOT_NULL(ver);
    ASSERT_TRUE(ver[0] != '\0');

    uint32_t ver_int = nmo_version_int();
    ASSERT_NE(0u, ver_int);
}

TEST(public_api_smoke, context_create_release) {
    nmo_context_desc_t desc = {0};
    nmo_context_t *ctx = nmo_context_create(&desc);
    ASSERT_NOT_NULL(ctx);

    nmo_context_release(ctx);
}

TEST(public_api_smoke, preferred_edit_and_query_headers_are_directly_usable) {
    nmo_session_edit_t *edit = NULL;
    nmo_object_query_t query = {0};
    query.name_mode = NMO_OBJECT_QUERY_NAME_EXACT;

    ASSERT_NULL(edit);
    ASSERT_EQ(NMO_OBJECT_QUERY_NAME_EXACT, query.name_mode);
}

TEST(public_api_smoke, report_result_headers_are_directly_usable) {
    nmo_comparison_result_stats_t comparison_stats = {0};
    nmo_diff_result_stats_t diff_stats = {0};
    nmo_object_summary_stats_t summary_stats = {0};

    ASSERT_FALSE(comparison_stats.match);
    ASSERT_EQ(0u, diff_stats.total_field_diffs);
    ASSERT_FALSE(summary_stats.has_reflection);
}

TEST(public_api_smoke, json_stream_is_not_part_of_public_api_surface) {
    ASSERT_FALSE(NMO_TEST_HAS_JSON_STREAM_PUBLIC_API);
}

TEST(public_api_smoke, public_api_tier_signals_are_declared) {
    ASSERT_EQ(NMO_PUBLIC_HEADER_KIND_MIXED_TIER, NMO_UMBRELLA_PUBLIC_HEADER_KIND);

    ASSERT_EQ(NMO_PUBLIC_HEADER_KIND_MIXED_TIER, NMO_CONTEXT_PUBLIC_HEADER_KIND);
    ASSERT_EQ(NMO_API_TIER_STABLE_CONSUMER, NMO_CONTEXT_LIFECYCLE_API_TIER);
    ASSERT_EQ(NMO_API_TIER_ADVANCED_C, NMO_CONTEXT_REGISTRY_ACCESS_API_TIER);
    ASSERT_EQ(NMO_API_TIER_ADVANCED_C, NMO_CONTEXT_RUNTIME_VIEW_API_TIER);

    ASSERT_EQ(NMO_PUBLIC_HEADER_KIND_MIXED_TIER, NMO_SESSION_PUBLIC_HEADER_KIND);
    ASSERT_EQ(NMO_API_TIER_STABLE_CONSUMER, NMO_SESSION_WORKFLOW_API_TIER);
    ASSERT_EQ(NMO_API_TIER_ADVANCED_C, NMO_SESSION_EXECUTION_API_TIER);
    ASSERT_EQ(NMO_API_TIER_ADVANCED_C, NMO_SESSION_ACCELERATION_CACHE_API_TIER);

    ASSERT_EQ(NMO_PUBLIC_HEADER_KIND_SINGLE_TIER, NMO_RUNTIME_KERNEL_PUBLIC_HEADER_KIND);
    ASSERT_EQ(NMO_API_TIER_ADVANCED_C, NMO_RUNTIME_KERNEL_API_TIER);

    ASSERT_EQ(NMO_PUBLIC_HEADER_KIND_SINGLE_TIER, NMO_REFERENCE_RESOLVER_PUBLIC_HEADER_KIND);
    ASSERT_EQ(NMO_API_TIER_ADVANCED_C, NMO_REFERENCE_RESOLVER_API_TIER);

    ASSERT_EQ(NMO_PUBLIC_HEADER_KIND_SINGLE_TIER, NMO_SERIALIZER_PUBLIC_HEADER_KIND);
    ASSERT_EQ(NMO_API_TIER_ADVANCED_C, NMO_SERIALIZER_API_TIER);

    ASSERT_EQ(NMO_PUBLIC_HEADER_KIND_SINGLE_TIER, NMO_SESSION_PIPELINE_PUBLIC_HEADER_KIND);
    ASSERT_EQ(NMO_API_TIER_ADVANCED_C, NMO_SESSION_PIPELINE_API_TIER);

    ASSERT_EQ(NMO_PUBLIC_HEADER_KIND_SINGLE_TIER, NMO_SESSION_EDIT_PUBLIC_HEADER_KIND);
    ASSERT_EQ(NMO_API_TIER_STABLE_CONSUMER, NMO_SESSION_EDIT_TRANSACTION_API_TIER);

    ASSERT_EQ(NMO_PUBLIC_HEADER_KIND_MIXED_TIER, NMO_OBJECT_REPOSITORY_PUBLIC_HEADER_KIND);
    ASSERT_EQ(NMO_API_TIER_STABLE_CONSUMER, NMO_OBJECT_REPOSITORY_IDENTITY_API_TIER);
    ASSERT_EQ(NMO_API_TIER_ADVANCED_C, NMO_OBJECT_REPOSITORY_SCRATCH_RESULT_API_TIER);

    ASSERT_EQ(NMO_PUBLIC_HEADER_KIND_SINGLE_TIER, NMO_OBJECT_INDEX_PUBLIC_HEADER_KIND);
    ASSERT_EQ(NMO_API_TIER_ADVANCED_C, NMO_OBJECT_INDEX_API_TIER);

    ASSERT_EQ(NMO_PUBLIC_HEADER_KIND_SINGLE_TIER, NMO_OBJECT_QUERY_PUBLIC_HEADER_KIND);
    ASSERT_EQ(NMO_API_TIER_ADVANCED_C, NMO_OBJECT_QUERY_ENGINE_API_TIER);

    ASSERT_EQ(NMO_PUBLIC_HEADER_KIND_MIXED_TIER, NMO_REF_GRAPH_PUBLIC_HEADER_KIND);
    ASSERT_EQ(NMO_API_TIER_PUBLIC_PROTOCOL, NMO_REF_GRAPH_KIND_ENUM_API_TIER);
    ASSERT_EQ(NMO_API_TIER_ADVANCED_C, NMO_REF_GRAPH_ANALYSIS_API_TIER);

    ASSERT_EQ(NMO_PUBLIC_HEADER_KIND_SINGLE_TIER, NMO_OBJECT_TYPE_COMMON_PUBLIC_HEADER_KIND);
    ASSERT_EQ(NMO_API_TIER_PUBLIC_PROTOCOL, NMO_OBJECT_TYPE_COMMON_API_TIER);

    ASSERT_EQ(NMO_PUBLIC_HEADER_KIND_MIXED_TIER, NMO_TYPE_QUERY_PUBLIC_HEADER_KIND);
    ASSERT_EQ(NMO_API_TIER_STABLE_CONSUMER, NMO_TYPE_QUERY_SCALAR_LOOKUP_API_TIER);
    ASSERT_EQ(NMO_API_TIER_ADVANCED_C, NMO_TYPE_QUERY_DESCRIPTOR_VIEW_API_TIER);
    ASSERT_EQ(NMO_API_TIER_ADVANCED_C, NMO_TYPE_QUERY_STATE_VIEW_API_TIER);

    ASSERT_EQ(NMO_PUBLIC_HEADER_KIND_MIXED_TIER, NMO_TYPE_SYSTEM_PUBLIC_HEADER_KIND);
    ASSERT_EQ(NMO_API_TIER_ADVANCED_C, NMO_TYPE_SYSTEM_REGISTRY_API_TIER);
    ASSERT_EQ(NMO_API_TIER_PUBLIC_PROTOCOL, NMO_TYPE_SYSTEM_AUTHORING_API_TIER);

    ASSERT_EQ(NMO_PUBLIC_HEADER_KIND_MIXED_TIER, NMO_REFLECTION_PUBLIC_HEADER_KIND);
    ASSERT_EQ(NMO_API_TIER_ADVANCED_C, NMO_REFLECTION_FIELD_QUERY_API_TIER);
    ASSERT_EQ(NMO_API_TIER_PUBLIC_PROTOCOL, NMO_REFLECTION_AUTHORING_API_TIER);

    ASSERT_EQ(NMO_PUBLIC_HEADER_KIND_MIXED_TIER, NMO_OPERATION_SYSTEM_PUBLIC_HEADER_KIND);
    ASSERT_EQ(NMO_API_TIER_ADVANCED_C, NMO_OPERATION_SYSTEM_LIFECYCLE_API_TIER);
    ASSERT_EQ(NMO_API_TIER_ADVANCED_C, NMO_OPERATION_SYSTEM_LOOKUP_API_TIER);
    ASSERT_EQ(NMO_API_TIER_ADVANCED_C, NMO_OPERATION_SYSTEM_EXECUTION_API_TIER);
    ASSERT_EQ(NMO_API_TIER_ADVANCED_C, NMO_OPERATION_SYSTEM_INTROSPECTION_API_TIER);
    ASSERT_EQ(NMO_API_TIER_PUBLIC_PROTOCOL, NMO_OPERATION_SYSTEM_AUTHORING_API_TIER);

    ASSERT_EQ(NMO_PUBLIC_HEADER_KIND_SINGLE_TIER, NMO_TYPE_RUNTIME_PUBLIC_HEADER_KIND);
    ASSERT_EQ(NMO_API_TIER_ADVANCED_C, NMO_TYPE_RUNTIME_AGGREGATE_API_TIER);

    ASSERT_EQ(NMO_PUBLIC_HEADER_KIND_SINGLE_TIER, NMO_TYPE_VIEW_PUBLIC_HEADER_KIND);
    ASSERT_EQ(NMO_API_TIER_STABLE_CONSUMER, NMO_TYPE_VIEW_METADATA_API_TIER);

    ASSERT_EQ(NMO_PUBLIC_HEADER_KIND_SINGLE_TIER, NMO_BB_REGISTRY_PUBLIC_HEADER_KIND);
    ASSERT_EQ(NMO_API_TIER_ADVANCED_C, NMO_BB_REGISTRY_API_TIER);

    ASSERT_EQ(NMO_PUBLIC_HEADER_KIND_SINGLE_TIER, NMO_BEHAVIOR_GRAPH_PUBLIC_HEADER_KIND);
    ASSERT_EQ(NMO_API_TIER_ADVANCED_C, NMO_BEHAVIOR_GRAPH_API_TIER);

    ASSERT_EQ(NMO_PUBLIC_HEADER_KIND_SINGLE_TIER, NMO_BEHAVIOR_INDEX_PUBLIC_HEADER_KIND);
    ASSERT_EQ(NMO_API_TIER_ADVANCED_C, NMO_BEHAVIOR_INDEX_API_TIER);

    ASSERT_EQ(NMO_PUBLIC_HEADER_KIND_SINGLE_TIER, NMO_SCRIPT_EDIT_PUBLIC_HEADER_KIND);
    ASSERT_EQ(NMO_API_TIER_STABLE_CONSUMER, NMO_SCRIPT_EDIT_TRANSACTION_API_TIER);

    ASSERT_EQ(NMO_PUBLIC_HEADER_KIND_SINGLE_TIER, NMO_SCRIPT_EDIT_GRAPH_PUBLIC_HEADER_KIND);
    ASSERT_EQ(NMO_API_TIER_ADVANCED_C, NMO_SCRIPT_EDIT_GRAPH_API_TIER);

    ASSERT_EQ(NMO_PUBLIC_HEADER_KIND_SINGLE_TIER, NMO_SCRIPT_WALKER_PUBLIC_HEADER_KIND);
    ASSERT_EQ(NMO_API_TIER_ADVANCED_C, NMO_SCRIPT_WALKER_API_TIER);

    ASSERT_EQ(NMO_PUBLIC_HEADER_KIND_SINGLE_TIER, NMO_BEHAVIOR_VIEW_PUBLIC_HEADER_KIND);
    ASSERT_EQ(NMO_API_TIER_STABLE_CONSUMER, NMO_BEHAVIOR_VIEW_READ_API_TIER);

    ASSERT_EQ(NMO_PUBLIC_HEADER_KIND_SINGLE_TIER, NMO_SCRIPT_VIEW_PUBLIC_HEADER_KIND);
    ASSERT_EQ(NMO_API_TIER_STABLE_CONSUMER, NMO_SCRIPT_VIEW_READ_API_TIER);

    ASSERT_EQ(NMO_PUBLIC_HEADER_KIND_SINGLE_TIER, NMO_CHUNK_API_PUBLIC_HEADER_KIND);
    ASSERT_EQ(NMO_API_TIER_PUBLIC_PROTOCOL, NMO_CHUNK_API_COMPAT_API_TIER);

    ASSERT_EQ(NMO_PUBLIC_HEADER_KIND_MIXED_TIER, NMO_INTERFACE_CHUNK_PUBLIC_HEADER_KIND);
    ASSERT_EQ(NMO_API_TIER_PUBLIC_PROTOCOL, NMO_INTERFACE_CHUNK_LAYOUT_API_TIER);
    ASSERT_EQ(NMO_API_TIER_ADVANCED_C, NMO_INTERFACE_CHUNK_TYPE_REGISTRATION_API_TIER);

    ASSERT_EQ(NMO_PUBLIC_HEADER_KIND_SINGLE_TIER, NMO_INTERFACE_EDIT_PUBLIC_HEADER_KIND);
    ASSERT_EQ(NMO_API_TIER_ADVANCED_C, NMO_INTERFACE_EDIT_API_TIER);

    ASSERT_EQ(NMO_PUBLIC_HEADER_KIND_SINGLE_TIER, NMO_INTERFACE_VIEW_PUBLIC_HEADER_KIND);
    ASSERT_EQ(NMO_API_TIER_STABLE_CONSUMER, NMO_INTERFACE_VIEW_READ_API_TIER);

    ASSERT_EQ(NMO_PUBLIC_HEADER_KIND_SINGLE_TIER, NMO_FORMAT_OBJECT_PUBLIC_HEADER_KIND);
    ASSERT_EQ(NMO_API_TIER_PUBLIC_PROTOCOL, NMO_FORMAT_OBJECT_LAYOUT_API_TIER);

    ASSERT_EQ(NMO_PUBLIC_HEADER_KIND_SINGLE_TIER, NMO_LOAD_PUBLIC_HEADER_KIND);
    ASSERT_EQ(NMO_API_TIER_STABLE_CONSUMER, NMO_LOAD_WORKFLOW_API_TIER);

    ASSERT_EQ(NMO_PUBLIC_HEADER_KIND_SINGLE_TIER, NMO_SAVE_PUBLIC_HEADER_KIND);
    ASSERT_EQ(NMO_API_TIER_STABLE_CONSUMER, NMO_SAVE_WORKFLOW_API_TIER);

    ASSERT_EQ(NMO_PUBLIC_HEADER_KIND_SINGLE_TIER, NMO_OBJECT_SUMMARY_PUBLIC_HEADER_KIND);
    ASSERT_EQ(NMO_API_TIER_ADVANCED_C, NMO_OBJECT_SUMMARY_RENDERING_API_TIER);

    ASSERT_EQ(NMO_PUBLIC_HEADER_KIND_SINGLE_TIER, NMO_OBJECT_DIFF_PUBLIC_HEADER_KIND);
    ASSERT_EQ(NMO_API_TIER_ADVANCED_C, NMO_OBJECT_DIFF_API_TIER);

    ASSERT_EQ(NMO_PUBLIC_HEADER_KIND_SINGLE_TIER, NMO_COMPARISON_PUBLIC_HEADER_KIND);
    ASSERT_EQ(NMO_API_TIER_ADVANCED_C, NMO_COMPARISON_API_TIER);

    ASSERT_EQ(NMO_PUBLIC_HEADER_KIND_SINGLE_TIER, NMO_OBJECT_IMPORT_PUBLIC_HEADER_KIND);
    ASSERT_EQ(NMO_API_TIER_ADVANCED_C, NMO_OBJECT_IMPORT_API_TIER);

    ASSERT_EQ(NMO_PUBLIC_HEADER_KIND_SINGLE_TIER, NMO_REPORT_RESULT_PUBLIC_HEADER_KIND);
    ASSERT_EQ(NMO_API_TIER_STABLE_CONSUMER, NMO_REPORT_RESULT_API_TIER);

    ASSERT_EQ(NMO_PUBLIC_HEADER_KIND_SINGLE_TIER, NMO_SESSION_QUERY_PUBLIC_HEADER_KIND);
    ASSERT_EQ(NMO_API_TIER_STABLE_CONSUMER, NMO_SESSION_QUERY_READ_API_TIER);

    ASSERT_EQ(NMO_PUBLIC_HEADER_KIND_SINGLE_TIER, NMO_OBJECT_ITER_PUBLIC_HEADER_KIND);
    ASSERT_EQ(NMO_API_TIER_STABLE_CONSUMER, NMO_OBJECT_ITER_READ_API_TIER);

    ASSERT_EQ(NMO_PUBLIC_HEADER_KIND_SINGLE_TIER, NMO_REF_QUERY_PUBLIC_HEADER_KIND);
    ASSERT_EQ(NMO_API_TIER_STABLE_CONSUMER, NMO_REF_QUERY_READ_API_TIER);

    ASSERT_EQ(NMO_PUBLIC_HEADER_KIND_SINGLE_TIER, NMO_EXTENSION_REGISTRY_PUBLIC_HEADER_KIND);
    ASSERT_EQ(NMO_API_TIER_ADVANCED_C, NMO_EXTENSION_REGISTRY_API_TIER);
}

TEST_MAIN_BEGIN()
    REGISTER_TEST(public_api_smoke, version);
    REGISTER_TEST(public_api_smoke, context_create_release);
    REGISTER_TEST(public_api_smoke, preferred_edit_and_query_headers_are_directly_usable);
    REGISTER_TEST(public_api_smoke, report_result_headers_are_directly_usable);
    REGISTER_TEST(public_api_smoke, json_stream_is_not_part_of_public_api_surface);
    REGISTER_TEST(public_api_smoke, public_api_tier_signals_are_declared);
TEST_MAIN_END()
